/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (DESIGN.md §5).

Education Department aid.

Continues the module of the same name. The law
here quotes rules from other agencies, which Lean
must see first; the split is a compilation order,
not a distinction in the law.
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.Entity
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale
import Lawlib.Household
import Lawlib.Parameters
import Lawlib.USA.DOE
import Lawlib.USA.SSA
import Lawlib.USA.HUD
import Lawlib.USA.FCC
import Lawlib.USA.IRS
import Lawlib.USA.ED
import Lawlib.USA.ACA
import Lawlib.USA.General
import Lawlib.USA.USDA
import Lawlib.USA.HHS
import Lawlib.USA.SSA.Part2
import Lawlib.USA.HUD.Part2
import Lawlib.USA.IRS.Part2

namespace Lawlib.USA
open Lawlib
open Lawlib.Parameters

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/ed/pell_grant/efc/pell_grant_dependents_in_college.py`
    policyengine-us 1.783.0, entity tax_unit, value_type int. -/
def pellGrantDependentsInCollege (t : TaxUnit) (d : Date) : Rat :=
  (sumBy t.members fun p => ((boolToRat (isTaxUnitDependent t p d)) *
      (boolToRat p.coreP1.isFullTimeCollegeStudent)))

/-- `pell_grant_household_type.py`
    in `policyengine_us/variables/gov/ed/pell_grant/sai/eligibility_type/`
    policyengine-us 1.783.0, entity person, value_type Enum. -/
def pellGrantHouseholdType (t : TaxUnit) (p : Person) (d : Date) : PellGrantHouseholdType :=
  (if ((isTaxUnitDependent t p d) && (!(taxUnitIsJoint t d))) then
      PellGrantHouseholdType.DEPENDENT_SINGLE else (if ((isTaxUnitDependent t p d) &&
      (taxUnitIsJoint t d)) then PellGrantHouseholdType.DEPENDENT_NOT_SINGLE else (if
      ((!(isTaxUnitDependent t p d)) && (!(taxUnitIsJoint t d))) then
      PellGrantHouseholdType.INDEPENDENT_SINGLE else (if
      ((!(isTaxUnitDependent t p d)) && (taxUnitIsJoint t d)) then
      PellGrantHouseholdType.INDEPENDENT_NOT_SINGLE else
      PellGrantHouseholdType.DEPENDENT_SINGLE))))

/-- `policyengine_us/variables/gov/ed/pell_grant/pell_grant_formula.py`
    policyengine-us 1.783.0, entity person, value_type Enum. -/
def pellGrantFormula (t : TaxUnit) (p : Person) (d : Date) : PellGrantFormula :=
  let has_dependents := (decide ((taxUnitDependents t d) > 0));
  let head_or_spouse := (p.coreP1.isTaxUnitHead || p.coreP1.isTaxUnitSpouse);
  (if (has_dependents && (!head_or_spouse)) then PellGrantFormula.A else (if
      ((!has_dependents) && head_or_spouse) then PellGrantFormula.B else
      PellGrantFormula.C))

/-- `pell_grant_max_fpg_limit.py`
    in `policyengine_us/variables/gov/ed/pell_grant/sai/eligibility_type/`
    policyengine-us 1.783.0, entity person, value_type float. -/
def pellGrantMaxFpgPercentLimit (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (match (pellGrantHouseholdType t p d) with
      | PellGrantHouseholdType.DEPENDENT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.max_pell_limits.DEPENDENT_SINGLE.atDate d)
      | PellGrantHouseholdType.DEPENDENT_NOT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.max_pell_limits.DEPENDENT_NOT_SINGLE.atDate d)
      | PellGrantHouseholdType.INDEPENDENT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.max_pell_limits.INDEPENDENT_SINGLE.atDate d)
      | PellGrantHouseholdType.INDEPENDENT_NOT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.max_pell_limits.INDEPENDENT_NOT_SINGLE.atDate d))

/-- `policyengine_us/variables/gov/ed/pell_grant/head/pell_grant_head_available_income.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def pellGrantHeadAvailableIncome (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  ((t.ed.pellGrantPrimaryIncome - p.ed.pellGrantHeadAllowances) * (match
      (pellGrantFormula t p d) with
      | PellGrantFormula.A => (ed.pell_grant.head.income_assessment_rate.A.atDate d)
      | PellGrantFormula.B => (ed.pell_grant.head.income_assessment_rate.B.atDate d)
      | PellGrantFormula.C => (ed.pell_grant.head.income_assessment_rate.C.atDate d)))

/-- `policyengine_us/variables/gov/ed/pell_grant/dependent/pell_grant_dependent_allowances.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def pellGrantDependentAllowances (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (((ed.pell_grant.dependent.ipa.atDate d) +
      (0 - (min ((pellGrantHeadAvailableIncome t p d) : Rat) 0))) +
      p.ed.pellGrantDependentOtherAllowances)

/-- `pell_grant_min_fpg_limit.py`
    in `policyengine_us/variables/gov/ed/pell_grant/sai/eligibility_type/`
    policyengine-us 1.783.0, entity person, value_type float. -/
def pellGrantMinFpgPercentLimit (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if ((((pellGrantHouseholdType t p d) == PellGrantHouseholdType.INDEPENDENT_SINGLE) ||
      ((pellGrantHouseholdType t p d) == PellGrantHouseholdType.INDEPENDENT_NOT_SINGLE)) &&
      (decide ((taxUnitChildDependents t d) = 0))) then
      (ed.pell_grant.sai.fpg_fraction.min_pell_limits.INDEPENDENT_NOT_PARENT.atDate d) else
      (match (pellGrantHouseholdType t p d) with
      | PellGrantHouseholdType.DEPENDENT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.min_pell_limits.DEPENDENT_SINGLE.atDate d)
      | PellGrantHouseholdType.DEPENDENT_NOT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.min_pell_limits.DEPENDENT_NOT_SINGLE.atDate d)
      | PellGrantHouseholdType.INDEPENDENT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.min_pell_limits.INDEPENDENT_SINGLE.atDate d)
      | PellGrantHouseholdType.INDEPENDENT_NOT_SINGLE =>
          (ed.pell_grant.sai.fpg_fraction.min_pell_limits.INDEPENDENT_NOT_SINGLE.atDate d)))

end Lawlib.USA
