import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.Entity
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale
import Lawlib.Core.Json
import Lawlib.Gen
import Lawlib.Gen.Irs.EicTable2023
import Lawlib.Verify.EicTable2023
import Lawlib.Verify.PeTable2023
import Lawlib.Theorems.Eitc2023
import Lawlib.Theorems.Ctc2023
import Lawlib.Claims
import Lawlib.Claims.Data
import Lawlib.Catala.Runtime
import Lawlib.Catala.Section32
import Lawlib.Verify.Catala2023
