import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.Entity
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale
import Lawlib.Core.Json
import Lawlib.Gen
import Lawlib.Gen.Irs.EicTable2023
import Lawlib.Verify.EicTable2023
import Lawlib.Claims
import Lawlib.Catala.Runtime
import Lawlib.Catala.Section32
