(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module EarnedIncomeCredit : sig
  type t = { credit: money; }
  include CatalaType with type t := t
end

module EarnedIncomeCredit_in : sig
  type t = {
    earned_income_in: money;
    adjusted_gross_income_in: money;
    qualifying_children_in: integer;
    joint_return_in: bool;
  }
  include CatalaType with type t := t
end


(** Toplevel definition loc *)
val loc : code_location array

(** Scope EarnedIncomeCredit *)
val earned_income_credit : EarnedIncomeCredit_in.t -> EarnedIncomeCredit.t
