/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (design §5).
-/
import Lean.Data.Json

namespace Lawlib

inductive AgeGroup where
  | CHILD
  | WORKING_AGE
  | SENIOR
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson AgeGroup where
  fromJson? j := do
    match (← j.getStr?) with
    | "CHILD" => pure .CHILD
    | "WORKING_AGE" => pure .WORKING_AGE
    | "SENIOR" => pure .SENIOR
    | s => throw s!"unknown AgeGroup: {s}"

instance : Lean.ToJson AgeGroup where
  toJson x := match x with
    | .CHILD => Lean.Json.str "CHILD"
    | .WORKING_AGE => Lean.Json.str "WORKING_AGE"
    | .SENIOR => Lean.Json.str "SENIOR"

/-- PolicyEngine's `decode_to_str` view. -/
def AgeGroup.asStr : AgeGroup → String
  | .CHILD => "CHILD"
  | .WORKING_AGE => "WORKING_AGE"
  | .SENIOR => "SENIOR"

inductive CCDFAgeGroup where
  | INFANT
  | TODDLER
  | PRESCHOOLER
  | SCHOOL_AGE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson CCDFAgeGroup where
  fromJson? j := do
    match (← j.getStr?) with
    | "INFANT" => pure .INFANT
    | "TODDLER" => pure .TODDLER
    | "PRESCHOOLER" => pure .PRESCHOOLER
    | "SCHOOL_AGE" => pure .SCHOOL_AGE
    | s => throw s!"unknown CCDFAgeGroup: {s}"

instance : Lean.ToJson CCDFAgeGroup where
  toJson x := match x with
    | .INFANT => Lean.Json.str "INFANT"
    | .TODDLER => Lean.Json.str "TODDLER"
    | .PRESCHOOLER => Lean.Json.str "PRESCHOOLER"
    | .SCHOOL_AGE => Lean.Json.str "SCHOOL_AGE"

/-- PolicyEngine's `decode_to_str` view. -/
def CCDFAgeGroup.asStr : CCDFAgeGroup → String
  | .INFANT => "INFANT"
  | .TODDLER => "TODDLER"
  | .PRESCHOOLER => "PRESCHOOLER"
  | .SCHOOL_AGE => "SCHOOL_AGE"

inductive CCDFDurationOfCare where
  | WEEKLY
  | DAILY
  | PART_DAY
  | HOURLY
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson CCDFDurationOfCare where
  fromJson? j := do
    match (← j.getStr?) with
    | "WEEKLY" => pure .WEEKLY
    | "DAILY" => pure .DAILY
    | "PART_DAY" => pure .PART_DAY
    | "HOURLY" => pure .HOURLY
    | s => throw s!"unknown CCDFDurationOfCare: {s}"

instance : Lean.ToJson CCDFDurationOfCare where
  toJson x := match x with
    | .WEEKLY => Lean.Json.str "WEEKLY"
    | .DAILY => Lean.Json.str "DAILY"
    | .PART_DAY => Lean.Json.str "PART_DAY"
    | .HOURLY => Lean.Json.str "HOURLY"

/-- PolicyEngine's `decode_to_str` view. -/
def CCDFDurationOfCare.asStr : CCDFDurationOfCare → String
  | .WEEKLY => "WEEKLY"
  | .DAILY => "DAILY"
  | .PART_DAY => "PART_DAY"
  | .HOURLY => "HOURLY"

inductive CHIPCategory where
  | CHILD
  | PREGNANT_STANDARD
  | PREGNANT_FCEP
  | NONE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson CHIPCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "CHILD" => pure .CHILD
    | "PREGNANT_STANDARD" => pure .PREGNANT_STANDARD
    | "PREGNANT_FCEP" => pure .PREGNANT_FCEP
    | "NONE" => pure .NONE
    | s => throw s!"unknown CHIPCategory: {s}"

instance : Lean.ToJson CHIPCategory where
  toJson x := match x with
    | .CHILD => Lean.Json.str "CHILD"
    | .PREGNANT_STANDARD => Lean.Json.str "PREGNANT_STANDARD"
    | .PREGNANT_FCEP => Lean.Json.str "PREGNANT_FCEP"
    | .NONE => Lean.Json.str "NONE"

/-- PolicyEngine's `decode_to_str` view. -/
def CHIPCategory.asStr : CHIPCategory → String
  | .CHILD => "CHILD"
  | .PREGNANT_STANDARD => "PREGNANT_STANDARD"
  | .PREGNANT_FCEP => "PREGNANT_FCEP"
  | .NONE => "NONE"

inductive ChildcareProviderTypeGroup where
  | DCC_SACC
  | FDC_GFDC
  | LE_GC
  | LE_STD
  | LE_ENH
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson ChildcareProviderTypeGroup where
  fromJson? j := do
    match (← j.getStr?) with
    | "DCC_SACC" => pure .DCC_SACC
    | "FDC_GFDC" => pure .FDC_GFDC
    | "LE_GC" => pure .LE_GC
    | "LE_STD" => pure .LE_STD
    | "LE_ENH" => pure .LE_ENH
    | s => throw s!"unknown ChildcareProviderTypeGroup: {s}"

instance : Lean.ToJson ChildcareProviderTypeGroup where
  toJson x := match x with
    | .DCC_SACC => Lean.Json.str "DCC_SACC"
    | .FDC_GFDC => Lean.Json.str "FDC_GFDC"
    | .LE_GC => Lean.Json.str "LE_GC"
    | .LE_STD => Lean.Json.str "LE_STD"
    | .LE_ENH => Lean.Json.str "LE_ENH"

/-- PolicyEngine's `decode_to_str` view. -/
def ChildcareProviderTypeGroup.asStr : ChildcareProviderTypeGroup → String
  | .DCC_SACC => "DCC_SACC"
  | .FDC_GFDC => "FDC_GFDC"
  | .LE_GC => "LE_GC"
  | .LE_STD => "LE_STD"
  | .LE_ENH => "LE_ENH"

inductive FamilyTierCategory where
  | INDIVIDUAL_AGE_RATED
  | ONE_ADULT
  | TWO_ADULTS
  | ONE_ADULT_AND_ONE_OR_MORE_CHILDREN
  | TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN
  | CHILD_ONLY
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson FamilyTierCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "INDIVIDUAL_AGE_RATED" => pure .INDIVIDUAL_AGE_RATED
    | "ONE_ADULT" => pure .ONE_ADULT
    | "TWO_ADULTS" => pure .TWO_ADULTS
    | "ONE_ADULT_AND_ONE_OR_MORE_CHILDREN" => pure .ONE_ADULT_AND_ONE_OR_MORE_CHILDREN
    | "TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN" => pure .TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN
    | "CHILD_ONLY" => pure .CHILD_ONLY
    | s => throw s!"unknown FamilyTierCategory: {s}"

instance : Lean.ToJson FamilyTierCategory where
  toJson x := match x with
    | .INDIVIDUAL_AGE_RATED => Lean.Json.str "INDIVIDUAL_AGE_RATED"
    | .ONE_ADULT => Lean.Json.str "ONE_ADULT"
    | .TWO_ADULTS => Lean.Json.str "TWO_ADULTS"
    | .ONE_ADULT_AND_ONE_OR_MORE_CHILDREN => Lean.Json.str "ONE_ADULT_AND_ONE_OR_MORE_CHILDREN"
    | .TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN => Lean.Json.str "TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN"
    | .CHILD_ONLY => Lean.Json.str "CHILD_ONLY"

/-- PolicyEngine's `decode_to_str` view. -/
def FamilyTierCategory.asStr : FamilyTierCategory → String
  | .INDIVIDUAL_AGE_RATED => "INDIVIDUAL_AGE_RATED"
  | .ONE_ADULT => "ONE_ADULT"
  | .TWO_ADULTS => "TWO_ADULTS"
  | .ONE_ADULT_AND_ONE_OR_MORE_CHILDREN => "ONE_ADULT_AND_ONE_OR_MORE_CHILDREN"
  | .TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN => "TWO_ADULTS_AND_ONE_OR_MORE_CHILDREN"
  | .CHILD_ONLY => "CHILD_ONLY"

inductive FilingStatus where
  | SINGLE
  | JOINT
  | SEPARATE
  | HEAD_OF_HOUSEHOLD
  | SURVIVING_SPOUSE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson FilingStatus where
  fromJson? j := do
    match (← j.getStr?) with
    | "SINGLE" => pure .SINGLE
    | "JOINT" => pure .JOINT
    | "SEPARATE" => pure .SEPARATE
    | "HEAD_OF_HOUSEHOLD" => pure .HEAD_OF_HOUSEHOLD
    | "SURVIVING_SPOUSE" => pure .SURVIVING_SPOUSE
    | s => throw s!"unknown FilingStatus: {s}"

instance : Lean.ToJson FilingStatus where
  toJson x := match x with
    | .SINGLE => Lean.Json.str "SINGLE"
    | .JOINT => Lean.Json.str "JOINT"
    | .SEPARATE => Lean.Json.str "SEPARATE"
    | .HEAD_OF_HOUSEHOLD => Lean.Json.str "HEAD_OF_HOUSEHOLD"
    | .SURVIVING_SPOUSE => Lean.Json.str "SURVIVING_SPOUSE"

/-- PolicyEngine's `decode_to_str` view. -/
def FilingStatus.asStr : FilingStatus → String
  | .SINGLE => "SINGLE"
  | .JOINT => "JOINT"
  | .SEPARATE => "SEPARATE"
  | .HEAD_OF_HOUSEHOLD => "HEAD_OF_HOUSEHOLD"
  | .SURVIVING_SPOUSE => "SURVIVING_SPOUSE"

inductive HUDIncomeLevel where
  | ABOVE_MODERATE
  | MODERATE
  | LOW
  | VERY_LOW
  | ESPECIALLY_LOW
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson HUDIncomeLevel where
  fromJson? j := do
    match (← j.getStr?) with
    | "ABOVE_MODERATE" => pure .ABOVE_MODERATE
    | "MODERATE" => pure .MODERATE
    | "LOW" => pure .LOW
    | "VERY_LOW" => pure .VERY_LOW
    | "ESPECIALLY_LOW" => pure .ESPECIALLY_LOW
    | s => throw s!"unknown HUDIncomeLevel: {s}"

instance : Lean.ToJson HUDIncomeLevel where
  toJson x := match x with
    | .ABOVE_MODERATE => Lean.Json.str "ABOVE_MODERATE"
    | .MODERATE => Lean.Json.str "MODERATE"
    | .LOW => Lean.Json.str "LOW"
    | .VERY_LOW => Lean.Json.str "VERY_LOW"
    | .ESPECIALLY_LOW => Lean.Json.str "ESPECIALLY_LOW"

/-- PolicyEngine's `decode_to_str` view. -/
def HUDIncomeLevel.asStr : HUDIncomeLevel → String
  | .ABOVE_MODERATE => "ABOVE_MODERATE"
  | .MODERATE => "MODERATE"
  | .LOW => "LOW"
  | .VERY_LOW => "VERY_LOW"
  | .ESPECIALLY_LOW => "ESPECIALLY_LOW"

inductive ImmigrationStatus where
  | CITIZEN
  | LEGAL_PERMANENT_RESIDENT
  | REFUGEE
  | ASYLEE
  | DEPORTATION_WITHHELD
  | CUBAN_HAITIAN_ENTRANT
  | CONDITIONAL_ENTRANT
  | PAROLED_ONE_YEAR
  | UNDOCUMENTED
  | DACA
  | TPS
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson ImmigrationStatus where
  fromJson? j := do
    match (← j.getStr?) with
    | "CITIZEN" => pure .CITIZEN
    | "LEGAL_PERMANENT_RESIDENT" => pure .LEGAL_PERMANENT_RESIDENT
    | "REFUGEE" => pure .REFUGEE
    | "ASYLEE" => pure .ASYLEE
    | "DEPORTATION_WITHHELD" => pure .DEPORTATION_WITHHELD
    | "CUBAN_HAITIAN_ENTRANT" => pure .CUBAN_HAITIAN_ENTRANT
    | "CONDITIONAL_ENTRANT" => pure .CONDITIONAL_ENTRANT
    | "PAROLED_ONE_YEAR" => pure .PAROLED_ONE_YEAR
    | "UNDOCUMENTED" => pure .UNDOCUMENTED
    | "DACA" => pure .DACA
    | "TPS" => pure .TPS
    | s => throw s!"unknown ImmigrationStatus: {s}"

instance : Lean.ToJson ImmigrationStatus where
  toJson x := match x with
    | .CITIZEN => Lean.Json.str "CITIZEN"
    | .LEGAL_PERMANENT_RESIDENT => Lean.Json.str "LEGAL_PERMANENT_RESIDENT"
    | .REFUGEE => Lean.Json.str "REFUGEE"
    | .ASYLEE => Lean.Json.str "ASYLEE"
    | .DEPORTATION_WITHHELD => Lean.Json.str "DEPORTATION_WITHHELD"
    | .CUBAN_HAITIAN_ENTRANT => Lean.Json.str "CUBAN_HAITIAN_ENTRANT"
    | .CONDITIONAL_ENTRANT => Lean.Json.str "CONDITIONAL_ENTRANT"
    | .PAROLED_ONE_YEAR => Lean.Json.str "PAROLED_ONE_YEAR"
    | .UNDOCUMENTED => Lean.Json.str "UNDOCUMENTED"
    | .DACA => Lean.Json.str "DACA"
    | .TPS => Lean.Json.str "TPS"

/-- PolicyEngine's `decode_to_str` view. -/
def ImmigrationStatus.asStr : ImmigrationStatus → String
  | .CITIZEN => "CITIZEN"
  | .LEGAL_PERMANENT_RESIDENT => "LEGAL_PERMANENT_RESIDENT"
  | .REFUGEE => "REFUGEE"
  | .ASYLEE => "ASYLEE"
  | .DEPORTATION_WITHHELD => "DEPORTATION_WITHHELD"
  | .CUBAN_HAITIAN_ENTRANT => "CUBAN_HAITIAN_ENTRANT"
  | .CONDITIONAL_ENTRANT => "CONDITIONAL_ENTRANT"
  | .PAROLED_ONE_YEAR => "PAROLED_ONE_YEAR"
  | .UNDOCUMENTED => "UNDOCUMENTED"
  | .DACA => "DACA"
  | .TPS => "TPS"

inductive MSPCategory where
  | NONE
  | QMB
  | SLMB
  | QI
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson MSPCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "NONE" => pure .NONE
    | "QMB" => pure .QMB
    | "SLMB" => pure .SLMB
    | "QI" => pure .QI
    | s => throw s!"unknown MSPCategory: {s}"

instance : Lean.ToJson MSPCategory where
  toJson x := match x with
    | .NONE => Lean.Json.str "NONE"
    | .QMB => Lean.Json.str "QMB"
    | .SLMB => Lean.Json.str "SLMB"
    | .QI => Lean.Json.str "QI"

/-- PolicyEngine's `decode_to_str` view. -/
def MSPCategory.asStr : MSPCategory → String
  | .NONE => "NONE"
  | .QMB => "QMB"
  | .SLMB => "SLMB"
  | .QI => "QI"

inductive MarketplaceCSRCategory where
  | NONE
  | AV_94
  | AV_87
  | AV_73
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson MarketplaceCSRCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "NONE" => pure .NONE
    | "AV_94" => pure .AV_94
    | "AV_87" => pure .AV_87
    | "AV_73" => pure .AV_73
    | s => throw s!"unknown MarketplaceCSRCategory: {s}"

instance : Lean.ToJson MarketplaceCSRCategory where
  toJson x := match x with
    | .NONE => Lean.Json.str "NONE"
    | .AV_94 => Lean.Json.str "AV_94"
    | .AV_87 => Lean.Json.str "AV_87"
    | .AV_73 => Lean.Json.str "AV_73"

/-- PolicyEngine's `decode_to_str` view. -/
def MarketplaceCSRCategory.asStr : MarketplaceCSRCategory → String
  | .NONE => "NONE"
  | .AV_94 => "AV_94"
  | .AV_87 => "AV_87"
  | .AV_73 => "AV_73"

inductive MarketplacePlanCategory where
  | BRONZE
  | SILVER
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson MarketplacePlanCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "BRONZE" => pure .BRONZE
    | "SILVER" => pure .SILVER
    | s => throw s!"unknown MarketplacePlanCategory: {s}"

instance : Lean.ToJson MarketplacePlanCategory where
  toJson x := match x with
    | .BRONZE => Lean.Json.str "BRONZE"
    | .SILVER => Lean.Json.str "SILVER"

/-- PolicyEngine's `decode_to_str` view. -/
def MarketplacePlanCategory.asStr : MarketplacePlanCategory → String
  | .BRONZE => "BRONZE"
  | .SILVER => "SILVER"

inductive MedicaidCategory where
  | INFANT
  | YOUNG_CHILD
  | OLDER_CHILD
  | YOUNG_ADULT
  | ADULT
  | PARENT
  | PREGNANT
  | SSI_RECIPIENT
  | SENIOR_OR_DISABLED
  | NONE
  | MEDICALLY_NEEDY
  | WORKING_DISABLED_BUY_IN
  | SECTION_1115_MEC_ADULT
  | HEALTHIER_MISSISSIPPI_WAIVER
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson MedicaidCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "INFANT" => pure .INFANT
    | "YOUNG_CHILD" => pure .YOUNG_CHILD
    | "OLDER_CHILD" => pure .OLDER_CHILD
    | "YOUNG_ADULT" => pure .YOUNG_ADULT
    | "ADULT" => pure .ADULT
    | "PARENT" => pure .PARENT
    | "PREGNANT" => pure .PREGNANT
    | "SSI_RECIPIENT" => pure .SSI_RECIPIENT
    | "SENIOR_OR_DISABLED" => pure .SENIOR_OR_DISABLED
    | "NONE" => pure .NONE
    | "MEDICALLY_NEEDY" => pure .MEDICALLY_NEEDY
    | "WORKING_DISABLED_BUY_IN" => pure .WORKING_DISABLED_BUY_IN
    | "SECTION_1115_MEC_ADULT" => pure .SECTION_1115_MEC_ADULT
    | "HEALTHIER_MISSISSIPPI_WAIVER" => pure .HEALTHIER_MISSISSIPPI_WAIVER
    | s => throw s!"unknown MedicaidCategory: {s}"

instance : Lean.ToJson MedicaidCategory where
  toJson x := match x with
    | .INFANT => Lean.Json.str "INFANT"
    | .YOUNG_CHILD => Lean.Json.str "YOUNG_CHILD"
    | .OLDER_CHILD => Lean.Json.str "OLDER_CHILD"
    | .YOUNG_ADULT => Lean.Json.str "YOUNG_ADULT"
    | .ADULT => Lean.Json.str "ADULT"
    | .PARENT => Lean.Json.str "PARENT"
    | .PREGNANT => Lean.Json.str "PREGNANT"
    | .SSI_RECIPIENT => Lean.Json.str "SSI_RECIPIENT"
    | .SENIOR_OR_DISABLED => Lean.Json.str "SENIOR_OR_DISABLED"
    | .NONE => Lean.Json.str "NONE"
    | .MEDICALLY_NEEDY => Lean.Json.str "MEDICALLY_NEEDY"
    | .WORKING_DISABLED_BUY_IN => Lean.Json.str "WORKING_DISABLED_BUY_IN"
    | .SECTION_1115_MEC_ADULT => Lean.Json.str "SECTION_1115_MEC_ADULT"
    | .HEALTHIER_MISSISSIPPI_WAIVER => Lean.Json.str "HEALTHIER_MISSISSIPPI_WAIVER"

/-- PolicyEngine's `decode_to_str` view. -/
def MedicaidCategory.asStr : MedicaidCategory → String
  | .INFANT => "INFANT"
  | .YOUNG_CHILD => "YOUNG_CHILD"
  | .OLDER_CHILD => "OLDER_CHILD"
  | .YOUNG_ADULT => "YOUNG_ADULT"
  | .ADULT => "ADULT"
  | .PARENT => "PARENT"
  | .PREGNANT => "PREGNANT"
  | .SSI_RECIPIENT => "SSI_RECIPIENT"
  | .SENIOR_OR_DISABLED => "SENIOR_OR_DISABLED"
  | .NONE => "NONE"
  | .MEDICALLY_NEEDY => "MEDICALLY_NEEDY"
  | .WORKING_DISABLED_BUY_IN => "WORKING_DISABLED_BUY_IN"
  | .SECTION_1115_MEC_ADULT => "SECTION_1115_MEC_ADULT"
  | .HEALTHIER_MISSISSIPPI_WAIVER => "HEALTHIER_MISSISSIPPI_WAIVER"

inductive MedicaidGroup where
  | CHILD
  | NON_EXPANSION_ADULT
  | EXPANSION_ADULT
  | AGED_DISABLED
  | NONE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson MedicaidGroup where
  fromJson? j := do
    match (← j.getStr?) with
    | "CHILD" => pure .CHILD
    | "NON_EXPANSION_ADULT" => pure .NON_EXPANSION_ADULT
    | "EXPANSION_ADULT" => pure .EXPANSION_ADULT
    | "AGED_DISABLED" => pure .AGED_DISABLED
    | "NONE" => pure .NONE
    | s => throw s!"unknown MedicaidGroup: {s}"

instance : Lean.ToJson MedicaidGroup where
  toJson x := match x with
    | .CHILD => Lean.Json.str "CHILD"
    | .NON_EXPANSION_ADULT => Lean.Json.str "NON_EXPANSION_ADULT"
    | .EXPANSION_ADULT => Lean.Json.str "EXPANSION_ADULT"
    | .AGED_DISABLED => Lean.Json.str "AGED_DISABLED"
    | .NONE => Lean.Json.str "NONE"

/-- PolicyEngine's `decode_to_str` view. -/
def MedicaidGroup.asStr : MedicaidGroup → String
  | .CHILD => "CHILD"
  | .NON_EXPANSION_ADULT => "NON_EXPANSION_ADULT"
  | .EXPANSION_ADULT => "EXPANSION_ADULT"
  | .AGED_DISABLED => "AGED_DISABLED"
  | .NONE => "NONE"

inductive NewElectricVehicleClassification where
  | VAN
  | SUV
  | PICKUP
  | OTHER
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson NewElectricVehicleClassification where
  fromJson? j := do
    match (← j.getStr?) with
    | "VAN" => pure .VAN
    | "SUV" => pure .SUV
    | "PICKUP" => pure .PICKUP
    | "OTHER" => pure .OTHER
    | s => throw s!"unknown NewElectricVehicleClassification: {s}"

instance : Lean.ToJson NewElectricVehicleClassification where
  toJson x := match x with
    | .VAN => Lean.Json.str "VAN"
    | .SUV => Lean.Json.str "SUV"
    | .PICKUP => Lean.Json.str "PICKUP"
    | .OTHER => Lean.Json.str "OTHER"

/-- PolicyEngine's `decode_to_str` view. -/
def NewElectricVehicleClassification.asStr : NewElectricVehicleClassification → String
  | .VAN => "VAN"
  | .SUV => "SUV"
  | .PICKUP => "PICKUP"
  | .OTHER => "OTHER"

inductive PellGrantEligibilityType where
  | MAXIMUM
  | MINIMUM
  | INELIGIBLE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson PellGrantEligibilityType where
  fromJson? j := do
    match (← j.getStr?) with
    | "MAXIMUM" => pure .MAXIMUM
    | "MINIMUM" => pure .MINIMUM
    | "INELIGIBLE" => pure .INELIGIBLE
    | s => throw s!"unknown PellGrantEligibilityType: {s}"

instance : Lean.ToJson PellGrantEligibilityType where
  toJson x := match x with
    | .MAXIMUM => Lean.Json.str "MAXIMUM"
    | .MINIMUM => Lean.Json.str "MINIMUM"
    | .INELIGIBLE => Lean.Json.str "INELIGIBLE"

/-- PolicyEngine's `decode_to_str` view. -/
def PellGrantEligibilityType.asStr : PellGrantEligibilityType → String
  | .MAXIMUM => "MAXIMUM"
  | .MINIMUM => "MINIMUM"
  | .INELIGIBLE => "INELIGIBLE"

inductive PellGrantFormula where
  | A
  | B
  | C
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson PellGrantFormula where
  fromJson? j := do
    match (← j.getStr?) with
    | "A" => pure .A
    | "B" => pure .B
    | "C" => pure .C
    | s => throw s!"unknown PellGrantFormula: {s}"

instance : Lean.ToJson PellGrantFormula where
  toJson x := match x with
    | .A => Lean.Json.str "A"
    | .B => Lean.Json.str "B"
    | .C => Lean.Json.str "C"

/-- PolicyEngine's `decode_to_str` view. -/
def PellGrantFormula.asStr : PellGrantFormula → String
  | .A => "A"
  | .B => "B"
  | .C => "C"

inductive PellGrantHouseholdType where
  | DEPENDENT_SINGLE
  | DEPENDENT_NOT_SINGLE
  | INDEPENDENT_SINGLE
  | INDEPENDENT_NOT_SINGLE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson PellGrantHouseholdType where
  fromJson? j := do
    match (← j.getStr?) with
    | "DEPENDENT_SINGLE" => pure .DEPENDENT_SINGLE
    | "DEPENDENT_NOT_SINGLE" => pure .DEPENDENT_NOT_SINGLE
    | "INDEPENDENT_SINGLE" => pure .INDEPENDENT_SINGLE
    | "INDEPENDENT_NOT_SINGLE" => pure .INDEPENDENT_NOT_SINGLE
    | s => throw s!"unknown PellGrantHouseholdType: {s}"

instance : Lean.ToJson PellGrantHouseholdType where
  toJson x := match x with
    | .DEPENDENT_SINGLE => Lean.Json.str "DEPENDENT_SINGLE"
    | .DEPENDENT_NOT_SINGLE => Lean.Json.str "DEPENDENT_NOT_SINGLE"
    | .INDEPENDENT_SINGLE => Lean.Json.str "INDEPENDENT_SINGLE"
    | .INDEPENDENT_NOT_SINGLE => Lean.Json.str "INDEPENDENT_NOT_SINGLE"

/-- PolicyEngine's `decode_to_str` view. -/
def PellGrantHouseholdType.asStr : PellGrantHouseholdType → String
  | .DEPENDENT_SINGLE => "DEPENDENT_SINGLE"
  | .DEPENDENT_NOT_SINGLE => "DEPENDENT_NOT_SINGLE"
  | .INDEPENDENT_SINGLE => "INDEPENDENT_SINGLE"
  | .INDEPENDENT_NOT_SINGLE => "INDEPENDENT_NOT_SINGLE"

inductive Race where
  | WHITE
  | BLACK
  | HISPANIC
  | OTHER
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson Race where
  fromJson? j := do
    match (← j.getStr?) with
    | "WHITE" => pure .WHITE
    | "BLACK" => pure .BLACK
    | "HISPANIC" => pure .HISPANIC
    | "OTHER" => pure .OTHER
    | s => throw s!"unknown Race: {s}"

instance : Lean.ToJson Race where
  toJson x := match x with
    | .WHITE => Lean.Json.str "WHITE"
    | .BLACK => Lean.Json.str "BLACK"
    | .HISPANIC => Lean.Json.str "HISPANIC"
    | .OTHER => Lean.Json.str "OTHER"

/-- PolicyEngine's `decode_to_str` view. -/
def Race.asStr : Race → String
  | .WHITE => "WHITE"
  | .BLACK => "BLACK"
  | .HISPANIC => "HISPANIC"
  | .OTHER => "OTHER"

inductive SPMUnitTenureType where
  | OWNER_WITH_MORTGAGE
  | OWNER_WITHOUT_MORTGAGE
  | RENTER
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson SPMUnitTenureType where
  fromJson? j := do
    match (← j.getStr?) with
    | "OWNER_WITH_MORTGAGE" => pure .OWNER_WITH_MORTGAGE
    | "OWNER_WITHOUT_MORTGAGE" => pure .OWNER_WITHOUT_MORTGAGE
    | "RENTER" => pure .RENTER
    | s => throw s!"unknown SPMUnitTenureType: {s}"

instance : Lean.ToJson SPMUnitTenureType where
  toJson x := match x with
    | .OWNER_WITH_MORTGAGE => Lean.Json.str "OWNER_WITH_MORTGAGE"
    | .OWNER_WITHOUT_MORTGAGE => Lean.Json.str "OWNER_WITHOUT_MORTGAGE"
    | .RENTER => Lean.Json.str "RENTER"

/-- PolicyEngine's `decode_to_str` view. -/
def SPMUnitTenureType.asStr : SPMUnitTenureType → String
  | .OWNER_WITH_MORTGAGE => "OWNER_WITH_MORTGAGE"
  | .OWNER_WITHOUT_MORTGAGE => "OWNER_WITHOUT_MORTGAGE"
  | .RENTER => "RENTER"

inductive SSICategory where
  | AGED
  | BLIND
  | DISABLED
  | NONE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson SSICategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "AGED" => pure .AGED
    | "BLIND" => pure .BLIND
    | "DISABLED" => pure .DISABLED
    | "NONE" => pure .NONE
    | s => throw s!"unknown SSICategory: {s}"

instance : Lean.ToJson SSICategory where
  toJson x := match x with
    | .AGED => Lean.Json.str "AGED"
    | .BLIND => Lean.Json.str "BLIND"
    | .DISABLED => Lean.Json.str "DISABLED"
    | .NONE => Lean.Json.str "NONE"

/-- PolicyEngine's `decode_to_str` view. -/
def SSICategory.asStr : SSICategory → String
  | .AGED => "AGED"
  | .BLIND => "BLIND"
  | .DISABLED => "DISABLED"
  | .NONE => "NONE"

inductive SSIFederalLivingArrangement where
  | OWN_HOUSEHOLD
  | ANOTHER_PERSONS_HOUSEHOLD
  | CHILD_IN_PARENTAL_HOUSEHOLD
  | MEDICAL_TREATMENT_FACILITY
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson SSIFederalLivingArrangement where
  fromJson? j := do
    match (← j.getStr?) with
    | "OWN_HOUSEHOLD" => pure .OWN_HOUSEHOLD
    | "ANOTHER_PERSONS_HOUSEHOLD" => pure .ANOTHER_PERSONS_HOUSEHOLD
    | "CHILD_IN_PARENTAL_HOUSEHOLD" => pure .CHILD_IN_PARENTAL_HOUSEHOLD
    | "MEDICAL_TREATMENT_FACILITY" => pure .MEDICAL_TREATMENT_FACILITY
    | s => throw s!"unknown SSIFederalLivingArrangement: {s}"

instance : Lean.ToJson SSIFederalLivingArrangement where
  toJson x := match x with
    | .OWN_HOUSEHOLD => Lean.Json.str "OWN_HOUSEHOLD"
    | .ANOTHER_PERSONS_HOUSEHOLD => Lean.Json.str "ANOTHER_PERSONS_HOUSEHOLD"
    | .CHILD_IN_PARENTAL_HOUSEHOLD => Lean.Json.str "CHILD_IN_PARENTAL_HOUSEHOLD"
    | .MEDICAL_TREATMENT_FACILITY => Lean.Json.str "MEDICAL_TREATMENT_FACILITY"

/-- PolicyEngine's `decode_to_str` view. -/
def SSIFederalLivingArrangement.asStr : SSIFederalLivingArrangement → String
  | .OWN_HOUSEHOLD => "OWN_HOUSEHOLD"
  | .ANOTHER_PERSONS_HOUSEHOLD => "ANOTHER_PERSONS_HOUSEHOLD"
  | .CHILD_IN_PARENTAL_HOUSEHOLD => "CHILD_IN_PARENTAL_HOUSEHOLD"
  | .MEDICAL_TREATMENT_FACILITY => "MEDICAL_TREATMENT_FACILITY"

inductive SSNCardType where
  | CITIZEN
  | NON_CITIZEN_VALID_EAD
  | OTHER_NON_CITIZEN
  | NONE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson SSNCardType where
  fromJson? j := do
    match (← j.getStr?) with
    | "CITIZEN" => pure .CITIZEN
    | "NON_CITIZEN_VALID_EAD" => pure .NON_CITIZEN_VALID_EAD
    | "OTHER_NON_CITIZEN" => pure .OTHER_NON_CITIZEN
    | "NONE" => pure .NONE
    | s => throw s!"unknown SSNCardType: {s}"

instance : Lean.ToJson SSNCardType where
  toJson x := match x with
    | .CITIZEN => Lean.Json.str "CITIZEN"
    | .NON_CITIZEN_VALID_EAD => Lean.Json.str "NON_CITIZEN_VALID_EAD"
    | .OTHER_NON_CITIZEN => Lean.Json.str "OTHER_NON_CITIZEN"
    | .NONE => Lean.Json.str "NONE"

/-- PolicyEngine's `decode_to_str` view. -/
def SSNCardType.asStr : SSNCardType → String
  | .CITIZEN => "CITIZEN"
  | .NON_CITIZEN_VALID_EAD => "NON_CITIZEN_VALID_EAD"
  | .OTHER_NON_CITIZEN => "OTHER_NON_CITIZEN"
  | .NONE => "NONE"

inductive SchoolMealTier where
  | FREE
  | REDUCED
  | PAID
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson SchoolMealTier where
  fromJson? j := do
    match (← j.getStr?) with
    | "FREE" => pure .FREE
    | "REDUCED" => pure .REDUCED
    | "PAID" => pure .PAID
    | s => throw s!"unknown SchoolMealTier: {s}"

instance : Lean.ToJson SchoolMealTier where
  toJson x := match x with
    | .FREE => Lean.Json.str "FREE"
    | .REDUCED => Lean.Json.str "REDUCED"
    | .PAID => Lean.Json.str "PAID"

/-- PolicyEngine's `decode_to_str` view. -/
def SchoolMealTier.asStr : SchoolMealTier → String
  | .FREE => "FREE"
  | .REDUCED => "REDUCED"
  | .PAID => "PAID"

inductive StateCode where
  | AL
  | AK
  | AZ
  | AR
  | CA
  | CO
  | CT
  | DE
  | FL
  | GA
  | HI
  | ID
  | IL
  | IN
  | IA
  | KS
  | KY
  | LA
  | ME
  | MD
  | MA
  | MI
  | MN
  | MS
  | MO
  | MT
  | NE
  | NV
  | NH
  | NJ
  | NM
  | NY
  | NC
  | ND
  | OH
  | OK
  | OR
  | PA
  | RI
  | SC
  | SD
  | TN
  | TX
  | UT
  | VT
  | VA
  | WA
  | WV
  | WI
  | WY
  | DC
  | GU
  | MP
  | PW
  | PR
  | VI
  | AA
  | AE
  | AP
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson StateCode where
  fromJson? j := do
    match (← j.getStr?) with
    | "AL" => pure .AL
    | "AK" => pure .AK
    | "AZ" => pure .AZ
    | "AR" => pure .AR
    | "CA" => pure .CA
    | "CO" => pure .CO
    | "CT" => pure .CT
    | "DE" => pure .DE
    | "FL" => pure .FL
    | "GA" => pure .GA
    | "HI" => pure .HI
    | "ID" => pure .ID
    | "IL" => pure .IL
    | "IN" => pure .IN
    | "IA" => pure .IA
    | "KS" => pure .KS
    | "KY" => pure .KY
    | "LA" => pure .LA
    | "ME" => pure .ME
    | "MD" => pure .MD
    | "MA" => pure .MA
    | "MI" => pure .MI
    | "MN" => pure .MN
    | "MS" => pure .MS
    | "MO" => pure .MO
    | "MT" => pure .MT
    | "NE" => pure .NE
    | "NV" => pure .NV
    | "NH" => pure .NH
    | "NJ" => pure .NJ
    | "NM" => pure .NM
    | "NY" => pure .NY
    | "NC" => pure .NC
    | "ND" => pure .ND
    | "OH" => pure .OH
    | "OK" => pure .OK
    | "OR" => pure .OR
    | "PA" => pure .PA
    | "RI" => pure .RI
    | "SC" => pure .SC
    | "SD" => pure .SD
    | "TN" => pure .TN
    | "TX" => pure .TX
    | "UT" => pure .UT
    | "VT" => pure .VT
    | "VA" => pure .VA
    | "WA" => pure .WA
    | "WV" => pure .WV
    | "WI" => pure .WI
    | "WY" => pure .WY
    | "DC" => pure .DC
    | "GU" => pure .GU
    | "MP" => pure .MP
    | "PW" => pure .PW
    | "PR" => pure .PR
    | "VI" => pure .VI
    | "AA" => pure .AA
    | "AE" => pure .AE
    | "AP" => pure .AP
    | s => throw s!"unknown StateCode: {s}"

instance : Lean.ToJson StateCode where
  toJson x := match x with
    | .AL => Lean.Json.str "AL"
    | .AK => Lean.Json.str "AK"
    | .AZ => Lean.Json.str "AZ"
    | .AR => Lean.Json.str "AR"
    | .CA => Lean.Json.str "CA"
    | .CO => Lean.Json.str "CO"
    | .CT => Lean.Json.str "CT"
    | .DE => Lean.Json.str "DE"
    | .FL => Lean.Json.str "FL"
    | .GA => Lean.Json.str "GA"
    | .HI => Lean.Json.str "HI"
    | .ID => Lean.Json.str "ID"
    | .IL => Lean.Json.str "IL"
    | .IN => Lean.Json.str "IN"
    | .IA => Lean.Json.str "IA"
    | .KS => Lean.Json.str "KS"
    | .KY => Lean.Json.str "KY"
    | .LA => Lean.Json.str "LA"
    | .ME => Lean.Json.str "ME"
    | .MD => Lean.Json.str "MD"
    | .MA => Lean.Json.str "MA"
    | .MI => Lean.Json.str "MI"
    | .MN => Lean.Json.str "MN"
    | .MS => Lean.Json.str "MS"
    | .MO => Lean.Json.str "MO"
    | .MT => Lean.Json.str "MT"
    | .NE => Lean.Json.str "NE"
    | .NV => Lean.Json.str "NV"
    | .NH => Lean.Json.str "NH"
    | .NJ => Lean.Json.str "NJ"
    | .NM => Lean.Json.str "NM"
    | .NY => Lean.Json.str "NY"
    | .NC => Lean.Json.str "NC"
    | .ND => Lean.Json.str "ND"
    | .OH => Lean.Json.str "OH"
    | .OK => Lean.Json.str "OK"
    | .OR => Lean.Json.str "OR"
    | .PA => Lean.Json.str "PA"
    | .RI => Lean.Json.str "RI"
    | .SC => Lean.Json.str "SC"
    | .SD => Lean.Json.str "SD"
    | .TN => Lean.Json.str "TN"
    | .TX => Lean.Json.str "TX"
    | .UT => Lean.Json.str "UT"
    | .VT => Lean.Json.str "VT"
    | .VA => Lean.Json.str "VA"
    | .WA => Lean.Json.str "WA"
    | .WV => Lean.Json.str "WV"
    | .WI => Lean.Json.str "WI"
    | .WY => Lean.Json.str "WY"
    | .DC => Lean.Json.str "DC"
    | .GU => Lean.Json.str "GU"
    | .MP => Lean.Json.str "MP"
    | .PW => Lean.Json.str "PW"
    | .PR => Lean.Json.str "PR"
    | .VI => Lean.Json.str "VI"
    | .AA => Lean.Json.str "AA"
    | .AE => Lean.Json.str "AE"
    | .AP => Lean.Json.str "AP"

/-- PolicyEngine's `decode_to_str` view. -/
def StateCode.asStr : StateCode → String
  | .AL => "AL"
  | .AK => "AK"
  | .AZ => "AZ"
  | .AR => "AR"
  | .CA => "CA"
  | .CO => "CO"
  | .CT => "CT"
  | .DE => "DE"
  | .FL => "FL"
  | .GA => "GA"
  | .HI => "HI"
  | .ID => "ID"
  | .IL => "IL"
  | .IN => "IN"
  | .IA => "IA"
  | .KS => "KS"
  | .KY => "KY"
  | .LA => "LA"
  | .ME => "ME"
  | .MD => "MD"
  | .MA => "MA"
  | .MI => "MI"
  | .MN => "MN"
  | .MS => "MS"
  | .MO => "MO"
  | .MT => "MT"
  | .NE => "NE"
  | .NV => "NV"
  | .NH => "NH"
  | .NJ => "NJ"
  | .NM => "NM"
  | .NY => "NY"
  | .NC => "NC"
  | .ND => "ND"
  | .OH => "OH"
  | .OK => "OK"
  | .OR => "OR"
  | .PA => "PA"
  | .RI => "RI"
  | .SC => "SC"
  | .SD => "SD"
  | .TN => "TN"
  | .TX => "TX"
  | .UT => "UT"
  | .VT => "VT"
  | .VA => "VA"
  | .WA => "WA"
  | .WV => "WV"
  | .WI => "WI"
  | .WY => "WY"
  | .DC => "DC"
  | .GU => "GU"
  | .MP => "MP"
  | .PW => "PW"
  | .PR => "PR"
  | .VI => "VI"
  | .AA => "AA"
  | .AE => "AE"
  | .AP => "AP"

inductive WICCategory where
  | PREGNANT
  | POSTPARTUM
  | BREASTFEEDING
  | INFANT
  | CHILD
  | NONE
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson WICCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "PREGNANT" => pure .PREGNANT
    | "POSTPARTUM" => pure .POSTPARTUM
    | "BREASTFEEDING" => pure .BREASTFEEDING
    | "INFANT" => pure .INFANT
    | "CHILD" => pure .CHILD
    | "NONE" => pure .NONE
    | s => throw s!"unknown WICCategory: {s}"

instance : Lean.ToJson WICCategory where
  toJson x := match x with
    | .PREGNANT => Lean.Json.str "PREGNANT"
    | .POSTPARTUM => Lean.Json.str "POSTPARTUM"
    | .BREASTFEEDING => Lean.Json.str "BREASTFEEDING"
    | .INFANT => Lean.Json.str "INFANT"
    | .CHILD => Lean.Json.str "CHILD"
    | .NONE => Lean.Json.str "NONE"

/-- PolicyEngine's `decode_to_str` view. -/
def WICCategory.asStr : WICCategory → String
  | .PREGNANT => "PREGNANT"
  | .POSTPARTUM => "POSTPARTUM"
  | .BREASTFEEDING => "BREASTFEEDING"
  | .INFANT => "INFANT"
  | .CHILD => "CHILD"
  | .NONE => "NONE"

inductive WICFoodPackage where
  | NONE
  | PREGNANT_SINGLETON
  | PREGNANT_MULTIPLE_FETUSES
  | PARTIALLY_BREASTFEEDING
  | POSTPARTUM_NON_BREASTFEEDING
  | FULLY_BREASTFEEDING
  | FULLY_BREASTFEEDING_MULTIPLES
  | INFANT_AVERAGE
  | INFANT_0_3_FULLY_FORMULA_FED
  | INFANT_4_5_FULLY_FORMULA_FED
  | INFANT_0_3_PARTIALLY_BREASTFED
  | INFANT_4_5_PARTIALLY_BREASTFED
  | INFANT_6_11_PARTIALLY_BREASTFED
  | INFANT_0_5_FULLY_BREASTFED
  | INFANT_6_11_FULLY_FORMULA_FED
  | INFANT_6_11_FULLY_BREASTFED
  | CHILD_12_23_MONTHS
  | CHILD_24_59_MONTHS
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson WICFoodPackage where
  fromJson? j := do
    match (← j.getStr?) with
    | "NONE" => pure .NONE
    | "PREGNANT_SINGLETON" => pure .PREGNANT_SINGLETON
    | "PREGNANT_MULTIPLE_FETUSES" => pure .PREGNANT_MULTIPLE_FETUSES
    | "PARTIALLY_BREASTFEEDING" => pure .PARTIALLY_BREASTFEEDING
    | "POSTPARTUM_NON_BREASTFEEDING" => pure .POSTPARTUM_NON_BREASTFEEDING
    | "FULLY_BREASTFEEDING" => pure .FULLY_BREASTFEEDING
    | "FULLY_BREASTFEEDING_MULTIPLES" => pure .FULLY_BREASTFEEDING_MULTIPLES
    | "INFANT_AVERAGE" => pure .INFANT_AVERAGE
    | "INFANT_0_3_FULLY_FORMULA_FED" => pure .INFANT_0_3_FULLY_FORMULA_FED
    | "INFANT_4_5_FULLY_FORMULA_FED" => pure .INFANT_4_5_FULLY_FORMULA_FED
    | "INFANT_0_3_PARTIALLY_BREASTFED" => pure .INFANT_0_3_PARTIALLY_BREASTFED
    | "INFANT_4_5_PARTIALLY_BREASTFED" => pure .INFANT_4_5_PARTIALLY_BREASTFED
    | "INFANT_6_11_PARTIALLY_BREASTFED" => pure .INFANT_6_11_PARTIALLY_BREASTFED
    | "INFANT_0_5_FULLY_BREASTFED" => pure .INFANT_0_5_FULLY_BREASTFED
    | "INFANT_6_11_FULLY_FORMULA_FED" => pure .INFANT_6_11_FULLY_FORMULA_FED
    | "INFANT_6_11_FULLY_BREASTFED" => pure .INFANT_6_11_FULLY_BREASTFED
    | "CHILD_12_23_MONTHS" => pure .CHILD_12_23_MONTHS
    | "CHILD_24_59_MONTHS" => pure .CHILD_24_59_MONTHS
    | s => throw s!"unknown WICFoodPackage: {s}"

instance : Lean.ToJson WICFoodPackage where
  toJson x := match x with
    | .NONE => Lean.Json.str "NONE"
    | .PREGNANT_SINGLETON => Lean.Json.str "PREGNANT_SINGLETON"
    | .PREGNANT_MULTIPLE_FETUSES => Lean.Json.str "PREGNANT_MULTIPLE_FETUSES"
    | .PARTIALLY_BREASTFEEDING => Lean.Json.str "PARTIALLY_BREASTFEEDING"
    | .POSTPARTUM_NON_BREASTFEEDING => Lean.Json.str "POSTPARTUM_NON_BREASTFEEDING"
    | .FULLY_BREASTFEEDING => Lean.Json.str "FULLY_BREASTFEEDING"
    | .FULLY_BREASTFEEDING_MULTIPLES => Lean.Json.str "FULLY_BREASTFEEDING_MULTIPLES"
    | .INFANT_AVERAGE => Lean.Json.str "INFANT_AVERAGE"
    | .INFANT_0_3_FULLY_FORMULA_FED => Lean.Json.str "INFANT_0_3_FULLY_FORMULA_FED"
    | .INFANT_4_5_FULLY_FORMULA_FED => Lean.Json.str "INFANT_4_5_FULLY_FORMULA_FED"
    | .INFANT_0_3_PARTIALLY_BREASTFED => Lean.Json.str "INFANT_0_3_PARTIALLY_BREASTFED"
    | .INFANT_4_5_PARTIALLY_BREASTFED => Lean.Json.str "INFANT_4_5_PARTIALLY_BREASTFED"
    | .INFANT_6_11_PARTIALLY_BREASTFED => Lean.Json.str "INFANT_6_11_PARTIALLY_BREASTFED"
    | .INFANT_0_5_FULLY_BREASTFED => Lean.Json.str "INFANT_0_5_FULLY_BREASTFED"
    | .INFANT_6_11_FULLY_FORMULA_FED => Lean.Json.str "INFANT_6_11_FULLY_FORMULA_FED"
    | .INFANT_6_11_FULLY_BREASTFED => Lean.Json.str "INFANT_6_11_FULLY_BREASTFED"
    | .CHILD_12_23_MONTHS => Lean.Json.str "CHILD_12_23_MONTHS"
    | .CHILD_24_59_MONTHS => Lean.Json.str "CHILD_24_59_MONTHS"

/-- PolicyEngine's `decode_to_str` view. -/
def WICFoodPackage.asStr : WICFoodPackage → String
  | .NONE => "NONE"
  | .PREGNANT_SINGLETON => "PREGNANT_SINGLETON"
  | .PREGNANT_MULTIPLE_FETUSES => "PREGNANT_MULTIPLE_FETUSES"
  | .PARTIALLY_BREASTFEEDING => "PARTIALLY_BREASTFEEDING"
  | .POSTPARTUM_NON_BREASTFEEDING => "POSTPARTUM_NON_BREASTFEEDING"
  | .FULLY_BREASTFEEDING => "FULLY_BREASTFEEDING"
  | .FULLY_BREASTFEEDING_MULTIPLES => "FULLY_BREASTFEEDING_MULTIPLES"
  | .INFANT_AVERAGE => "INFANT_AVERAGE"
  | .INFANT_0_3_FULLY_FORMULA_FED => "INFANT_0_3_FULLY_FORMULA_FED"
  | .INFANT_4_5_FULLY_FORMULA_FED => "INFANT_4_5_FULLY_FORMULA_FED"
  | .INFANT_0_3_PARTIALLY_BREASTFED => "INFANT_0_3_PARTIALLY_BREASTFED"
  | .INFANT_4_5_PARTIALLY_BREASTFED => "INFANT_4_5_PARTIALLY_BREASTFED"
  | .INFANT_6_11_PARTIALLY_BREASTFED => "INFANT_6_11_PARTIALLY_BREASTFED"
  | .INFANT_0_5_FULLY_BREASTFED => "INFANT_0_5_FULLY_BREASTFED"
  | .INFANT_6_11_FULLY_FORMULA_FED => "INFANT_6_11_FULLY_FORMULA_FED"
  | .INFANT_6_11_FULLY_BREASTFED => "INFANT_6_11_FULLY_BREASTFED"
  | .CHILD_12_23_MONTHS => "CHILD_12_23_MONTHS"
  | .CHILD_24_59_MONTHS => "CHILD_24_59_MONTHS"

inductive WICInfantFeedingCategory where
  | AVERAGE
  | FULLY_FORMULA_FED
  | PARTIALLY_BREASTFED
  | FULLY_BREASTFED
deriving Repr, DecidableEq, BEq

instance : Lean.FromJson WICInfantFeedingCategory where
  fromJson? j := do
    match (← j.getStr?) with
    | "AVERAGE" => pure .AVERAGE
    | "FULLY_FORMULA_FED" => pure .FULLY_FORMULA_FED
    | "PARTIALLY_BREASTFED" => pure .PARTIALLY_BREASTFED
    | "FULLY_BREASTFED" => pure .FULLY_BREASTFED
    | s => throw s!"unknown WICInfantFeedingCategory: {s}"

instance : Lean.ToJson WICInfantFeedingCategory where
  toJson x := match x with
    | .AVERAGE => Lean.Json.str "AVERAGE"
    | .FULLY_FORMULA_FED => Lean.Json.str "FULLY_FORMULA_FED"
    | .PARTIALLY_BREASTFED => Lean.Json.str "PARTIALLY_BREASTFED"
    | .FULLY_BREASTFED => Lean.Json.str "FULLY_BREASTFED"

/-- PolicyEngine's `decode_to_str` view. -/
def WICInfantFeedingCategory.asStr : WICInfantFeedingCategory → String
  | .AVERAGE => "AVERAGE"
  | .FULLY_FORMULA_FED => "FULLY_FORMULA_FED"
  | .PARTIALLY_BREASTFED => "PARTIALLY_BREASTFED"
  | .FULLY_BREASTFED => "FULLY_BREASTFED"

end Lawlib
