import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

/-!
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/

namespace Lawlib.Parameters
open Lawlib

/-- The total utility expense subsidies.
    `household/expense/utilities/subsidies.yaml` (policyengine-us). -/
def household.expense.utilities.subsidies : DatedParam (List String) :=
  ⟨(⟨0, 1, 1⟩, ["ca_care", "ca_fera", "ca_la_ez_save"]), []⟩

end Lawlib.Parameters
