/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Lexington-Fayette Urban County Government (Fayette County), Kentucky levies an occupational license fee on earnings at this rate.
    `gov/local/ky/fayette/tax/income/occupational/rate.yaml` (policyengine-us).
    * LFUCG Division of Revenue — occupational license fee rates (2.25%): https://www.lexingtonky.gov/working/business-licensing-taxes/occupational-license-fee-rates-current-forms -/
def gov.local.ky.fayette.tax.income.occupational.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 9 400), []⟩

/-- Louisville Metro (Jefferson County), Kentucky levies an occupational license fee on earnings at this rate.
    `gov/local/ky/jefferson/tax/income/occupational/rate.yaml` (policyengine-us).
    * Louisville Metro Revenue Commission Form W-1KJC instructions — occupational license fee rates: https://louisvilleky.gov/sites/default/files/2024-12/w-1kjc_instructions_2025.pdf -/
def gov.local.ky.jefferson.tax.income.occupational.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 11 500), []⟩

end Lawlib.Gen.Params
