/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Maryland sets the following county income tax rates for head of household filers in Anne Arundel County.
    `gov/local/md/anne_arundel_county/tax/income/head_of_household.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.anne_arundel_county.tax.income.head_of_household : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2023, 1, 1⟩, .fin (mkRat 27 1000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000), (⟨2024, 1, 1⟩, .fin 75000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2025, 1, 1⟩, .fin (mkRat 147 5000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 480000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for married filers filing jointly in Anne Arundel County.
    `gov/local/md/anne_arundel_county/tax/income/joint.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.anne_arundel_county.tax.income.joint : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2023, 1, 1⟩, .fin (mkRat 27 1000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000), (⟨2024, 1, 1⟩, .fin 75000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2025, 1, 1⟩, .fin (mkRat 147 5000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 480000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for married filers filing separately in Anne Arundel County.
    `gov/local/md/anne_arundel_county/tax/income/separate.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.anne_arundel_county.tax.income.separate : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2023, 1, 1⟩, .fin (mkRat 27 1000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2025, 1, 1⟩, .fin (mkRat 147 5000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 400000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for single filers in Anne Arundel County.
    `gov/local/md/anne_arundel_county/tax/income/single.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.anne_arundel_county.tax.income.single : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2023, 1, 1⟩, .fin (mkRat 27 1000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2025, 1, 1⟩, .fin (mkRat 147 5000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 400000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for qualified surviving spouse filers in Anne Arundel County.
    `gov/local/md/anne_arundel_county/tax/income/surviving_spouse.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.anne_arundel_county.tax.income.surviving_spouse : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2023, 1, 1⟩, .fin (mkRat 27 1000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000), (⟨2024, 1, 1⟩, .fin 75000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 281 10000)), [(⟨2025, 1, 1⟩, .fin (mkRat 147 5000))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 480000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland county local income tax rates by county.
    `gov/local/md/flat_rate.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.flat_rate.ALLEGANY_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 61 2000), [(⟨2023, 1, 1⟩, mkRat 303 10000)]⟩
def gov.local.md.flat_rate.ANNE_ARUNDEL_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 0), []⟩
def gov.local.md.flat_rate.BALTIMORE_CITY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.BALTIMORE_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.CALVERT_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 100), [(⟨2025, 1, 1⟩, mkRat 4 125)]⟩
def gov.local.md.flat_rate.CAROLINE_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.CARROLL_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 303 10000), []⟩
def gov.local.md.flat_rate.CECIL_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 100), [(⟨2023, 1, 1⟩, mkRat 7 250), (⟨2024, 1, 1⟩, mkRat 11 400), (⟨2025, 1, 1⟩, mkRat 137 5000)]⟩
def gov.local.md.flat_rate.CHARLES_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 303 10000), []⟩
def gov.local.md.flat_rate.DORCHESTER_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), [(⟨2025, 1, 1⟩, mkRat 33 1000)]⟩
def gov.local.md.flat_rate.FREDERICK_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 0), []⟩
def gov.local.md.flat_rate.GARRETT_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 53 2000), []⟩
def gov.local.md.flat_rate.HARFORD_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 153 5000), []⟩
def gov.local.md.flat_rate.HOWARD_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.KENT_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.MONTGOMERY_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.PRINCE_GEORGE_S_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.QUEEN_ANNE_S_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.SOMERSET_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.ST_MARY_S_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 317 10000), [(⟨2022, 1, 1⟩, mkRat 31 1000), (⟨2023, 1, 1⟩, mkRat 3 100), (⟨2025, 1, 1⟩, mkRat 4 125)]⟩
def gov.local.md.flat_rate.TALBOT_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 125), []⟩
def gov.local.md.flat_rate.WASHINGTON_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), [(⟨2022, 1, 1⟩, mkRat 3 100), (⟨2023, 1, 1⟩, mkRat 59 2000)]⟩
def gov.local.md.flat_rate.WICOMICO_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 4 125), []⟩
def gov.local.md.flat_rate.WORCESTER_COUNTY_MD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, mkRat 9 400), []⟩

/-- Maryland sets the following county income tax rates for head of household filers in Frederick County.
    `gov/local/md/frederick_county/tax/income/head_of_household.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.frederick_county.tax.income.head_of_household : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2023, 1, 1⟩, .fin (mkRat 11 400)), (⟨2024, 1, 1⟩, .fin (mkRat 9 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 100000), (⟨2024, 1, 1⟩, .fin 25000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2024, 1, 1⟩, .fin (mkRat 11 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 100000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 37 1250)), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 250000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for married filers filing jointly in Frederick County.
    `gov/local/md/frederick_county/tax/income/joint.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.frederick_county.tax.income.joint : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2023, 1, 1⟩, .fin (mkRat 11 400)), (⟨2024, 1, 1⟩, .fin (mkRat 9 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 100000), (⟨2024, 1, 1⟩, .fin 25000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2024, 1, 1⟩, .fin (mkRat 11 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 100000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 37 1250)), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 250000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for married filers filing separately in Frederick County.
    `gov/local/md/frederick_county/tax/income/separate.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.frederick_county.tax.income.separate : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2023, 1, 1⟩, .fin (mkRat 11 400)), (⟨2024, 1, 1⟩, .fin (mkRat 9 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000), (⟨2024, 1, 1⟩, .fin 25000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2024, 1, 1⟩, .fin (mkRat 11 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 50000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 37 1250)), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 150000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for single filers in Frederick County.
    `gov/local/md/frederick_county/tax/income/single.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.frederick_county.tax.income.single : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2023, 1, 1⟩, .fin (mkRat 11 400)), (⟨2024, 1, 1⟩, .fin (mkRat 9 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 50000), (⟨2024, 1, 1⟩, .fin 25000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2024, 1, 1⟩, .fin (mkRat 11 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 50000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 37 1250)), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 150000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Maryland sets the following county income tax rates for qualified surviving spouse filers in Frederick County.
    `gov/local/md/frederick_county/tax/income/surviving_spouse.yaml` (policyengine-us).
    * Maryland 2025 Resident Tax Forms and Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2025/resident-booklet.pdf#page=25
    * Maryland Local Income Tax Rates: https://services.marylandcomptroller.gov/taxes/en/maryland-income-tax-rates-and-brackets
    * 2022 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2022/Resident_Booklet.pdf#page=22
    * 2023 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2023/Resident_Booklet.pdf#page=23
    * 2024 Maryland Income Tax Instructions - Local Tax Rate Chart: https://www.marylandcomptroller.gov/content/dam/mdcomp/tax/instructions/2024/Resident_Booklet.pdf#page=25 -/
def gov.local.md.frederick_county.tax.income.surviving_spouse : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .fin 0), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2023, 1, 1⟩, .fin (mkRat 11 400)), (⟨2024, 1, 1⟩, .fin (mkRat 9 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2023, 1, 1⟩, .fin 100000), (⟨2024, 1, 1⟩, .fin 25000)]⟩, ⟨(⟨2023, 1, 1⟩, .fin (mkRat 37 1250)), [(⟨2024, 1, 1⟩, .fin (mkRat 11 400))]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 100000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 37 1250)), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .posInf), [(⟨2024, 1, 1⟩, .fin 250000)]⟩, ⟨(⟨2024, 1, 1⟩, .fin (mkRat 4 125)), []⟩⟩]⟩

/-- Montgomery County matches this percentage of the refundable Maryland Earned Income Tax Credit.
    `gov/local/md/montgomery_county/tax/income/credits/eitc/refundable/match.yaml` (policyengine-us).
    * 2023 Montgomery County Earned Income Credit EIC Refund: https://www3.montgomerycountymd.gov/311/Solutions.aspx?SolutionId=1-4DAM0I
    * COUNTY COUNCIL FOR MONTGOMERY COUNTY, MARYLAND - Resolution 20-184: https://apps.montgomerycountymd.gov/ccllims/DownloadFilePage?FileName=11869_1_25039_Resolution_20-184_Adopted_20230525.pdf#page=28
    * 2020 - 2022 Expedited Finance Working Families Income Bill 14-21 Supplement Amendments: https://www.montgomerycountymd.gov/OLO/Resources/Files/eis/2021/EIS-EBill14-21.pdf
    * 2015 - 2016 Montgomery County Sec. 20-81. Administration; Regulations Sec. 20-79. Amount of Supplement (a), (b): https://codelibrary.amlegal.com/codes/montgomerycounty/latest/montgomeryco_md/0-0-0-129735 -/
def gov.local.md.montgomery_county.tax.income.credits.eitc.refundable.match : DatedParam Rate :=
  ⟨(⟨2015, 1, 1⟩, mkRat 9 10), [(⟨2016, 1, 1⟩, mkRat 19 20), (⟨2020, 1, 1⟩, 1), (⟨2023, 7, 1⟩, mkRat 14 25)]⟩

end Lawlib.Gen.Params
