/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Nebraska provides this amount as the monthly standard of need for individuals in alternate living arrangements under the Aid to the Aged, Blind, or Disabled program.
    `gov/states/ne/dhhs/aabd/alternate_living_standard.yaml` (policyengine-us).
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2021-01-01): https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2017-01-01, Manual Letter: https://web.archive.org/web/20161221055507/https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2015-01-01, Manual Letter: https://web.archive.org/web/20150907223322/https://dhhs.ne.gov/Documents/469-000-211.pdf
    * SSA State Assistance Programs for SSI Recipients, January 2011 - Nebraska, Table 1: https://www.ssa.gov/policy/docs/progdesc/ssi_st_asst/2011/ne.pdf#page=2 -/
def gov.states.ne.dhhs.aabd.alternate_living_standard.ADULT_FAMILY_HOME : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 865), [(⟨2017, 1, 1⟩, 867), (⟨2021, 1, 1⟩, 926)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.ASSISTED_LIVING_FACILITY : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1175), [(⟨2017, 1, 1⟩, 1177), (⟨2021, 1, 1⟩, 1236)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.ASSISTED_LIVING_WAIVER : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 733), [(⟨2017, 1, 1⟩, 735), (⟨2021, 1, 1⟩, 794)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.BOARD_AND_ROOM : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 737), [(⟨2017, 1, 1⟩, 739), (⟨2021, 1, 1⟩, 798)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.GROUP_HOME_CHILDREN : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 801), [(⟨2017, 1, 1⟩, 803), (⟨2021, 1, 1⟩, 862)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.INDEPENDENT : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 0), []⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.LONG_TERM_CARE : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 50), [(⟨2017, 1, 1⟩, 60)]⟩
def gov.states.ne.dhhs.aabd.alternate_living_standard.NONE : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 0), []⟩

/-- Nebraska provides this amount as the monthly maximum shelter allowance for multi-person households living independently under the Aid to the Aged, Blind, or Disabled program.
    `gov/states/ne/dhhs/aabd/shelter_allowance/multiple.yaml` (policyengine-us).
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2021-01-01): https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2015-01-01, Manual Letter: https://web.archive.org/web/20150907223322/https://dhhs.ne.gov/Documents/469-000-211.pdf -/
def gov.states.ne.dhhs.aabd.shelter_allowance.multiple : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 349), []⟩

/-- Nebraska provides this amount as the monthly maximum shelter allowance for one-person households living independently under the Aid to the Aged, Blind, or Disabled program.
    `gov/states/ne/dhhs/aabd/shelter_allowance/single.yaml` (policyengine-us).
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2021-01-01): https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2015-01-01, Manual Letter: https://web.archive.org/web/20150907223322/https://dhhs.ne.gov/Documents/469-000-211.pdf -/
def gov.states.ne.dhhs.aabd.shelter_allowance.single : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 281), []⟩

/-- Nebraska provides this amount as the monthly standard of need for households living independently, by household size, under the Aid to the Aged, Blind, or Disabled program.
    `gov/states/ne/dhhs/aabd/standard_of_need/independent.yaml` (policyengine-us).
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2021-01-01): https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2017-01-01, Manual Letter: https://web.archive.org/web/20161221055507/https://dhhs.ne.gov/Documents/469-000-211.pdf
    * 469 NAC 469-000-211 AABD or SDP Standard of Need (effective 2015-01-01, Manual Letter: https://web.archive.org/web/20150907223322/https://dhhs.ne.gov/Documents/469-000-211.pdf
    * SSA State Assistance Programs for SSI Recipients, January 2011 - Nebraska: https://www.ssa.gov/policy/docs/progdesc/ssi_st_asst/2011/ne.pdf#page=2 -/
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«1» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 491), [(⟨2017, 1, 1⟩, 505), (⟨2021, 1, 1⟩, 564)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«2» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 778), [(⟨2017, 1, 1⟩, 799), (⟨2021, 1, 1⟩, 887)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«3» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 964), [(⟨2017, 1, 1⟩, 989), (⟨2021, 1, 1⟩, 1109)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«4» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1155), [(⟨2017, 1, 1⟩, 1186), (⟨2021, 1, 1⟩, 1336)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«5» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1346), [(⟨2017, 1, 1⟩, 1383), (⟨2021, 1, 1⟩, 1563)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«6» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1537), [(⟨2017, 1, 1⟩, 1580), (⟨2021, 1, 1⟩, 1790)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«7» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1728), [(⟨2017, 1, 1⟩, 1777), (⟨2021, 1, 1⟩, 2017)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«8» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 1919), [(⟨2017, 1, 1⟩, 1974), (⟨2021, 1, 1⟩, 2244)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«9» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 2110), [(⟨2017, 1, 1⟩, 2171), (⟨2021, 1, 1⟩, 2471)]⟩
def gov.states.ne.dhhs.aabd.standard_of_need.independent.«10» : DatedParam USD :=
  ⟨(⟨2015, 1, 1⟩, 2301), [(⟨2017, 1, 1⟩, 2368), (⟨2021, 1, 1⟩, 2698)]⟩

/-- Nebraska provides this share of the standard of need as the payment standard under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/benefit/payment_standard_rate.yaml` (policyengine-us).
    * Neb. Rev. Stat. 43-512(3): https://nebraskalegislature.gov/laws/statutes.php?statute=43-512 -/
def gov.states.ne.dhhs.adc.benefit.payment_standard_rate : DatedParam Rate :=
  ⟨(⟨2015, 9, 1⟩, mkRat 11 20), []⟩

/-- Nebraska adds this amount to the standard of need for each person beyond unit size 10 under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/benefit/standard_of_need/additional_person.yaml` (policyengine-us).
    * Neb. Rev. Stat. 43-513(1): https://nebraskalegislature.gov/laws/statutes.php?statute=43-513
    * ACF-202 TANF Caseload Reduction Report (2017, 2019 SON values): https://dhhs.ne.gov/Documents/Nebraska-State-TANF-Plan-2025.pdf#page=3
    * 468-000-209 (2021): https://dhhs.ne.gov/Documents/468-000-209.pdf
    * Nebraska Legislature 2024 TANF Report (2023): https://nebraskalegislature.gov/pdf/reports/fiscal/2024_tanf_report.pdf#page=4
    * Title 468 NAC Chapter 3 (2025): https://dhhs.ne.gov/Guidance%20Docs/Title%20468%20-%20Aid%20to%20Dependent%20Children.pdf#page=9 -/
def gov.states.ne.dhhs.adc.benefit.standard_of_need.additional_person : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 126), [(⟨2017, 7, 1⟩, 130), (⟨2019, 7, 1⟩, 135), (⟨2021, 7, 1⟩, 140), (⟨2023, 7, 1⟩, 160), (⟨2025, 7, 1⟩, 170)]⟩

/-- Nebraska sets this amount as the standard of need under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/benefit/standard_of_need/amount.yaml` (policyengine-us).
    * Neb. Rev. Stat. 43-513(1): https://nebraskalegislature.gov/laws/statutes.php?statute=43-513
    * ACF-202 TANF Caseload Reduction Report (2017, 2019 SON values): https://dhhs.ne.gov/Documents/Nebraska-State-TANF-Plan-2025.pdf#page=3
    * 468-000-209 (2021): https://dhhs.ne.gov/Documents/468-000-209.pdf
    * Nebraska Legislature 2024 TANF Report (2023): https://nebraskalegislature.gov/pdf/reports/fiscal/2024_tanf_report.pdf#page=4
    * Title 468 NAC Chapter 3 (2025): https://dhhs.ne.gov/Guidance%20Docs/Title%20468%20-%20Aid%20to%20Dependent%20Children.pdf#page=9 -/
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«1» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 541), [(⟨2017, 7, 1⟩, 556), (⟨2019, 7, 1⟩, 579), (⟨2021, 7, 1⟩, 601), (⟨2023, 7, 1⟩, 683), (⟨2025, 7, 1⟩, 727)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«2» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 667), [(⟨2017, 7, 1⟩, 686), (⟨2019, 7, 1⟩, 714), (⟨2021, 7, 1⟩, 741), (⟨2023, 7, 1⟩, 843), (⟨2025, 7, 1⟩, 897)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«3» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 793), [(⟨2017, 7, 1⟩, 816), (⟨2019, 7, 1⟩, 849), (⟨2021, 7, 1⟩, 881), (⟨2023, 7, 1⟩, 1003), (⟨2025, 7, 1⟩, 1067)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«4» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 919), [(⟨2017, 7, 1⟩, 946), (⟨2019, 7, 1⟩, 984), (⟨2021, 7, 1⟩, 1021), (⟨2023, 7, 1⟩, 1163), (⟨2025, 7, 1⟩, 1237)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«5» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1045), [(⟨2017, 7, 1⟩, 1076), (⟨2019, 7, 1⟩, 1119), (⟨2021, 7, 1⟩, 1161), (⟨2023, 7, 1⟩, 1323), (⟨2025, 7, 1⟩, 1407)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«6» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1171), [(⟨2017, 7, 1⟩, 1206), (⟨2019, 7, 1⟩, 1254), (⟨2021, 7, 1⟩, 1301), (⟨2023, 7, 1⟩, 1483), (⟨2025, 7, 1⟩, 1577)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«7» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1297), [(⟨2017, 7, 1⟩, 1336), (⟨2019, 7, 1⟩, 1389), (⟨2021, 7, 1⟩, 1441), (⟨2023, 7, 1⟩, 1643), (⟨2025, 7, 1⟩, 1747)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«8» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1423), [(⟨2017, 7, 1⟩, 1466), (⟨2019, 7, 1⟩, 1524), (⟨2021, 7, 1⟩, 1581), (⟨2023, 7, 1⟩, 1803), (⟨2025, 7, 1⟩, 1917)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«9» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1549), [(⟨2017, 7, 1⟩, 1596), (⟨2019, 7, 1⟩, 1659), (⟨2021, 7, 1⟩, 1721), (⟨2023, 7, 1⟩, 1963), (⟨2025, 7, 1⟩, 2087)]⟩
def gov.states.ne.dhhs.adc.benefit.standard_of_need.amount.«10» : DatedParam USD :=
  ⟨(⟨2015, 7, 1⟩, 1675), [(⟨2017, 7, 1⟩, 1726), (⟨2019, 7, 1⟩, 1794), (⟨2021, 7, 1⟩, 1861), (⟨2023, 7, 1⟩, 2123), (⟨2025, 7, 1⟩, 2257)]⟩

/-- Nebraska excludes this share of earnings from countable income for initial applicants under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/income/earned_income_disregard/initial.yaml` (policyengine-us).
    * Neb. Rev. Stat. 68-1726(3)(a)(i): https://nebraskalegislature.gov/laws/statutes.php?statute=68-1726 -/
def gov.states.ne.dhhs.adc.income.earned_income_disregard.initial : DatedParam Rate :=
  ⟨(⟨2015, 9, 1⟩, mkRat 1 5), []⟩

/-- Nebraska excludes this share of earnings from countable income for ongoing recipients under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/income/earned_income_disregard/ongoing.yaml` (policyengine-us).
    * Neb. Rev. Stat. 68-1726(3)(a)(ii): https://nebraskalegislature.gov/laws/statutes.php?statute=68-1726 -/
def gov.states.ne.dhhs.adc.income.earned_income_disregard.ongoing : DatedParam Rate :=
  ⟨(⟨2015, 9, 1⟩, mkRat 1 2), []⟩

/-- Nebraska sets this as the maximum unit size for benefit calculations under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/max_unit_size.yaml` (policyengine-us).
    * Title 468 NAC Chapter 3 (2025): https://dhhs.ne.gov/Guidance%20Docs/Title%20468%20-%20Aid%20to%20Dependent%20Children.pdf#page=9 -/
def gov.states.ne.dhhs.adc.max_unit_size : DatedParam Rate :=
  ⟨(⟨2015, 7, 1⟩, 10), []⟩

/-- Nebraska limits countable resources to this amount under the Aid to Dependent Children program.
    `gov/states/ne/dhhs/adc/resources/limit.yaml` (policyengine-us).
    * Neb. Rev. Stat. 68-1726(1): https://nebraskalegislature.gov/laws/statutes.php?statute=68-1726 -/
def gov.states.ne.dhhs.adc.resources.limit : Scale :=
  ⟨[⟨⟨(⟨2015, 7, 1⟩, 1), []⟩, ⟨(⟨2015, 7, 1⟩, 4000), []⟩⟩,
    ⟨⟨(⟨2015, 7, 1⟩, 2), []⟩, ⟨(⟨2015, 7, 1⟩, 6000), []⟩⟩]⟩

/-- Nebraska limits the child care subsidy to children of this age or younger, not requiring special needs care.
    `gov/states/ne/dhhs/child_care_subsidy/age_threshold/base.yaml` (policyengine-us).
    * Nebraska DHHS, Child Care Subsidy Information For Parents: https://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Parents.aspx -/
def gov.states.ne.dhhs.child_care_subsidy.age_threshold.base : DatedParam Rat :=
  ⟨(⟨2021, 8, 28⟩, 12), []⟩

/-- Nebraska limits the child care subsidy to children of this age or younger, requiring special needs care.
    `gov/states/ne/dhhs/child_care_subsidy/age_threshold/special_needs.yaml` (policyengine-us).
    * Nebraska DHHS, Child Care Subsidy Information For Parents: https://dhhs.ne.gov/Pages/Child-Care-Subsidy-Information-for-Parents.aspx -/
def gov.states.ne.dhhs.child_care_subsidy.age_threshold.special_needs : DatedParam Rat :=
  ⟨(⟨2021, 8, 28⟩, 18), []⟩

/-- Nebraska provides a fee-free child care subsidy to families with a income at or below this fraction of the federal poverty guidelines.
    `gov/states/ne/dhhs/child_care_subsidy/fpg_fraction/fee_free_limit.yaml` (policyengine-us).
    * Nebraska DHHS, Department of Health and Human Services, LB 485 FAQ: https://dhhs.ne.gov/Child%20Care%20Documents/LB%20485%20FAQ.pdf#page=4 -/
def gov.states.ne.dhhs.child_care_subsidy.fpg_fraction.fee_free_limit : DatedParam Rate :=
  ⟨(⟨2021, 8, 28⟩, 1), []⟩

/-- Nebraska limits the child care subsidy to families with income at or below this fraction of the federal poverty guidelines for initial eligibility.
    `gov/states/ne/dhhs/child_care_subsidy/fpg_fraction/initial_eligibility.yaml` (policyengine-us).
    * Nebraska Revised Statute | Chapter 68 | §1206 (2)(a): https://nebraskalegislature.gov/laws/statutes.php?statute=68-1206
    * Nebraska DHHS, Child Care For Parents, Increased income eligibility guidelines for child care subsidy: https://dhhs.ne.gov/Pages/Child-Care-Parents.aspx -/
def gov.states.ne.dhhs.child_care_subsidy.fpg_fraction.initial_eligibility : DatedParam Rate :=
  ⟨(⟨2021, 8, 28⟩, mkRat 13 10), [(⟨2023, 1, 1⟩, mkRat 37 20), (⟨2026, 10, 1⟩, mkRat 13 10)]⟩

/-- Nebraska counts these income sources as earned income under the Child Care Subsidy program.
    `gov/states/ne/dhhs/child_care_subsidy/income/sources/earned.yaml` (policyengine-us).
    * 392 NAC 3-005.02(3), (27)-(28): https://dhhs.ne.gov/Documents/Title-392-Complete.pdf#page=13
    * Nebraska DHHS Title 392 Guidance Document, 392 NAC 2-010.01(A): https://dhhs.ne.gov/Guidance%20Docs/Title%20392%20-%20Child%20Care%20Subsidy.pdf#page=3 -/
def gov.states.ne.dhhs.child_care_subsidy.income.sources.earned : DatedParam (List String) :=
  ⟨(⟨2011, 6, 28⟩, ["employment_income", "self_employment_income", "sstb_self_employment_income", "farm_operations_income"]), []⟩

/-- Nebraska counts these income sources as unearned income under the Child Care Subsidy program.
    `gov/states/ne/dhhs/child_care_subsidy/income/sources/unearned.yaml` (policyengine-us).
    * 392 NAC 3-005.02(1), (7)-(9), (12), (16)-(19), (23)-(25): https://dhhs.ne.gov/Documents/Title-392-Complete.pdf#page=13
    * Nebraska DHHS Title 392 Guidance Document, 392 NAC 2-010.01(A): https://dhhs.ne.gov/Guidance%20Docs/Title%20392%20-%20Child%20Care%20Subsidy.pdf#page=3 -/
def gov.states.ne.dhhs.child_care_subsidy.income.sources.unearned : DatedParam (List String) :=
  ⟨(⟨2011, 6, 28⟩, ["ssi", "social_security", "dividend_income", "interest_income", "rental_income", "pension_income", "veterans_benefits", "strike_benefits", "unemployment_compensation", "workers_compensation", "child_support_received", "alimony_income"]), []⟩

/-- Nebraska excludes the earnings of in-school children at or below this age from countable income under the Child Care Subsidy program.
    `gov/states/ne/dhhs/child_care_subsidy/income/student_earner_age_threshold.yaml` (policyengine-us).
    * 392 NAC 3-005.03(17): https://dhhs.ne.gov/Documents/Title-392-Complete.pdf#page=16 -/
def gov.states.ne.dhhs.child_care_subsidy.income.student_earner_age_threshold : DatedParam Rat :=
  ⟨(⟨2009, 3, 10⟩, 18), []⟩

/-- Nebraska sets the child care family fee to this share of household gross income under the Child Care Subsidy program.
    `gov/states/ne/dhhs/child_care_subsidy/rate.yaml` (policyengine-us).
    * Nebraska DHHS, Department of Health and Human Services, LB 485 FAQ: https://dhhs.ne.gov/Child%20Care%20Documents/LB%20485%20FAQ.pdf#page=4
    * Nebraska DHHS Title 392 Guidance Document, 392 NAC 2-011: https://dhhs.ne.gov/Guidance%20Docs/Title%20392%20-%20Child%20Care%20Subsidy.pdf#page=4 -/
def gov.states.ne.dhhs.child_care_subsidy.rate : DatedParam Rate :=
  ⟨(⟨2021, 8, 28⟩, mkRat 7 100), []⟩

/-- Nebraska limits the military retirement benefits to filers this age or older.
    `gov/states/ne/tax/income/agi/subtractions/military_retirement/age_threshold.yaml` (policyengine-us).
    * 2021 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/f_1040n_booklet.pdf#page=16
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_8.pdf#page=3
    * 2023 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=19
    * 2024 Nebraska Individual Income Tax Booklet, Line 29: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=21
    * 2025 Nebraska Individual Income Tax Booklet, Line 32: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=26
    * Nebraska Revised Statute 77-2716 (15)(a): https://nebraskalegislature.gov/laws/statutes.php?statute=77-2716 -/
def gov.states.ne.tax.income.agi.subtractions.military_retirement.age_threshold : DatedParam Rat :=
  ⟨(⟨2015, 1, 1⟩, 67), [(⟨2022, 1, 1⟩, 0)]⟩

/-- Nebraska subtracts this fraction of military retirement benefits from federal adjusted gross income.
    `gov/states/ne/tax/income/agi/subtractions/military_retirement/fraction.yaml` (policyengine-us).
    * 2021 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/f_1040n_booklet.pdf#page=16
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_8.pdf#page=3
    * 2023 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=19
    * 2024 Nebraska Individual Income Tax Booklet, Line 29: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=21
    * 2025 Nebraska Individual Income Tax Booklet, Line 32: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=26
    * Nebraska Revised Statute 77-2716(15): https://nebraskalegislature.gov/laws/statutes.php?statute=77-2716 -/
def gov.states.ne.tax.income.agi.subtractions.military_retirement.fraction : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 2 5), [(⟨2022, 1, 1⟩, 1)]⟩

/-- Nebraska caps the subtraction for 529 education savings plan contributions at this amount.
    `gov/states/ne/tax/income/agi/subtractions/plan_529_contributions/cap.yaml` (policyengine-us).
    * Nebraska Revised Statute § 77-2716(20): https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2716
    * 2025 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=26 -/
def gov.states.ne.tax.income.agi.subtractions.plan_529_contributions.cap.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 10000), []⟩
def gov.states.ne.tax.income.agi.subtractions.plan_529_contributions.cap.JOINT : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 10000), []⟩
def gov.states.ne.tax.income.agi.subtractions.plan_529_contributions.cap.SEPARATE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 5000), []⟩
def gov.states.ne.tax.income.agi.subtractions.plan_529_contributions.cap.SINGLE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 10000), []⟩
def gov.states.ne.tax.income.agi.subtractions.plan_529_contributions.cap.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 10000), []⟩

/-- Fraction of taxable social security allowed as NE AGI subtraction when federal AGI is above threshold (fraction is 1.0 for others).
    `gov/states/ne/tax/income/agi/subtractions/social_security/fraction.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * Nebraska Revised Statute | chapter 77 | §2716 | 14 (a): https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2716
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=19
    * 2023 Nebraska Legislative Changes, Social Security Benefits: https://revenue.nebraska.gov/about/2023-nebraska-legislative-changes
    * 2024 Nebraska Individual Income Tax Booklet, Line 28: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=20
    * 2025 Nebraska Individual Income Tax Booklet, Line 31: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=26
    * Section 77-2716(14) (a) (iv): https://www.nebraskalegislature.gov/FloorDocs/108/PDF/Slip/LB754.pdf#page=9 -/
def gov.states.ne.tax.income.agi.subtractions.social_security.fraction : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 20), [(⟨2022, 1, 1⟩, mkRat 2 5), (⟨2023, 1, 1⟩, mkRat 3 5), (⟨2024, 1, 1⟩, 1)]⟩

/-- `gov/states/ne/tax/income/agi/subtractions/social_security/threshold.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.agi.subtractions.social_security.threshold.JOINT : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .fin 59960), [(⟨2022, 1, 1⟩, .fin 61760), (⟨2023, 1, 1⟩, .fin 66510), (⟨2024, 1, 1⟩, .posInf)]⟩

/-- `gov/states/ne/tax/income/agi/subtractions/social_security/threshold.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.agi.subtractions.social_security.threshold.HEAD_OF_HOUSEHOLD : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .fin 44460), [(⟨2022, 1, 1⟩, .fin 45790), (⟨2023, 1, 1⟩, .fin 49310), (⟨2024, 1, 1⟩, .posInf)]⟩

/-- `gov/states/ne/tax/income/agi/subtractions/social_security/threshold.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.agi.subtractions.social_security.threshold.SURVIVING_SPOUSE : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .fin 44460), [(⟨2022, 1, 1⟩, .fin 45790), (⟨2023, 1, 1⟩, .fin 49310), (⟨2024, 1, 1⟩, .posInf)]⟩

/-- `gov/states/ne/tax/income/agi/subtractions/social_security/threshold.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.agi.subtractions.social_security.threshold.SINGLE : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .fin 44460), [(⟨2022, 1, 1⟩, .fin 45790), (⟨2023, 1, 1⟩, .fin 49310), (⟨2024, 1, 1⟩, .posInf)]⟩

/-- `gov/states/ne/tax/income/agi/subtractions/social_security/threshold.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.agi.subtractions.social_security.threshold.SEPARATE : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .fin 44460), [(⟨2022, 1, 1⟩, .fin 45790), (⟨2023, 1, 1⟩, .fin 49310), (⟨2024, 1, 1⟩, .posInf)]⟩

/-- Nebraska subtracts these sources from adjusted gross income.
    `gov/states/ne/tax/income/agi/subtractions/subtractions.yaml` (policyengine-us).
    * Nebraska Revised Statute | chapter 77 | §2716: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2716
    * 2025 Nebraska Individual Income Tax Booklet, Schedule I: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=26 -/
def gov.states.ne.tax.income.agi.subtractions.subtractions : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["ne_social_security_subtraction", "ne_military_retirement_subtraction", "us_govt_interest", "ne_529_deduction"]), [(⟨2024, 1, 1⟩, ["ne_social_security_subtraction", "taxable_public_pension_income", "ne_military_retirement_subtraction", "us_govt_interest", "ne_529_deduction"])]⟩

/-- Nebraska matches this fraction of the federal child and dependent care credit as a non-refundable credit.
    `gov/states/ne/tax/income/credits/cdcc/nonrefundable/fraction.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.03 | 002.05M: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=10
    * 2024 Nebraska Individual Income Tax Booklet, Line 23: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=11
    * 2025 Nebraska Individual Income Tax Booklet, Line 23: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=15 -/
def gov.states.ne.tax.income.credits.cdcc.nonrefundable.fraction : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 4), []⟩

/-- Nebraska provides the child and dependent care credit as a refundable credit to filers with federal adjusted gross income of this amount or less.
    `gov/states/ne/tax/income/credits/cdcc/refundable/income_limit.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.03: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_2441N_2023_Final.pdf#page=1
    * 2024 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_2441N.pdf#page=1
    * 2025 Nebraska Individual Income Tax Booklet, Line 42: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=18 -/
def gov.states.ne.tax.income.credits.cdcc.refundable.income_limit : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 29000), []⟩

/-- Nebraska matches this fraction of the federal child and dependent care credit as a refundable credit.
    `gov/states/ne/tax/income/credits/cdcc/refundable/match.yaml` (policyengine-us).
    * 2021 NE Form 2441N: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_2441n.pdf
    * 2022 NE Form 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/Form_2441N_Ne_Child_and_Dependent_Care_Expenses_8-618-2022_final_2.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.11: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_2441N_2023_Final.pdf#page=1
    * 2024 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_2441N.pdf#page=2
    * 2025 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_2441N.pdf#page=1 -/
def gov.states.ne.tax.income.credits.cdcc.refundable.match : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, 1), []⟩

/-- Nebraska reduces the refundable child and dependent tax credit match percentage by this amount for each increment of federal adjusted gross income exceeding the threshold.
    `gov/states/ne/tax/income/credits/cdcc/refundable/reduction/amount.yaml` (policyengine-us).
    * 2021 NE Form 2441N: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_2441n.pdf
    * 2022 NE Form 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/Form_2441N_Ne_Child_and_Dependent_Care_Expenses_8-618-2022_final_2.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.11: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_2441N_2023_Final.pdf#page=1
    * 2024 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_2441N.pdf#page=1
    * 2025 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_2441N.pdf#page=1 -/
def gov.states.ne.tax.income.credits.cdcc.refundable.reduction.amount : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 10), []⟩

/-- Nebraska reduces the refundable child and dependent tax credit match percentage for each of these increments of federal adjusted gross income exceeding the threshold.
    `gov/states/ne/tax/income/credits/cdcc/refundable/reduction/increment.yaml` (policyengine-us).
    * 2021 NE Form 2441N: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_2441n.pdf
    * 2022 NE Form 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/Form_2441N_Ne_Child_and_Dependent_Care_Expenses_8-618-2022_final_2.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.11: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_2441N_2023_Final.pdf#page=1
    * 2024 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_2441N.pdf#page=1
    * 2025 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_2441N.pdf#page=1 -/
def gov.states.ne.tax.income.credits.cdcc.refundable.reduction.increment : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 1000), []⟩

/-- Nebraska reduces the refundable child and dependent tax credit match percentage for filers with federal adjusted gross income above this amount.
    `gov/states/ne/tax/income/credits/cdcc/refundable/reduction/start.yaml` (policyengine-us).
    * 2021 NE Form 2441N: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_2441n.pdf
    * 2022 NE Form 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/Form_2441N_Ne_Child_and_Dependent_Care_Expenses_8-618-2022_final_2.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.11: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_2441N_2023_Final.pdf#page=1
    * 2024 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_2441N.pdf#page=1
    * 2025 Nebraska FORM 2441N: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_2441N.pdf#page=1 -/
def gov.states.ne.tax.income.credits.cdcc.refundable.reduction.start : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 22000), []⟩

/-- Nebraska limits the refundable child tax credit to children this age or younger.
    `gov/states/ne/tax/income/credits/ctc/refundable/age_threshold.yaml` (policyengine-us).
    * Nebraska Revised Statute | Chapter 77 | §7202 (1): https://nebraskalegislature.gov/laws/statutes.php?statute=77-7202
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=2
    * 2025 Nebraska Individual Income Tax Booklet, Line 48: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=19 -/
def gov.states.ne.tax.income.credits.ctc.refundable.age_threshold : DatedParam Rat :=
  ⟨(⟨2024, 1, 1⟩, 5), []⟩

/-- Nebraska provides this refundable child credit amount for each qualifying dependent, based on adjusted gross income.
    `gov/states/ne/tax/income/credits/ctc/refundable/amount.yaml` (policyengine-us).
    * Nebraska Revised Statute | Chapter 77 | §7203 (2): https://nebraskalegislature.gov/laws/statutes.php?statute=77-7203
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=2
    * 2025 Nebraska Individual Income Tax Booklet, Line 48: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=19 -/
def gov.states.ne.tax.income.credits.ctc.refundable.amount : Scale :=
  ⟨[⟨⟨(⟨2024, 1, 1⟩, 0), []⟩, ⟨(⟨2024, 1, 1⟩, 2000), []⟩⟩,
    ⟨⟨(⟨2024, 1, 1⟩, 75000), []⟩, ⟨(⟨2024, 1, 1⟩, 1000), []⟩⟩,
    ⟨⟨(⟨2024, 1, 1⟩, 150000), []⟩, ⟨(⟨2024, 1, 1⟩, 0), []⟩⟩]⟩

/-- Nebraska limits the refundable child tax credit to filers with an total household income at or below this fraction of the federal poverty guideline.
    `gov/states/ne/tax/income/credits/ctc/refundable/fpg_fraction.yaml` (policyengine-us).
    * Nebraska Revised Statute | Chapter 77 | §7203 (1)(c): https://nebraskalegislature.gov/laws/statutes.php?statute=77-7203
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=2
    * 2025 Nebraska Individual Income Tax Booklet, Line 48: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=19 -/
def gov.states.ne.tax.income.credits.ctc.refundable.fpg_fraction : DatedParam Rate :=
  ⟨(⟨2024, 1, 1⟩, 1), []⟩

/-- Nebraska matches this fraction of the federal earned income tax credit.
    `gov/states/ne/tax/income/credits/eitc/fraction.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.21 | 002.05M: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=12
    * 2024 Nebraska Individual Income Tax Booklet, Line 42: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=14
    * 2025 Nebraska Individual Income Tax Booklet, Line 44: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=18 -/
def gov.states.ne.tax.income.credits.eitc.fraction : DatedParam Rate :=
  ⟨(⟨2006, 1, 1⟩, mkRat 2 25), [(⟨2007, 1, 1⟩, mkRat 1 10)]⟩

/-- Nebraska provides the following nonrefundable credits.
    `gov/states/ne/tax/income/credits/nonrefundable.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.01: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 316 Nebraska Administrative Code | Chapter 22 | §019.04: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 316 Nebraska Administrative Code | Chapter 22 | §019.03: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=10
    * 2024 Nebraska Individual Income Tax Booklet, Line 32: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=12
    * 2025 Nebraska Individual Income Tax Booklet, Line 34: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=17 -/
def gov.states.ne.tax.income.credits.nonrefundable : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["ne_exemptions", "ne_elderly_disabled_credit", "ne_cdcc_nonrefundable"]), []⟩

/-- Nebraska limits the net adjusted gross income adjustments to this amount.
    `gov/states/ne/tax/income/credits/nonrefundable_adjust_limit.yaml` (policyengine-us).
    * 2021 NE income tax form and instructions, Federal Tax Liability Worksheet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instructions, Federal Tax Liability Worksheet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §003.01: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=6
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=7
    * 2025 Nebraska Individual Income Tax Booklet, Line 35: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=17 -/
def gov.states.ne.tax.income.credits.nonrefundable_adjust_limit : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 5000), []⟩

/-- Nebraska provides the following refundable credits.
    `gov/states/ne/tax/income/credits/refundable.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 316 Nebraska Administrative Code | Chapter 22 | §019.11: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 316 Nebraska Administrative Code | Chapter 22 | §019.21: https://revenue.nebraska.gov/about/legal-information/regulations/chapter-22-individual-income-tax
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=12
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=14
    * 2025 Nebraska Individual Income Tax Booklet, Lines 41-49: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=18
    * Nebraska Revised Statute | Chapter 77 | §7203: https://nebraskalegislature.gov/laws/statutes.php?statute=77-7203 -/
def gov.states.ne.tax.income.credits.refundable : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["ne_cdcc_refundable", "ne_eitc"]), [(⟨2022, 1, 1⟩, ["ne_cdcc_refundable", "ne_eitc", "ne_stillborn_credit"]), (⟨2024, 1, 1⟩, ["ne_cdcc_refundable", "ne_eitc", "ne_stillborn_credit", "ne_refundable_ctc", "ne_school_readiness_credit"])]⟩

/-- Nebraska provides the following refundable School Readiness credit amounts, based on the Nebraska Early Childhood Professional (ECP) Record System level.
    `gov/states/ne/tax/income/credits/school_readiness/amount/refundable.yaml` (policyengine-us).
    * Nebraska Revised Statute 77-3605: https://nebraskalegislature.gov/laws/statutes.php?statute=77-3605
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=2
    * 2025 Nebraska Individual Income Tax Booklet, Line 49: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=19 -/
def gov.states.ne.tax.income.credits.school_readiness.amount.refundable.«1» : DatedParam USD :=
  ⟨(⟨2024, 1, 1⟩, 2300), []⟩
def gov.states.ne.tax.income.credits.school_readiness.amount.refundable.«2» : DatedParam USD :=
  ⟨(⟨2024, 1, 1⟩, 2600), []⟩
def gov.states.ne.tax.income.credits.school_readiness.amount.refundable.«3» : DatedParam USD :=
  ⟨(⟨2024, 10, 1⟩, 2900), []⟩
def gov.states.ne.tax.income.credits.school_readiness.amount.refundable.«4» : DatedParam USD :=
  ⟨(⟨2024, 10, 1⟩, 3200), []⟩
def gov.states.ne.tax.income.credits.school_readiness.amount.refundable.«5» : DatedParam USD :=
  ⟨(⟨2024, 10, 1⟩, 3500), []⟩

/-- Nebraska caps Nebraska Early Childhood Professional (ECP) Record System level at the following level, under the School Readiness credit.
    `gov/states/ne/tax/income/credits/school_readiness/max_unit_size.yaml` (policyengine-us).
    * Nebraska Revised Statute 77-3605: https://nebraskalegislature.gov/laws/statutes.php?statute=77-3605
    * 2024 Nebraska Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=2
    * 2025 Nebraska Individual Income Tax Booklet, Line 49: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=19 -/
def gov.states.ne.tax.income.credits.school_readiness.max_unit_size : DatedParam Rat :=
  ⟨(⟨2024, 1, 1⟩, 5), []⟩

/-- Nebraska provides this refundable credit for each stillborn child for whom a Birth Resulting in Stillbirth Certificate has been issued, where the stillbirth occurred at or after the twentieth week of gestation and the child would have been a dependent.
    `gov/states/ne/tax/income/credits/stillborn.yaml` (policyengine-us).
    * Neb. Rev. Stat. § 77-2715.07(9) (stillborn child tax credit): https://nebraskalegislature.gov/laws/statutes.php?statute=77-2715.07
    * Nebraska LB 432 (2021), § 11 (enacting legislation): https://nebraskalegislature.gov/FloorDocs/107/PDF/Slip/LB432.pdf
    * 2022 Nebraska Individual Income Tax Booklet (Form 1040N, line 38 instructions): https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_8.pdf#page=12
    * 2023 Nebraska Individual Income Tax Booklet (Form 1040N, line 39 instructions): https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=14
    * 2024 Nebraska Individual Income Tax Booklet (Form 1040N, line 45 instructions): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=16 -/
def gov.states.ne.tax.income.credits.stillborn : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 0), [(⟨2022, 1, 1⟩, 2000)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/additional_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.additional_amount.SINGLE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 1650), [(⟨2022, 1, 1⟩, 1700), (⟨2023, 1, 1⟩, 1850), (⟨2024, 1, 1⟩, 1950), (⟨2025, 1, 1⟩, 2000)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/additional_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.additional_amount.JOINT : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 1350), [(⟨2022, 1, 1⟩, 1400), (⟨2023, 1, 1⟩, 1500), (⟨2024, 1, 1⟩, 1600), (⟨2025, 1, 1⟩, 1650)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/additional_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.additional_amount.SURVIVING_SPOUSE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 1350), [(⟨2022, 1, 1⟩, 1400), (⟨2023, 1, 1⟩, 1500), (⟨2024, 1, 1⟩, 1600), (⟨2025, 1, 1⟩, 1650)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/additional_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.additional_amount.SEPARATE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 1350), [(⟨2022, 1, 1⟩, 1400), (⟨2023, 1, 1⟩, 1500), (⟨2024, 1, 1⟩, 1600), (⟨2025, 1, 1⟩, 1650)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/additional_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.additional_amount.HEAD_OF_HOUSEHOLD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 1650), [(⟨2022, 1, 1⟩, 1700), (⟨2023, 1, 1⟩, 1850), (⟨2024, 1, 1⟩, 1950), (⟨2025, 1, 1⟩, 2000)]⟩

/-- Nebraska limits its extra standard deduction to filers this age or older.
    `gov/states/ne/tax/income/deductions/standard/age_minimum.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * Nebraska Revised Statute | chapter 77 | §2716.01: https://nebraskalegislature.gov/laws/statutes.php?statute=77-2716.01
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=8
    * 2024 Nebraska Individual Income Tax Booklet, Line 2a: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=8
    * 2025 Nebraska Individual Income Tax Booklet, Line 6: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=13 -/
def gov.states.ne.tax.income.deductions.standard.age_minimum : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 65), []⟩

/-- `gov/states/ne/tax/income/deductions/standard/base_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.base_amount.JOINT : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 14200), [(⟨2022, 1, 1⟩, 14700), (⟨2023, 1, 1⟩, 15800), (⟨2024, 1, 1⟩, 16700), (⟨2025, 1, 1⟩, 17200)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/base_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.base_amount.HEAD_OF_HOUSEHOLD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 10450), [(⟨2022, 1, 1⟩, 10750), (⟨2023, 1, 1⟩, 11600), (⟨2024, 1, 1⟩, 12250), (⟨2025, 1, 1⟩, 12600)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/base_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.base_amount.SURVIVING_SPOUSE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 14200), [(⟨2022, 1, 1⟩, 14700), (⟨2023, 1, 1⟩, 15800), (⟨2024, 1, 1⟩, 16700), (⟨2025, 1, 1⟩, 17200)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/base_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.base_amount.SINGLE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 7100), [(⟨2022, 1, 1⟩, 7350), (⟨2023, 1, 1⟩, 7900), (⟨2024, 1, 1⟩, 8350), (⟨2025, 1, 1⟩, 8600)]⟩

/-- `gov/states/ne/tax/income/deductions/standard/base_amount.yaml` (policyengine-us). -/
def gov.states.ne.tax.income.deductions.standard.base_amount.SEPARATE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 7100), [(⟨2022, 1, 1⟩, 7350), (⟨2023, 1, 1⟩, 7900), (⟨2024, 1, 1⟩, 8350), (⟨2025, 1, 1⟩, 8600)]⟩

/-- Nebraska per-person exemption amount
    `gov/states/ne/tax/income/exemptions/amount.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * Nebraska Revised Statute | chapter 77 | §2716.01: https://nebraskalegislature.gov/laws/statutes.php?statute=77-2716.01
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=10
    * 2024 Nebraska Individual Income Tax Booklet, Line 18: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2024/f_Individual_Income_Tax_Booklet.pdf#page=11
    * 2025 Nebraska Individual Income Tax Booklet, Line 18: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=14 -/
def gov.states.ne.tax.income.exemptions.amount : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 142), [(⟨2022, 1, 1⟩, 146), (⟨2023, 1, 1⟩, 157), (⟨2024, 1, 1⟩, 166), (⟨2025, 1, 1⟩, 171)]⟩

/-- Nebraska taxes head of household filers at these rates.
    `gov/states/ne/tax/income/rates/head_of_household.yaml` (policyengine-us).
    * Legislative Bill 754 (Bill Text): https://www.nebraskalegislature.gov/FloorDocs/108/PDF/Slip/LB754.pdf#page=3
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=9
    * Nebraska Revised Statute | chapter 77 | §2715.03: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2715.03
    * Nebraska Tax Rate Chronologies: https://revenue.nebraska.gov/sites/default/files/doc/research/chronology/4-607table1_0.pdf
    * 2025 Nebraska Individual Income Tax Booklet, Tax Table: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=49
    * 2026 Nebraska Estimated Income Tax Rate Schedule (Form 1040N-ES): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_1040N-ES.pdf#page=5 -/
def gov.states.ne.tax.income.rates.head_of_household : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 123 5000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 6220), [(⟨2022, 1, 1⟩, 6410), (⟨2023, 1, 1⟩, 6900), (⟨2024, 1, 1⟩, 7270), (⟨2025, 1, 1⟩, 7510), (⟨2026, 1, 1⟩, 7700)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 351 10000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 31990), [(⟨2022, 1, 1⟩, 32950), (⟨2023, 1, 1⟩, 35480), (⟨2024, 1, 1⟩, 37400), (⟨2025, 1, 1⟩, 38590), (⟨2026, 1, 1⟩, 39620)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 501 10000), [(⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 47760), [(⟨2022, 1, 1⟩, 49200), (⟨2023, 1, 1⟩, 52980), (⟨2024, 1, 1⟩, 55850), (⟨2025, 1, 1⟩, 57630), (⟨2026, 1, 1⟩, 59160)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 171 2500), [(⟨2023, 1, 1⟩, mkRat 83 1250), (⟨2024, 1, 1⟩, mkRat 73 1250), (⟨2025, 1, 1⟩, mkRat 13 250), (⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩]⟩

/-- Nebraska taxes joint filers at these rates.
    `gov/states/ne/tax/income/rates/joint.yaml` (policyengine-us).
    * Legislative Bill 754 (Bill Text): https://www.nebraskalegislature.gov/FloorDocs/108/PDF/Slip/LB754.pdf#page=3
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=9
    * Nebraska Revised Statute | chapter 77 | §2715.03: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2715.03
    * Nebraska Tax Rate Chronologies: https://revenue.nebraska.gov/sites/default/files/doc/research/chronology/4-607table1_0.pdf
    * 2025 Nebraska Individual Income Tax Booklet, Tax Table: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=49
    * 2026 Nebraska Estimated Income Tax Rate Schedule (Form 1040N-ES): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_1040N-ES.pdf#page=5 -/
def gov.states.ne.tax.income.rates.joint : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 123 5000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 6660), [(⟨2022, 1, 1⟩, 6860), (⟨2023, 1, 1⟩, 7390), (⟨2024, 1, 1⟩, 7790), (⟨2025, 1, 1⟩, 8040), (⟨2026, 1, 1⟩, 8250)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 351 10000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 39990), [(⟨2022, 1, 1⟩, 41190), (⟨2023, 1, 1⟩, 44350), (⟨2024, 1, 1⟩, 46760), (⟨2025, 1, 1⟩, 48250), (⟨2026, 1, 1⟩, 49530)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 501 10000), [(⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 64430), [(⟨2022, 1, 1⟩, 66360), (⟨2023, 1, 1⟩, 71460), (⟨2024, 1, 1⟩, 75340), (⟨2025, 1, 1⟩, 77730), (⟨2026, 1, 1⟩, 79800)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 171 2500), [(⟨2023, 1, 1⟩, mkRat 83 1250), (⟨2024, 1, 1⟩, mkRat 73 1250), (⟨2025, 1, 1⟩, mkRat 13 250), (⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩]⟩

/-- Nebraska taxes separate filers at these rates.
    `gov/states/ne/tax/income/rates/separate.yaml` (policyengine-us).
    * Legislative Bill 754 (Bill Text): https://www.nebraskalegislature.gov/FloorDocs/108/PDF/Slip/LB754.pdf#page=3
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=9
    * Nebraska Revised Statute | chapter 77 | §2715.03: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2715.03
    * Nebraska Tax Rate Chronologies: https://revenue.nebraska.gov/sites/default/files/doc/research/chronology/4-607table1_0.pdf
    * 2025 Nebraska Individual Income Tax Booklet, Tax Table: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=49
    * 2026 Nebraska Estimated Income Tax Rate Schedule (Form 1040N-ES): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_1040N-ES.pdf#page=5 -/
def gov.states.ne.tax.income.rates.separate : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 123 5000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 3340), [(⟨2022, 1, 1⟩, 3440), (⟨2023, 1, 1⟩, 3700), (⟨2024, 1, 1⟩, 3900), (⟨2025, 1, 1⟩, 4030), (⟨2026, 1, 1⟩, 4130)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 351 10000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 19990), [(⟨2022, 1, 1⟩, 20590), (⟨2023, 1, 1⟩, 22170), (⟨2024, 1, 1⟩, 23370), (⟨2025, 1, 1⟩, 24120), (⟨2026, 1, 1⟩, 24760)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 501 10000), [(⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 32210), [(⟨2022, 1, 1⟩, 33180), (⟨2023, 1, 1⟩, 35730), (⟨2024, 1, 1⟩, 37670), (⟨2025, 1, 1⟩, 38870), (⟨2026, 1, 1⟩, 39900)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 171 2500), [(⟨2023, 1, 1⟩, mkRat 83 1250), (⟨2024, 1, 1⟩, mkRat 73 1250), (⟨2025, 1, 1⟩, mkRat 13 250), (⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩]⟩

/-- Nebraska taxes single filers at these rates.
    `gov/states/ne/tax/income/rates/single.yaml` (policyengine-us).
    * Legislative Bill 754 (Bill Text): https://www.nebraskalegislature.gov/FloorDocs/108/PDF/Slip/LB754.pdf#page=3
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=9
    * Nebraska Revised Statute | chapter 77 | §2715.03: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2715.03
    * Nebraska Tax Rate Chronologies: https://revenue.nebraska.gov/sites/default/files/doc/research/chronology/4-607table1_0.pdf
    * 2025 Nebraska Individual Income Tax Booklet, Tax Table: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=49
    * 2026 Nebraska Estimated Income Tax Rate Schedule (Form 1040N-ES): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_1040N-ES.pdf#page=5 -/
def gov.states.ne.tax.income.rates.single : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 123 5000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 3340), [(⟨2022, 1, 1⟩, 3440), (⟨2023, 1, 1⟩, 3700), (⟨2024, 1, 1⟩, 3900), (⟨2025, 1, 1⟩, 4030), (⟨2026, 1, 1⟩, 4130)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 351 10000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 19990), [(⟨2022, 1, 1⟩, 20590), (⟨2023, 1, 1⟩, 22170), (⟨2024, 1, 1⟩, 23370), (⟨2025, 1, 1⟩, 24120), (⟨2026, 1, 1⟩, 24760)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 501 10000), [(⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 32210), [(⟨2022, 1, 1⟩, 33180), (⟨2023, 1, 1⟩, 35730), (⟨2024, 1, 1⟩, 37670), (⟨2025, 1, 1⟩, 38870), (⟨2026, 1, 1⟩, 39900)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 171 2500), [(⟨2023, 1, 1⟩, mkRat 83 1250), (⟨2024, 1, 1⟩, mkRat 73 1250), (⟨2025, 1, 1⟩, mkRat 13 250), (⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩]⟩

/-- Nebraska taxes surviving spouses at these rates.
    `gov/states/ne/tax/income/rates/surviving_spouse.yaml` (policyengine-us).
    * 2021 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/tax-forms/2021/f_1040n_booklet.pdf
    * 2022 NE income tax form and instruction booklet: https://revenue.nebraska.gov/files/doc/2022_Ne_Individual_Income_Tax_Booklet_8-307-2022_final_5.pdf
    * 2023 NE Individual Income Tax Booklet: https://revenue.nebraska.gov/sites/revenue.nebraska.gov/files/doc/tax-forms/2023/incometax/f_1040n_booklet_2023_Final.pdf#page=9
    * Nebraska Revised Statute | chapter 77 | §2715.03: https://www.nebraskalegislature.gov/laws/statutes.php?statute=77-2715.03
    * Nebraska Tax Rate Chronologies: https://revenue.nebraska.gov/sites/default/files/doc/research/chronology/4-607table1_0.pdf
    * 2025 Nebraska Individual Income Tax Booklet, Tax Table: https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_Individual_Income_Tax_Booklet.pdf#page=49
    * 2026 Nebraska Estimated Income Tax Rate Schedule (Form 1040N-ES): https://revenue.nebraska.gov/sites/default/files/doc/tax-forms/2025/f_1040N-ES.pdf#page=5 -/
def gov.states.ne.tax.income.rates.surviving_spouse : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 123 5000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 6660), [(⟨2022, 1, 1⟩, 6860), (⟨2023, 1, 1⟩, 7390), (⟨2024, 1, 1⟩, 7790), (⟨2025, 1, 1⟩, 8040), (⟨2026, 1, 1⟩, 8250)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 351 10000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 39990), [(⟨2022, 1, 1⟩, 41190), (⟨2023, 1, 1⟩, 44350), (⟨2024, 1, 1⟩, 46760), (⟨2025, 1, 1⟩, 48250), (⟨2026, 1, 1⟩, 49530)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 501 10000), [(⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 64430), [(⟨2022, 1, 1⟩, 66360), (⟨2023, 1, 1⟩, 71460), (⟨2024, 1, 1⟩, 75340), (⟨2025, 1, 1⟩, 77730), (⟨2026, 1, 1⟩, 79800)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 171 2500), [(⟨2023, 1, 1⟩, mkRat 83 1250), (⟨2024, 1, 1⟩, mkRat 73 1250), (⟨2025, 1, 1⟩, mkRat 13 250), (⟨2026, 1, 1⟩, mkRat 91 2000), (⟨2027, 1, 1⟩, mkRat 399 10000)]⟩⟩]⟩

/-- Default employer-side unemployment insurance tax rate for Nebraska.
    `gov/states/ne/tax/payroll/unemployment/default_rate.yaml` (policyengine-us).
    * Nebraska Revised Statute 48-649.02: https://nebraskalegislature.gov/laws/statutes.php?statute=48-649.02
    * Tax Measures of State Unemployment Insurance Tax Systems, CY 2024: https://oui.doleta.gov/unemploy/pdf/sigmeasures/sigmeasuitaxsys24.pdf#page=37 -/
def gov.states.ne.tax.payroll.unemployment.default_rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 1 80), []⟩

/-- Employer-side unemployment insurance taxable wage base for Nebraska.
    `gov/states/ne/tax/payroll/unemployment/taxable_wage_base.yaml` (policyengine-us).
    * Nebraska Revised Statute 48-648: https://nebraskalegislature.gov/laws/statutes.php?statute=48-648
    * Tax Measures of State Unemployment Insurance Tax Systems, CY 2024: https://oui.doleta.gov/unemploy/pdf/sigmeasures/sigmeasuitaxsys24.pdf#page=37 -/
def gov.states.ne.tax.payroll.unemployment.taxable_wage_base : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 9000), []⟩

end Lawlib.Gen.Params
