/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Wisconsin limits countable resources to this amount under the Wisconsin Works program.
    `gov/states/wi/dcf/works/asset/limit.yaml` (policyengine-us).
    * W-2 Manual 3.3.4 - Counting Assets: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/03/03.3.4_COUNTING_ASSETS.htm
    * Wisconsin Administrative Code DCF 101.09(3)(b): https://docs.legis.wisconsin.gov/code/admin_code/dcf/101_199/101/09/3/b
    * Wisconsin Statutes 49.145(2)(d): https://docs.legis.wisconsin.gov/statutes/statutes/49/iii/145/2/d -/
def gov.states.wi.dcf.works.asset.limit : DatedParam USD :=
  ⟨(⟨1997, 5, 1⟩, 2500), []⟩

/-- Wisconsin excludes this amount of vehicle equity from countable resources under the Wisconsin Works program.
    `gov/states/wi/dcf/works/asset/vehicle_exclusion.yaml` (policyengine-us).
    * W-2 Manual 3.3.4 - Counting Assets: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/03/03.3.4_COUNTING_ASSETS.htm
    * Wisconsin Administrative Code DCF 101.09(3)(b): https://docs.legis.wisconsin.gov/code/admin_code/dcf/101_199/101/09/3/b -/
def gov.states.wi.dcf.works.asset.vehicle_exclusion : DatedParam USD :=
  ⟨(⟨1997, 5, 1⟩, 10000), []⟩

/-- Wisconsin limits gross income to this share of the federal poverty guideline under the Wisconsin Works program.
    `gov/states/wi/dcf/works/income_limit/rate.yaml` (policyengine-us).
    * W-2 Manual 3.2.1 - 115 Percent Gross Income Test: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/03/03.2.1_115_Percent_Gross_Income_Test.htm
    * Wisconsin Administrative Code DCF 101.09(3)(a): https://docs.legis.wisconsin.gov/code/admin_code/dcf/101_199/101/09/3/a
    * Wisconsin Statutes 49.145(2)(a): https://docs.legis.wisconsin.gov/statutes/statutes/49/iii/145/2/a -/
def gov.states.wi.dcf.works.income_limit.rate : DatedParam Rate :=
  ⟨(⟨1997, 5, 1⟩, mkRat 23 20), []⟩

/-- Wisconsin provides this amount as the monthly payment under the Wisconsin Works program.
    `gov/states/wi/dcf/works/placement/amount.yaml` (policyengine-us).
    * Wisconsin Statutes 49.148(1)(b): https://docs.legis.wisconsin.gov/statutes/statutes/49/iii/148/1/b
    * W-2 Manual 7.4.1 - Community Service Jobs: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/07/7.4.1_Community_Service_Jobs_(CSJ).htm
    * Wisconsin Administrative Code DCF 101.18(2): https://docs.legis.wisconsin.gov/code/admin_code/dcf/101_199/101/18/2 -/
def gov.states.wi.dcf.works.placement.amount.ARP : DatedParam USD :=
  ⟨(⟨1997, 9, 1⟩, 673), []⟩
def gov.states.wi.dcf.works.placement.amount.CMC : DatedParam USD :=
  ⟨(⟨1997, 9, 1⟩, 673), []⟩
def gov.states.wi.dcf.works.placement.amount.CSJ : DatedParam USD :=
  ⟨(⟨1997, 9, 1⟩, 673), [(⟨2011, 10, 1⟩, 653)]⟩
def gov.states.wi.dcf.works.placement.amount.NONE : DatedParam USD :=
  ⟨(⟨1997, 9, 1⟩, 0), []⟩
def gov.states.wi.dcf.works.placement.amount.W2_TRANSITION : DatedParam USD :=
  ⟨(⟨1997, 9, 1⟩, 628), [(⟨2011, 10, 1⟩, 608)]⟩

/-- Wisconsin limits the At Risk Pregnancy placement to pregnant individuals at or above this pregnancy month under the Wisconsin Works program.
    `gov/states/wi/dcf/works/placement/arp_pregnancy_month_threshold.yaml` (policyengine-us).
    * Wisconsin Statutes 49.148(1m)(a)2: https://docs.legis.wisconsin.gov/statutes/statutes/49/iii/148
    * W-2 Manual 7.4.4 - At Risk Pregnancy: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/07/7.4.4_At_Risk_Pregnancy.htm -/
def gov.states.wi.dcf.works.placement.arp_pregnancy_month_threshold : DatedParam Rat :=
  ⟨(⟨1997, 9, 1⟩, 7), []⟩

/-- Wisconsin limits the Custodial Parent of Infant placement to parents with children at or below this age in months under the Wisconsin Works program.
    `gov/states/wi/dcf/works/placement/cmc_infant_age_limit.yaml` (policyengine-us).
    * Wisconsin Statutes 49.148(1m)(a)1: https://docs.legis.wisconsin.gov/statutes/statutes/49/iii/148
    * W-2 Manual 7.4.5 - Custodial Parent of an Infant: https://dcf.wisconsin.gov/manuals/w-2-manual/Production/07/7.4.5_Custodial_Parent_of_an_Infant_CMC_.htm -/
def gov.states.wi.dcf.works.placement.cmc_infant_age_limit : DatedParam Rat :=
  ⟨(⟨2011, 10, 1⟩, 2), []⟩

/-- Wisconsin charges this BadgerCare Plus monthly premium per CHIP-eligible child, based on the tax unit's modified adjusted gross income as a fraction of the federal poverty line. The total for all children is also capped at 5 percent of the assistance group's income under the federal cost-sharing cap.
    `gov/states/wi/hhs/chip/premium/per_child.yaml` (policyengine-us).
    * Wisconsin BadgerCare Plus Eligibility Handbook 48.1 - Premiums for Children: https://www.emhandbooks.wisconsin.gov/bcplus/policyfiles/6/48.1.htm -/
def gov.states.wi.hhs.chip.premium.per_child : ScaleX :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, .negInf), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 0), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 201 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 10), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 231 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 15), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 241 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 23), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 251 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 34), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 261 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 44), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 271 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 55), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 281 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 68), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 291 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin 82), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, .fin (mkRat 301 100)), []⟩, ⟨(⟨2021, 1, 1⟩, .fin (mkRat 9753 100)), []⟩⟩]⟩

/-- Wisconsin limits capital losses to this amount, based on filing status.
    `gov/states/wi/tax/income/additions/capital_loss/limit.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule WD, Line 28: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleWDf.pdf#page=2
    * 2022 Wisconsin Form 1 Schedule WD, Line 28: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleWDf.pdf#page=2
    * 2023 Wisconsin Form 1 Schedule WD, Line 28: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleWDf.pdf#page=2
    * 2024 Wisconsin Form 1 Schedule WD, Line 28: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWDf.pdf#page=2
    * 2025 Wisconsin Form 1 Schedule WD, Line 28: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleWDf.pdf#page=2 -/
def gov.states.wi.tax.income.additions.capital_loss.limit.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), [(⟨2023, 1, 1⟩, 3000)]⟩
def gov.states.wi.tax.income.additions.capital_loss.limit.JOINT : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), [(⟨2023, 1, 1⟩, 3000)]⟩
def gov.states.wi.tax.income.additions.capital_loss.limit.SEPARATE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), [(⟨2023, 1, 1⟩, 1500)]⟩
def gov.states.wi.tax.income.additions.capital_loss.limit.SINGLE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), [(⟨2023, 1, 1⟩, 3000)]⟩
def gov.states.wi.tax.income.additions.capital_loss.limit.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), [(⟨2023, 1, 1⟩, 3000)]⟩

/-- Wisconsin adds these variables to US adjusted gross income when computing its gross income.
    `gov/states/wi/tax/income/additions/sources.yaml` (policyengine-us).
    * 2021 WI schedule AD: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleADf.pdf
    * 2021 WI schedule AD instructions: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleAD-Inst.pdf
    * 2022 WI schedule AD: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleADf.pdf
    * 2022 WI schedule AD instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleAD-Inst.pdf
    * 2023 WI schedule AD instructions: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleAD-Inst.pdf
    * 2024 WI schedule AD instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleAD-Inst.pdf
    * 2025 WI schedule AD instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleAD-Inst.pdf -/
def gov.states.wi.tax.income.additions.sources : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["tax_exempt_interest_income", "wi_capital_gain_loss_addition", "form_4972_lumpsum_distributions"]), []⟩

/-- Wisconsin allows this fraction of the federal child and dependent care credit as an AGI income subtraction.
    `gov/states/wi/tax/income/credits/childcare_expense/fraction.yaml` (policyengine-us).
    * 2022 Form 1: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=2
    * 2022 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=17
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=18
    * 2024 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWI-2441-Inst.pdf
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=17
    * 2024 Wisconsin Statutes Taxation. 71.07 (9g) (b): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/07/9g -/
def gov.states.wi.tax.income.credits.childcare_expense.fraction : DatedParam Rate :=
  ⟨(⟨2022, 1, 1⟩, mkRat 1 2), [(⟨2024, 1, 1⟩, 1)]⟩

/-- Wisconsin caps child and dependent care expenses at this amount per qualifying individual.
    `gov/states/wi/tax/income/credits/childcare_expense/max_expense.yaml` (policyengine-us).
    * Wisconsin Statute § 71.07(9g)(c)5 (2023 Wisconsin Act 101): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/07/9g
    * 2024 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWI-2441-Inst.pdf -/
def gov.states.wi.tax.income.credits.childcare_expense.max_expense : DatedParam USD :=
  ⟨(⟨2022, 1, 1⟩, 0), [(⟨2024, 1, 1⟩, 10000)]⟩

/-- Wisconsin applies the federal investment income limit for the earned income tax credit if this is true.
    `gov/states/wi/tax/income/credits/earned_income/apply_federal_investment_income_limit.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 instructions for Line 26: https://www.revenue.wi.gov/TaxForms2021/2021-Form1-Inst.pdf#page=27
    * 2022 Wisconsin Form 1 instructions for Line 29: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=27
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=27
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=26
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=26 -/
def gov.states.wi.tax.income.credits.earned_income.apply_federal_investment_income_limit : DatedParam Bool :=
  ⟨(⟨2021, 1, 1⟩, false), [(⟨2023, 1, 1⟩, true)]⟩

/-- Wisconsin matches this fraction of the federal EITC, depending on the number of EITC-eligible children.
    `gov/states/wi/tax/income/credits/earned_income/fraction.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 instructions for Line 26: https://www.revenue.wi.gov/TaxForms2021/2021-Form1-Inst.pdf#page=27
    * 2022 Wisconsin Form 1 instructions for Line 29: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=27
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=28
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=26
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=26 -/
def gov.states.wi.tax.income.credits.earned_income.fraction : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 1), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 1 25), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 2), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 11 100), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 3), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 17 50), []⟩⟩]⟩

/-- Wisconsin limits EITC eligibility to this investment income amount.
    `gov/states/wi/tax/income/credits/earned_income/investment_income_limit.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 instructions for Line 26: https://www.revenue.wi.gov/TaxForms2021/2021-Form1-Inst.pdf#page=27
    * 2022 Wisconsin Form 1 instructions for Line 29: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=27
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=27
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=26 -/
def gov.states.wi.tax.income.credits.earned_income.investment_income_limit : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3650), [(⟨2022, 1, 1⟩, 3800)]⟩

/-- Wisconsin homestead credits recognizes these earnings sources.
    `gov/states/wi/tax/income/credits/homestead/eligible/earnings_sources.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=7
    * 2025 Wisconsin Schedule H instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=7 -/
def gov.states.wi.tax.income.credits.homestead.eligible.earnings_sources : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["irs_employment_income", "self_employment_income", "sstb_self_employment_income", "partnership_s_corp_income", "farm_operations_income"]), []⟩

/-- Wisconsin homestead credit has this maximum income for eligibility.
    `gov/states/wi/tax/income/credits/homestead/eligible/max_income.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=5
    * 2021 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf#page=26
    * 2022 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=25
    * 2023 I-016a Schedule H & H-EZ Instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=4
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=9 -/
def gov.states.wi.tax.income.credits.homestead.eligible.max_income : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 24680), []⟩

/-- Wisconsin homestead credit has this minimum age for eligibility.
    `gov/states/wi/tax/income/credits/homestead/eligible/min_age.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=7
    * 2021 Wisconsin Form 1 Schedule H, Line 1a: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf
    * 2022 Wisconsin Form 1 Schedule H, Line 1a: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf
    * 2023 I-016a Schedule H & H-EZ Instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=1
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=9
    * 2025 Wisconsin Schedule H instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=4 -/
def gov.states.wi.tax.income.credits.homestead.eligible.min_age : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 18), []⟩

/-- Wisconsin homestead credit has this minimum elderly age for eligibility.
    `gov/states/wi/tax/income/credits/homestead/eligible/min_elderly_age.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=7
    * 2021 Wisconsin Form 1 Schedule H, Line 1c: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf
    * 2022 Wisconsin Form 1 Schedule H, Line 1c: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf
    * 2023 I-016a Schedule H & H-EZ Instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=4
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=9
    * 2025 Wisconsin Schedule H instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=4 -/
def gov.states.wi.tax.income.credits.homestead.eligible.min_elderly_age : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 62), []⟩

/-- Wisconsin homestead credit has this dependent exemption.
    `gov/states/wi/tax/income/credits/homestead/income/exemption.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule H, Line 12b: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf#page=2
    * 2022 Wisconsin Form 1 Schedule H, Line 12b: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=2
    * 2023 I-016a Schedule H & H-EZ Instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=8
    * 2024 I-016 Schedule H: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleH.pdf#page=2
    * 2025 Wisconsin Schedule H, Line 12b: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH.pdf#page=2 -/
def gov.states.wi.tax.income.credits.homestead.income.exemption : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 500), []⟩

/-- Wisconsin homestead credit recognizes these income sources.
    `gov/states/wi/tax/income/credits/homestead/income/sources.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=14
    * 2025 Wisconsin Schedule H instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=6 -/
def gov.states.wi.tax.income.credits.homestead.income.sources : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["adjusted_gross_income", "tax_exempt_interest_income", "tax_exempt_social_security", "tax_exempt_pension_income", "tax_exempt_unemployment_compensation", "ssi", "tanf"]), []⟩

/-- Wisconsin homestead credit phases out capped property taxes at this rate.
    `gov/states/wi/tax/income/credits/homestead/phase_out/rate.yaml` (policyengine-us).
    * Homestead Tax Credit, WI Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=5
    * 2021 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH-inst.pdf#page=26
    * 2022 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH-inst.pdf#page=25
    * 2024 Wisconsin Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleH-inst.pdf#page=25
    * Wisconsin Statutes 71.54 (1)(g)(2): https://docs.legis.wisconsin.gov/statutes/statutes/71/viii/54 -/
def gov.states.wi.tax.income.credits.homestead.phase_out.rate : DatedParam Rate :=
  ⟨(⟨2012, 1, 1⟩, mkRat 1757 20000), []⟩

/-- Wisconsin homestead credit phases out capped property taxes starting at this income.
    `gov/states/wi/tax/income/credits/homestead/phase_out/start.yaml` (policyengine-us).
    * Homestead Tax Credit, Wisconsin Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=5
    * 2021 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf#page=26
    * 2022 Wisconsin Form 1 Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=25
    * 2023 I-016a Schedule H & H-EZ Instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=25
    * 2024 Wisconsin Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleH-inst.pdf#page=25
    * 2025 Wisconsin Schedule H instructions, Table A: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=25
    * Wisconsin Statutes 71.54 (1)(g)(2): https://docs.legis.wisconsin.gov/statutes/statutes/71/viii/54 -/
def gov.states.wi.tax.income.credits.homestead.phase_out.start : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 8060), []⟩

/-- Wisconsin homestead credit caps property taxes at this maximum.
    `gov/states/wi/tax/income/credits/homestead/property_tax/max.yaml` (policyengine-us).
    * Homestead Tax Credit, WI Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=5
    * 2021 Wisconsin Form 1 Schedule H, Line 16: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf#page=2
    * 2022 Wisconsin Form 1 Schedule H, Line 16: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=2
    * Wisconsin Statutes 71.54 (2)(b)(4): https://docs.legis.wisconsin.gov/statutes/statutes/71/viii/54
    * 2023 Wisconsin Form 1 Schedule H, Line 14: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH-inst.pdf#page=26
    * 2025 Wisconsin Schedule H, Line 16: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH.pdf#page=2 -/
def gov.states.wi.tax.income.credits.homestead.property_tax.max : DatedParam USD :=
  ⟨(⟨2011, 1, 1⟩, 1460), []⟩

/-- Wisconsin homestead credit assumes property taxes are this ratio to rent.
    `gov/states/wi/tax/income/credits/homestead/property_tax/rent_ratio.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule H, Line 14: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH.pdf#page=2
    * 2022 Wisconsin Form 1 Schedule H, Line 14: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH.pdf#page=2
    * 2023 Wisconsin Form 1 Schedule H, Line 14: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleH-Inst.pdf#page=18
    * 2025 Wisconsin Schedule H, Line 14: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH.pdf#page=2 -/
def gov.states.wi.tax.income.credits.homestead.property_tax.rent_ratio : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 5), []⟩

/-- Wisconsin homestead credit equals eligible property taxes times this rate.
    `gov/states/wi/tax/income/credits/homestead/rate.yaml` (policyengine-us).
    * Homestead Tax Credit, WI Legislative Fiscal Bureau: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2021/0013_homestead_tax_credit_informational_paper_13.pdf#page=5
    * 2021 Wisconsin Form 1 Schedule H instructions, Table B: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleH-inst.pdf#page=27
    * 2022 Wisconsin Form 1 Schedule H instructions, Table B: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleH-inst.pdf#page=26
    * 2024 Wisconsin Schedule H instructions, Table B: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleH-inst.pdf#page=26
    * 2025 Wisconsin Schedule H instructions, Table B: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleH-inst.pdf#page=26
    * Wisconsin Statutes 71.54 (1)(g)(2): https://docs.legis.wisconsin.gov/statutes/statutes/71/viii/54 -/
def gov.states.wi.tax.income.credits.homestead.rate : DatedParam Rate :=
  ⟨(⟨2012, 1, 1⟩, mkRat 4 5), []⟩

/-- Wisconsin has an itemized deduction credit equal to this rate times the excess of itemized deductions over the standard deduction.
    `gov/states/wi/tax/income/credits/itemized_deduction/rate.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=4
    * 2022 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=4
    * 2023 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2023/2023-Form1.pdf#page=4
    * 2024 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2024/2024-Form1.pdf#page=4
    * 2025 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2025/2025-Form1.pdf#page=4 -/
def gov.states.wi.tax.income.credits.itemized_deduction.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 20), []⟩

/-- Wisconsin married couple credit has these income sources
    `gov/states/wi/tax/income/credits/married_couple/income_sources.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=4
    * 2021 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=4
    * 2023 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2023/2023-Form1.pdf#page=4
    * 2024 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2024/2024-Form1.pdf#page=4
    * 2025 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2025/2025-Form1.pdf#page=4 -/
def gov.states.wi.tax.income.credits.married_couple.income_sources : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["irs_employment_income", "self_employment_income", "sstb_self_employment_income", "partnership_s_corp_income", "farm_operations_income"]), []⟩

/-- Wisconsin married couple credit is limited to this maximum.
    `gov/states/wi/tax/income/credits/married_couple/max.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=4
    * 2021 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=4
    * 2023 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2023/2023-Form1.pdf#page=4
    * 2024 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2024/2024-Form1.pdf#page=4
    * 2025 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2025/2025-Form1.pdf#page=4 -/
def gov.states.wi.tax.income.credits.married_couple.max : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 480), []⟩

/-- Wisconsin married couple credit is calculated using this rate.
    `gov/states/wi/tax/income/credits/married_couple/rate.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=4
    * 2022 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=4
    * 2023 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2023/2023-Form1.pdf#page=4
    * 2024 Wisconsin Form 1, Schedule 1: https://www.revenue.wi.gov/TaxForms2024/2024-Form1.pdf#page=4
    * 2025 Wisconsin Form 1, Schedule 2: https://www.revenue.wi.gov/TaxForms2025/2025-Form1.pdf#page=4 -/
def gov.states.wi.tax.income.credits.married_couple.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 100), []⟩

/-- Wisconsin income tax has these nonrefundable credits.
    `gov/states/wi/tax/income/credits/non_refundable.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=2
    * 2021 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2021/2021-Form1-Inst.pdf#page=16
    * 2022 Wisconsin Form 1: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=2
    * 2022 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=16
    * 2023 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=18
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=16
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=16 -/
def gov.states.wi.tax.income.credits.non_refundable : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["wi_itemized_deduction_credit", "wi_property_tax_credit", "wi_married_couple_credit"]), [(⟨2022, 1, 1⟩, ["wi_itemized_deduction_credit", "wi_childcare_expense_credit", "wi_property_tax_credit", "wi_married_couple_credit"])]⟩

/-- Wisconsin property tax credit is limited to this maximum.
    `gov/states/wi/tax/income/credits/property_tax/max.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on WI income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf#page=19
    * 2024 Form 1 instructions - Homeowner's School Property Tax Credit Table: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=20
    * 2025 Form 1 instructions - Homeowner's School Property Tax Credit Table: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=20 -/
def gov.states.wi.tax.income.credits.property_tax.max : DatedParam USD :=
  ⟨(⟨2000, 1, 1⟩, 300), []⟩

/-- Wisconsin propery tax credit is calculated using this rate.
    `gov/states/wi/tax/income/credits/property_tax/rate.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on WI income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf#page=19
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/07/9/b/5
    * 2024 Form 1 instructions - Homeowner's School Property Tax Credit Table: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=20
    * 2025 Form 1 instructions - Homeowner's School Property Tax Credit Table: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=20 -/
def gov.states.wi.tax.income.credits.property_tax.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 25), []⟩

/-- Wisconsin property tax credit considers property taxes to be this fraction of rent.
    `gov/states/wi/tax/income/credits/property_tax/rent_fraction.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on WI income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf#page=19
    * 2025 Form 1 instructions - Renter's School Property Tax Credit: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=18
    * Wisconsin Statutes 71.07 (9)(a)(4): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/07/9/b/5 -/
def gov.states.wi.tax.income.credits.property_tax.rent_fraction : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 5), []⟩

/-- Wisconsin income tax has these refundable credits.
    `gov/states/wi/tax/income/credits/refundable.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1: https://www.revenue.wi.gov/TaxForms2021/2021-Form1f.pdf#page=2
    * 2021 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2021/2021-Form1-Inst.pdf#page=26
    * 2022 Wisconsin Form 1: https://www.revenue.wi.gov/TaxForms2022/2022-Form1f.pdf#page=2
    * 2022 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2022/2022-Form1-Inst.pdf#page=26
    * 2023 Wisconsin Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=18
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=16
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=26 -/
def gov.states.wi.tax.income.credits.refundable : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["wi_earned_income_credit", "wi_homestead_credit"]), []⟩

/-- Wisconsin provides this standard deduction amount before phase out.
    `gov/states/wi/tax/income/deductions/standard/max.yaml` (policyengine-us).
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/22/dt
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * 2024 Form 1 instructions, Standard Deduction Table: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=35
    * 2025 Form 1 instructions, Standard Deduction Table: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=35 -/
def gov.states.wi.tax.income.deductions.standard.max.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 14470), [(⟨2022, 1, 1⟩, 15230), (⟨2023, 1, 1⟩, 16480), (⟨2024, 1, 1⟩, 17090), (⟨2025, 1, 1⟩, 17520)]⟩
def gov.states.wi.tax.income.deductions.standard.max.JOINT : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 20730), [(⟨2022, 1, 1⟩, 21820), (⟨2023, 1, 1⟩, 23620), (⟨2024, 1, 1⟩, 24490), (⟨2025, 1, 1⟩, 25110)]⟩
def gov.states.wi.tax.income.deductions.standard.max.SEPARATE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 9850), [(⟨2022, 1, 1⟩, 10370), (⟨2023, 1, 1⟩, 11220), (⟨2024, 1, 1⟩, 11630), (⟨2025, 1, 1⟩, 11930)]⟩
def gov.states.wi.tax.income.deductions.standard.max.SINGLE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 11200), [(⟨2022, 1, 1⟩, 11790), (⟨2023, 1, 1⟩, 12760), (⟨2024, 1, 1⟩, 13230), (⟨2025, 1, 1⟩, 13560)]⟩
def gov.states.wi.tax.income.deductions.standard.max.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 20730), [(⟨2022, 1, 1⟩, 21820), (⟨2023, 1, 1⟩, 23620), (⟨2024, 1, 1⟩, 24490), (⟨2025, 1, 1⟩, 25110)]⟩

/-- Wisconsin phases out its standard deduction for head of household filers according to this schedule.
    `gov/states/wi/tax/income/deductions/standard/phase_out/head_of_household.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/22/dm -/
def gov.states.wi.tax.income.deductions.standard.phase_out.head_of_household : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 16150), [(⟨2022, 1, 1⟩, 16990), (⟨2023, 1, 1⟩, 18400), (⟨2024, 1, 1⟩, 19070), (⟨2025, 1, 1⟩, 19550)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 4503 20000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 47248), [(⟨2022, 1, 1⟩, 49705), (⟨2023, 1, 1⟩, 53778), (⟨2024, 1, 1⟩, 55779), (⟨2025, 1, 1⟩, 57210)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 3 25), []⟩⟩]⟩

/-- Wisconsin phases out its standard deduction for joint filers according to this schedule.
    `gov/states/wi/tax/income/deductions/standard/phase_out/joint.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/22/dm -/
def gov.states.wi.tax.income.deductions.standard.phase_out.joint : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 23300), [(⟨2022, 1, 1⟩, 24520), (⟨2023, 1, 1⟩, 26550), (⟨2024, 1, 1⟩, 27520), (⟨2025, 1, 1⟩, 28210)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 9889 50000), []⟩⟩]⟩

/-- Wisconsin phases out its standard deduction for separate filers according to this schedule.
    `gov/states/wi/tax/income/deductions/standard/phase_out/separate.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/22/dm -/
def gov.states.wi.tax.income.deductions.standard.phase_out.separate : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 11060), [(⟨2022, 1, 1⟩, 11640), (⟨2023, 1, 1⟩, 12600), (⟨2024, 1, 1⟩, 13060), (⟨2025, 1, 1⟩, 13390)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 9889 50000), []⟩⟩]⟩

/-- Wisconsin phases out its standard deduction for single filers according to this schedule.
    `gov/states/wi/tax/income/deductions/standard/phase_out/single.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * Wisconsin Statutes 71.07 (9)(b)(5): https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/22/dm -/
def gov.states.wi.tax.income.deductions.standard.phase_out.single : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 16150), [(⟨2022, 1, 1⟩, 16990), (⟨2023, 1, 1⟩, 18400), (⟨2024, 1, 1⟩, 19070), (⟨2025, 1, 1⟩, 19550)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 3 25), []⟩⟩]⟩

/-- Wisconsin exemption includes this base amount.
    `gov/states/wi/tax/income/exemption/base.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on WI income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=16
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=15
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=15 -/
def gov.states.wi.tax.income.exemption.base : DatedParam USD :=
  ⟨(⟨2001, 1, 1⟩, 700), []⟩

/-- Wisconsin exemption includes this amount for each elderly taxpayer.
    `gov/states/wi/tax/income/exemption/extra.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on Wisconsin income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf#page=17
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=16
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=15
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=15 -/
def gov.states.wi.tax.income.exemption.extra : DatedParam USD :=
  ⟨(⟨2001, 1, 1⟩, 250), []⟩

/-- Wisconsin gives an extra exemption to head/spouse this age or more.
    `gov/states/wi/tax/income/exemption/old_age.yaml` (policyengine-us).
    * Legislative Fiscal Bureau paper on WI income tax: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf
    * 2023 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=17
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=15
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=15 -/
def gov.states.wi.tax.income.exemption.old_age : DatedParam Rat :=
  ⟨(⟨2001, 1, 1⟩, 65), []⟩

/-- Wisconsin taxes personal income at these rates for head of household filers.
    `gov/states/wi/tax/income/rates/head_of_household.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * State of Wisconsin Department of Revenue: https://www.revenue.wi.gov/Pages/FAQS/pcs-taxrates.aspx
    * 2023 I-010 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=39
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=38
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=38 -/
def gov.states.wi.tax.income.rates.head_of_household : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 177 5000), [(⟨2023, 1, 1⟩, mkRat 7 200)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 12120), [(⟨2022, 1, 1⟩, 12760), (⟨2023, 1, 1⟩, 13810), (⟨2024, 1, 1⟩, 14320), (⟨2025, 1, 1⟩, 14680)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 93 2000), [(⟨2023, 1, 1⟩, mkRat 11 250)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 24250), [(⟨2022, 1, 1⟩, 25520), (⟨2023, 1, 1⟩, 27630), (⟨2024, 1, 1⟩, 28640), (⟨2025, 1, 1⟩, 51130)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 53 1000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 266930), [(⟨2022, 1, 1⟩, 280950), (⟨2023, 1, 1⟩, 304170), (⟨2024, 1, 1⟩, 315310), (⟨2025, 1, 1⟩, 323290)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 153 2000), []⟩⟩]⟩

/-- Wisconsin taxes personal income at these rates for joint filers.
    `gov/states/wi/tax/income/rates/joint.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * State of Wisconsin Department of Revenue: https://www.revenue.wi.gov/Pages/FAQS/pcs-taxrates.aspx
    * 2023 I-010 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=39
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=38
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=38 -/
def gov.states.wi.tax.income.rates.joint : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 177 5000), [(⟨2023, 1, 1⟩, mkRat 7 200)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 16160), [(⟨2022, 1, 1⟩, 17010), (⟨2023, 1, 1⟩, 18420), (⟨2024, 1, 1⟩, 19090), (⟨2025, 1, 1⟩, 19580)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 93 2000), [(⟨2023, 1, 1⟩, mkRat 11 250)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 32330), [(⟨2022, 1, 1⟩, 34030), (⟨2023, 1, 1⟩, 36840), (⟨2024, 1, 1⟩, 38190), (⟨2025, 1, 1⟩, 68170)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 53 1000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 355910), [(⟨2022, 1, 1⟩, 374600), (⟨2023, 1, 1⟩, 405550), (⟨2024, 1, 1⟩, 420420), (⟨2025, 1, 1⟩, 431060)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 153 2000), []⟩⟩]⟩

/-- Wisconsin taxes personal income at these rates for separate filers.
    `gov/states/wi/tax/income/rates/separate.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * State of Wisconsin Department of Revenue: https://www.revenue.wi.gov/Pages/FAQS/pcs-taxrates.aspx
    * 2023 I-010 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=39
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=38
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=38 -/
def gov.states.wi.tax.income.rates.separate : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 177 5000), [(⟨2023, 1, 1⟩, mkRat 7 200)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 8080), [(⟨2022, 1, 1⟩, 8510), (⟨2023, 1, 1⟩, 9210), (⟨2024, 1, 1⟩, 9550), (⟨2025, 1, 1⟩, 9790)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 93 2000), [(⟨2023, 1, 1⟩, mkRat 11 250)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 16160), [(⟨2022, 1, 1⟩, 17010), (⟨2023, 1, 1⟩, 18420), (⟨2024, 1, 1⟩, 19090), (⟨2025, 1, 1⟩, 34090)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 53 1000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 177960), [(⟨2022, 1, 1⟩, 187300), (⟨2023, 1, 1⟩, 202780), (⟨2024, 1, 1⟩, 210210), (⟨2025, 1, 1⟩, 215530)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 153 2000), []⟩⟩]⟩

/-- Wisconsin taxes personal income at these rates for single filers.
    `gov/states/wi/tax/income/rates/single.yaml` (policyengine-us).
    * Wisconsin Tax Brackets, Rates, Forms, and Standard Deductions: https://www.efile.com/wisconsin-tax-brackets-rates-and-forms/
    * State of Wisconsin Department of Revenue: https://www.revenue.wi.gov/Pages/FAQS/pcs-taxrates.aspx
    * 2023 I-010 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2023/2023-Form1-Inst.pdf#page=39
    * 2024 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2024/2024-Form1-inst.pdf#page=38
    * 2025 Form 1 instructions: https://www.revenue.wi.gov/TaxForms2025/2025-Form1-inst.pdf#page=38 -/
def gov.states.wi.tax.income.rates.single : Scale :=
  ⟨[⟨⟨(⟨2021, 1, 1⟩, 0), []⟩, ⟨(⟨2021, 1, 1⟩, mkRat 177 5000), [(⟨2023, 1, 1⟩, mkRat 7 200)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 12120), [(⟨2022, 1, 1⟩, 12760), (⟨2023, 1, 1⟩, 13810), (⟨2024, 1, 1⟩, 14320), (⟨2025, 1, 1⟩, 14680)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 93 2000), [(⟨2023, 1, 1⟩, mkRat 11 250)]⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 24250), [(⟨2022, 1, 1⟩, 25520), (⟨2023, 1, 1⟩, 27630), (⟨2024, 1, 1⟩, 28640), (⟨2025, 1, 1⟩, 51130)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 53 1000), []⟩⟩,
    ⟨⟨(⟨2021, 1, 1⟩, 266930), [(⟨2022, 1, 1⟩, 280950), (⟨2023, 1, 1⟩, 304170), (⟨2024, 1, 1⟩, 315310), (⟨2025, 1, 1⟩, 323290)]⟩, ⟨(⟨2021, 1, 1⟩, mkRat 153 2000), []⟩⟩]⟩

/-- Wisconsin subtracts from AGI this fraction of long-term capital gains.
    `gov/states/wi/tax/income/subtractions/capital_gain/fraction.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1, Schedule WD, Line 25: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleWDf.pdf#page=2
    * 2022 Wisconsin Form 1, Schedule WD, Line 25: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleWDf.pdf#page=2
    * 2023 Wisconsin Form 1, Schedule WD: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleWD-Inst.pdf#page=1
    * 2024 Wisconsin Form 1 Schedule WD, Line 25: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWDf.pdf#page=2
    * 2025 Wisconsin Form 1 Schedule WD, Line 25: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleWDf.pdf#page=2 -/
def gov.states.wi.tax.income.subtractions.capital_gain.fraction : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 3 10), []⟩

/-- Wisconsin subtracts from AGI this maximum of child and dependent care expenses per dependent.
    `gov/states/wi/tax/income/subtractions/childcare_expense/max_amount.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=7
    * 2024 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWI-2441-Inst.pdf#page=5
    * 2025 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleWI-2441-Inst.pdf#page=5 -/
def gov.states.wi.tax.income.subtractions.childcare_expense.max_amount : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3000), []⟩

/-- Wisconsin recognizes this maximum number of dependents as eligible for care expense AGI subtraction.
    `gov/states/wi/tax/income/subtractions/childcare_expense/max_dependents.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=7
    * 2024 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleWI-2441-Inst.pdf#page=5
    * 2025 Schedule WI-2441 Instructions - Additional Child and Dependent Care Credit: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleWI-2441-Inst.pdf#page=5 -/
def gov.states.wi.tax.income.subtractions.childcare_expense.max_dependents : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 2), []⟩

/-- Wisconsin caps the 529 plan contributions deduction per beneficiary at this amount. The married filing separately cap is half the regular cap.
    `gov/states/wi/tax/income/subtractions/plan_529/cap.yaml` (policyengine-us).
    * Edvest 529 Tax Benefits: https://www.edvest.com/learn/tax-benefits/
    * DFI Wisconsin 529 College Savings Program: https://dfi.wi.gov/Pages/EducationalServices/CollegeSavingsCareerPlanning/CollegeSavingsProgram.aspx -/
def gov.states.wi.tax.income.subtractions.plan_529.cap.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3560), [(⟨2024, 1, 1⟩, 5000), (⟨2025, 1, 1⟩, 5130), (⟨2026, 1, 1⟩, 5280)]⟩
def gov.states.wi.tax.income.subtractions.plan_529.cap.JOINT : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3560), [(⟨2024, 1, 1⟩, 5000), (⟨2025, 1, 1⟩, 5130), (⟨2026, 1, 1⟩, 5280)]⟩
def gov.states.wi.tax.income.subtractions.plan_529.cap.SEPARATE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 1780), [(⟨2024, 1, 1⟩, 2500), (⟨2025, 1, 1⟩, 2560), (⟨2026, 1, 1⟩, 2640)]⟩
def gov.states.wi.tax.income.subtractions.plan_529.cap.SINGLE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3560), [(⟨2024, 1, 1⟩, 5000), (⟨2025, 1, 1⟩, 5130), (⟨2026, 1, 1⟩, 5280)]⟩
def gov.states.wi.tax.income.subtractions.plan_529.cap.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 3560), [(⟨2024, 1, 1⟩, 5000), (⟨2025, 1, 1⟩, 5130), (⟨2026, 1, 1⟩, 5280)]⟩

/-- Wisconsin retirement income exclusion applies if this is true.
    `gov/states/wi/tax/income/subtractions/retirement_income/exclusion/in_effect.yaml` (policyengine-us).
    * Wis. Stat. 71.05(6)(b)54m.a: https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/6/b/54m/a
    * 2025 Wisconsin Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.exclusion.in_effect : DatedParam Bool :=
  ⟨(⟨2021, 1, 1⟩, false), [(⟨2025, 1, 1⟩, true)]⟩

/-- Wisconsin limits the joint retirement income exclusion to this amount when both spouses are age-eligible.
    `gov/states/wi/tax/income/subtractions/retirement_income/exclusion/max_amount/joint.yaml` (policyengine-us).
    * Wis. Stat. 71.05(6)(b)54m.a: https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/6/b/54m/a
    * 2025 Wisconsin Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.exclusion.max_amount.joint : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 48000), []⟩

/-- Wisconsin limits the retirement income exclusion to this amount per eligible individual.
    `gov/states/wi/tax/income/subtractions/retirement_income/exclusion/max_amount/single.yaml` (policyengine-us).
    * Wis. Stat. 71.05(6)(b)54m.a: https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/6/b/54m/a
    * 2025 Wisconsin Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.exclusion.max_amount.single : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 24000), []⟩

/-- Wisconsin sets this age as the minimum for the retirement income exclusion.
    `gov/states/wi/tax/income/subtractions/retirement_income/exclusion/min_age.yaml` (policyengine-us).
    * Wis. Stat. 71.05(6)(b)54m.a: https://docs.legis.wisconsin.gov/statutes/statutes/71/i/05/6/b/54m/a
    * 2025 Wisconsin Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.exclusion.min_age : DatedParam Rat :=
  ⟨(⟨2025, 1, 1⟩, 67), []⟩

/-- Wisconsin limits eligibility for retirement income subtraction to this maximum federal AGI.
    `gov/states/wi/tax/income/subtractions/retirement_income/max_agi.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions, Line 17: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=9
    * 2022 Wisconsin Form 1 Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=7
    * 2023 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleSB-Inst.pdf#page=7
    * 2024 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.max_agi.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 15000), []⟩
def gov.states.wi.tax.income.subtractions.retirement_income.max_agi.JOINT : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 30000), []⟩
def gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SEPARATE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 15000), []⟩
def gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SINGLE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 15000), []⟩
def gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 15000), []⟩

/-- Wisconsin limits retirement income AGI subtraction to this maximum per person.
    `gov/states/wi/tax/income/subtractions/retirement_income/max_amount.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions, Line 17: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=9
    * 2022 Wisconsin Form 1 Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=7
    * 2023 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleSB-Inst.pdf#page=7
    * 2024 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.max_amount : DatedParam USD :=
  ⟨(⟨2021, 1, 1⟩, 5000), []⟩

/-- Wisconsin limits its retirement income subtraction to filers this age or older.
    `gov/states/wi/tax/income/subtractions/retirement_income/min_age.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions, Line 17: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=9
    * 2022 Wisconsin Form 1 Schedule SB instructions, Line 16: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf#page=7
    * 2023 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2023/2023-ScheduleSB-Inst.pdf#page=7
    * 2024 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleSB-Inst.pdf#page=7 -/
def gov.states.wi.tax.income.subtractions.retirement_income.min_age : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 65), []⟩

/-- Wisconsin subtracts these variables from US adjusted gross income when computing its gross income.
    `gov/states/wi/tax/income/subtractions/sources.yaml` (policyengine-us).
    * 2021 WI schedule SB: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSBf.pdf
    * 2021 WI schedule SB instructions: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-Inst.pdf
    * 2022 WI schedule SB: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleSBf.pdf
    * 2022 WI schedule SB instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleSB-Inst.pdf
    * 2024 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleSB-Inst.pdf
    * 2025 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-inst.pdf -/
def gov.states.wi.tax.income.subtractions.sources : DatedParam (List String) :=
  ⟨(⟨2021, 1, 1⟩, ["wi_unemployment_compensation_subtraction", "tax_unit_taxable_social_security", "wi_capital_gain_loss_subtraction", "wi_childcare_expense_subtraction", "wi_retirement_income_subtraction", "us_govt_interest", "wi_529_plan_deduction"]), [(⟨2022, 1, 1⟩, ["wi_unemployment_compensation_subtraction", "tax_unit_taxable_social_security", "wi_capital_gain_loss_subtraction", "wi_retirement_income_subtraction", "us_govt_interest", "wi_529_plan_deduction"])]⟩

/-- `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/base.yaml` (policyengine-us). -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.base.SINGLE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 12000), []⟩

/-- `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/base.yaml` (policyengine-us). -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.base.JOINT : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 18000), []⟩

/-- `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/base.yaml` (policyengine-us). -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.base.SURVIVING_SPOUSE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 18000), []⟩

/-- `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/base.yaml` (policyengine-us). -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.base.SEPARATE : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 12000), []⟩

/-- `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/base.yaml` (policyengine-us). -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.base.HEAD_OF_HOUSEHOLD : DatedParam Rat :=
  ⟨(⟨2021, 1, 1⟩, 12000), []⟩

/-- Wisconsin uses this rate to phase-out income in calculation of unemployment compensation subtraction.
    `gov/states/wi/tax/income/subtractions/unemployment_compensation/income_phase_out/rate.yaml` (policyengine-us).
    * 2021 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2021/2021-ScheduleSB-inst.pdf#page=2
    * 2022 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2022/2022-ScheduleSB-Inst.pdf#page=1
    * 2024 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2024/2024-ScheduleSB-Inst.pdf#page=2
    * 2025 Wisconsin Form 1 Schedule SB instructions: https://www.revenue.wi.gov/TaxForms2025/2025-ScheduleSB-inst.pdf#page=2 -/
def gov.states.wi.tax.income.subtractions.unemployment_compensation.income_phase_out.rate : DatedParam Rate :=
  ⟨(⟨2021, 1, 1⟩, mkRat 1 2), []⟩

/-- Default employer-side unemployment insurance tax rate for Wisconsin.
    `gov/states/wi/tax/payroll/unemployment/default_rate.yaml` (policyengine-us).
    * Wisconsin Statutes Section 108.18: https://docs.legis.wisconsin.gov/statutes/statutes/108/18
    * Tax Measures of State Unemployment Insurance Tax Systems, CY 2024: https://oui.doleta.gov/unemploy/pdf/sigmeasures/sigmeasuitaxsys24.pdf#page=61 -/
def gov.states.wi.tax.payroll.unemployment.default_rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 1 40), []⟩

/-- Employer-side unemployment insurance taxable wage base for Wisconsin.
    `gov/states/wi/tax/payroll/unemployment/taxable_wage_base.yaml` (policyengine-us).
    * Wisconsin Statutes Section 108.02(26): https://docs.legis.wisconsin.gov/statutes/statutes/108/02/26
    * Tax Measures of State Unemployment Insurance Tax Systems, CY 2024: https://oui.doleta.gov/unemploy/pdf/sigmeasures/sigmeasuitaxsys24.pdf#page=61 -/
def gov.states.wi.tax.payroll.unemployment.taxable_wage_base : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 14000), []⟩

end Lawlib.Gen.Params
