/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Parameters
open Lawlib

/-- The US caps high-efficiency home program rebates at this amount per year for heat pump
    clothes dryers.
    `gov/doe/high_efficiency_electric_home_rebate/cap/electric_heat_pump_clothes_dryer.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.electric_heat_pump_clothes_dryer : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 840), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for electric load
    service center upgrades.
    `gov/doe/high_efficiency_electric_home_rebate/cap/electric_load_service_center_upgrade.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.electric_load_service_center_upgrade : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 4000), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for electric
    stoves, cooktops, ranges, or ovens.
    `gov/doe/high_efficiency_electric_home_rebate/cap/electric_stove_cooktop_range_or_oven.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.electric_stove_cooktop_range_or_oven : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 840), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for electric
    wiring.
    `gov/doe/high_efficiency_electric_home_rebate/cap/electric_wiring.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.electric_wiring : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 2500), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for heat pumps.
    `gov/doe/high_efficiency_electric_home_rebate/cap/heat_pump.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.heat_pump : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 8000), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for heat pump water
    heaters.
    `gov/doe/high_efficiency_electric_home_rebate/cap/heat_pump_water_heater.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=596 -/
def doe.high_efficiency_electric_home_rebate.cap.heat_pump_water_heater : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 1750), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for insulation, air
    sealing, and ventilation.
    `gov/doe/high_efficiency_electric_home_rebate/cap/insulation_air_sealing_ventilation.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.insulation_air_sealing_ventilation : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 1600), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US caps high-efficiency home program rebates at this amount per year for appliance and
    non-appliance upgrades.
    `gov/doe/high_efficiency_electric_home_rebate/cap/total.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=597 -/
def doe.high_efficiency_electric_home_rebate.cap.total : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), [(⟨2023, 1, 1⟩, 14000), (⟨2032, 1, 1⟩, 0)]⟩

/-- The US covers this percentage of expenditures for its high-efficiency electric home program
    rebate program, based on a household's ratio of income to area median income
    `gov/doe/high_efficiency_electric_home_rebate/elements.yaml` (policyengine-us).
    * Inflation Reduction Act:
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=598 -/
def doe.high_efficiency_electric_home_rebate.elements : DatedParam (List String) :=
  ⟨(⟨0, 1, 1⟩, []),
    [(⟨2023, 1, 1⟩, ["electric_heat_pump_clothes_dryer",
      "electric_load_service_center_upgrade",
      "electric_stove_cooktop_range_or_oven",
      "electric_wiring",
      "heat_pump_water_heater",
      "heat_pump",
      "insulation_air_sealing_ventilation"]),
     (⟨2032, 1, 1⟩, [])]⟩

/-- The US covers this percentage of expenditures for its high-efficiency electric home program
    rebate program, based on a household's ratio of income to area median income
    `gov/doe/high_efficiency_electric_home_rebate/percent_covered.yaml` (policyengine-us).
    * Inflation Reduction Act:
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=598 -/
def doe.high_efficiency_electric_home_rebate.percent_covered : ScaleX :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, .negInf), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 1)]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 4 5)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin (mkRat 1 2))]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 3 2)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 0)]⟩⟩]⟩

/-- The US caps residential efficiency and electrification program rebates at this amount per
    year for retrofits achieving at least the high threshold of energy savings, by income-AMI
    ratio.
    `gov/doe/residential_efficiency_electrification_rebate/cap/high.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.cap.high : ScaleX :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, .negInf), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 8000),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 4 5)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 4000),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩]⟩

/-- The US caps residential efficiency and electrification program rebates at this amount per
    one-percent reduction of the state's average home energy usage, per year, for retrofits
    achieving low energy savings, by income AMI ratio.
    `gov/doe/residential_efficiency_electrification_rebate/cap/low.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.cap.low : ScaleX :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, .negInf), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 200),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 4 5)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 100),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩]⟩

/-- The US caps residential efficiency and electrification program rebates at this amount per
    year for retrofits achieving between the medium and high thresholds of energy savings, by
    income-AMI ratio.
    `gov/doe/residential_efficiency_electrification_rebate/cap/medium.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.cap.medium : ScaleX :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, .negInf), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 4000),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 4 5)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin 2000),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩]⟩

/-- The US caps projects costs residential efficiency and electrification program rebates at
    this percentage per year for for retrofits by income AMI ratio.
    `gov/doe/residential_efficiency_electrification_rebate/percent.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.percent : ScaleX :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, .negInf), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin (mkRat 4 5)),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, .fin (mkRat 4 5)), []⟩, ⟨(⟨0, 1, 1⟩, .fin 0), [(⟨2023, 1, 1⟩, .fin (mkRat 1 2)),
    (⟨2031, 10, 1⟩, .fin 0)]⟩⟩]⟩

/-- The US limits high residential efficiency and electrification rebates to retrofits achieving
    at least this percentage of modeled energy savings.
    `gov/doe/residential_efficiency_electrification_rebate/threshold/high.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.threshold.high : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 7 20), []⟩

/-- The US limits residential efficiency and electrification rebates to retrofits achieving at
    least this percentage of modeled energy savings.
    `gov/doe/residential_efficiency_electrification_rebate/threshold/low.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.threshold.low : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 3 20), []⟩

/-- The US limits medium residential efficiency and electrification rebates to retrofits
    achieving at least this percentage of modeled energy savings.
    `gov/doe/residential_efficiency_electrification_rebate/threshold/medium.yaml` (policyengine-us).
    * Inflation Reduction Act, part 2, Section 50121 (c):
      https://www.democrats.senate.gov/imo/media/doc/inflation_reduction_act_of_2022.pdf#page=587 -/
def doe.residential_efficiency_electrification_rebate.threshold.medium : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 1 5), []⟩

end Lawlib.Parameters
