/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Parameters
open Lawlib

/-- The Social Security Administration calculates the National Average Wage Index.
    `gov/ssa/nawi.yaml` (policyengine-us).
    * Social Security National Average Wage Index:
      https://www.ssa.gov/oact/cola/AWI.html#Series -/
def ssa.nawi : DatedParam USD :=
  ⟨(⟨1951, 1, 1⟩, mkRat 69979 25),
    [(⟨1952, 1, 1⟩, mkRat 74333 25),
     (⟨1953, 1, 1⟩, mkRat 78486 25),
     (⟨1954, 1, 1⟩, mkRat 78891 25),
     (⟨1955, 1, 1⟩, mkRat 82536 25),
     (⟨1956, 1, 1⟩, mkRat 88309 25),
     (⟨1957, 1, 1⟩, mkRat 91043 25),
     (⟨1958, 1, 1⟩, mkRat 18369 5),
     (⟨1959, 1, 1⟩, mkRat 19279 5),
     (⟨1960, 1, 1⟩, mkRat 100178 25),
     (⟨1961, 1, 1⟩, mkRat 102169 25),
     (⟨1962, 1, 1⟩, mkRat 21457 5),
     (⟨1963, 1, 1⟩, mkRat 109916 25),
     (⟨1964, 1, 1⟩, mkRat 114408 25),
     (⟨1965, 1, 1⟩, mkRat 116468 25),
     (⟨1966, 1, 1⟩, mkRat 123459 25),
     (⟨1967, 1, 1⟩, mkRat 130336 25),
     (⟨1968, 1, 1⟩, mkRat 139294 25),
     (⟨1969, 1, 1⟩, mkRat 147344 25),
     (⟨1970, 1, 1⟩, mkRat 154656 25),
     (⟨1971, 1, 1⟩, mkRat 162427 25),
     (⟨1972, 1, 1⟩, mkRat 35669 5),
     (⟨1973, 1, 1⟩, mkRat 189504 25),
     (⟨1974, 1, 1⟩, mkRat 200769 25),
     (⟨1975, 1, 1⟩, mkRat 215773 25),
     (⟨1976, 1, 1⟩, mkRat 230662 25),
     (⟨1977, 1, 1⟩, mkRat 244486 25),
     (⟨1978, 1, 1⟩, mkRat 1055603 100),
     (⟨1979, 1, 1⟩, mkRat 573973 50),
     (⟨1980, 1, 1⟩, mkRat 625673 50),
     (⟨1981, 1, 1⟩, mkRat 137731 10),
     (⟨1982, 1, 1⟩, mkRat 726567 50),
     (⟨1983, 1, 1⟩, mkRat 380981 25),
     (⟨1984, 1, 1⟩, mkRat 1613507 100),
     (⟨1985, 1, 1⟩, mkRat 1682251 100),
     (⟨1986, 1, 1⟩, mkRat 866091 50),
     (⟨1987, 1, 1⟩, mkRat 1842651 100),
     (⟨1988, 1, 1⟩, mkRat 483351 25),
     (⟨1989, 1, 1⟩, mkRat 401991 20),
     (⟨1990, 1, 1⟩, mkRat 1051399 50),
     (⟨1991, 1, 1⟩, mkRat 109058 5),
     (⟨1992, 1, 1⟩, mkRat 1146771 50),
     (⟨1993, 1, 1⟩, mkRat 2313267 100),
     (⟨1994, 1, 1⟩, mkRat 2375353 100),
     (⟨1995, 1, 1⟩, mkRat 1235283 50),
     (⟨1996, 1, 1⟩, mkRat 259139 10),
     (⟨1997, 1, 1⟩, 27426),
     (⟨1998, 1, 1⟩, mkRat 721536 25),
     (⟨1999, 1, 1⟩, mkRat 761746 25),
     (⟨2000, 1, 1⟩, mkRat 1607741 50),
     (⟨2001, 1, 1⟩, mkRat 823048 25),
     (⟨2002, 1, 1⟩, mkRat 3325209 100),
     (⟨2003, 1, 1⟩, mkRat 681299 20),
     (⟨2004, 1, 1⟩, mkRat 712971 20),
     (⟨2005, 1, 1⟩, mkRat 1847647 50),
     (⟨2006, 1, 1⟩, mkRat 3865141 100),
     (⟨2007, 1, 1⟩, mkRat 1010137 25),
     (⟨2008, 1, 1⟩, mkRat 4133497 100),
     (⟨2009, 1, 1⟩, mkRat 4071161 100),
     (⟨2010, 1, 1⟩, mkRat 4167383 100),
     (⟨2011, 1, 1⟩, mkRat 4297961 100),
     (⟨2012, 1, 1⟩, mkRat 4432167 100),
     (⟨2013, 1, 1⟩, mkRat 1122204 25),
     (⟨2014, 1, 1⟩, mkRat 1162038 25),
     (⟨2015, 1, 1⟩, mkRat 4809863 100),
     (⟨2016, 1, 1⟩, mkRat 972843 20),
     (⟨2017, 1, 1⟩, mkRat 5032189 100),
     (⟨2018, 1, 1⟩, mkRat 260729 5),
     (⟨2019, 1, 1⟩, mkRat 5409999 100),
     (⟨2020, 1, 1⟩, mkRat 278143 5),
     (⟨2021, 1, 1⟩, mkRat 6057507 100),
     (⟨2022, 1, 1⟩, mkRat 6379513 100),
     (⟨2023, 1, 1⟩, mkRat 333109 5),
     (⟨2024, 1, 1⟩, mkRat 6984657 100),
     (⟨2025, 1, 1⟩, mkRat 728913 10),
     (⟨2026, 1, 1⟩, mkRat 7516861 100),
     (⟨2027, 1, 1⟩, mkRat 7812471 100),
     (⟨2028, 1, 1⟩, mkRat 405404 5),
     (⟨2029, 1, 1⟩, mkRat 4207467 50),
     (⟨2030, 1, 1⟩, mkRat 1741811 20),
     (⟨2031, 1, 1⟩, mkRat 2250794 25),
     (⟨2032, 1, 1⟩, mkRat 4654447 50),
     (⟨2033, 1, 1⟩, mkRat 2406464 25),
     (⟨2034, 1, 1⟩, mkRat 4976803 50),
     (⟨2035, 1, 1⟩, mkRat 10292073 100)]⟩

/-- Share of gross SS benefits whose taxation is credited to OASDI trust funds.
    `gov/ssa/revenue/oasdi_share_of_gross_ss.yaml` (policyengine-us).
    * PL 98-21 Section 121(e)(1) - Trust fund appropriations:
      https://www.congress.gov/bill/98th-congress/house-bill/1900
    * OBRA 1993 Section 13215(c) - Medicare HI allocation:
      https://www.congress.gov/bill/103rd-congress/house-bill/2264 -/
def ssa.revenue.oasdi_share_of_gross_ss : DatedParam Rate :=
  ⟨(⟨1984, 1, 1⟩, mkRat 1 2), []⟩

/-- The Social Security Administration considers blind individuals earning more than this
    amount, net of impairment-related work expenses, to be engaging in Substantial Gainful
    Activity.
    `gov/ssa/sga/blind.yaml` (policyengine-us).
    * Substantial Gainful Activity:
      https://www.ssa.gov/oact/cola/sga.html
    * 416.974. Evaluation guides if you are an employee (b)(2)(ii)(B):
      https://www.ssa.gov/OP_Home/cfr20/416/416-0974.htm -/
def ssa.sga.blind : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 200),
    [(⟨1976, 1, 1⟩, 230),
     (⟨1977, 1, 1⟩, 240),
     (⟨1978, 1, 1⟩, 334),
     (⟨1979, 1, 1⟩, 375),
     (⟨1980, 1, 1⟩, 417),
     (⟨1981, 1, 1⟩, 459),
     (⟨1982, 1, 1⟩, 500),
     (⟨1983, 1, 1⟩, 550),
     (⟨1984, 1, 1⟩, 580),
     (⟨1985, 1, 1⟩, 610),
     (⟨1986, 1, 1⟩, 650),
     (⟨1987, 1, 1⟩, 680),
     (⟨1988, 1, 1⟩, 700),
     (⟨1989, 1, 1⟩, 740),
     (⟨1990, 1, 1⟩, 780),
     (⟨1991, 1, 1⟩, 810),
     (⟨1992, 1, 1⟩, 850),
     (⟨1993, 1, 1⟩, 880),
     (⟨1994, 1, 1⟩, 930),
     (⟨1995, 1, 1⟩, 940),
     (⟨1996, 1, 1⟩, 960),
     (⟨1997, 1, 1⟩, 1000),
     (⟨1998, 1, 1⟩, 1050),
     (⟨1999, 1, 1⟩, 1110),
     (⟨2000, 1, 1⟩, 1170),
     (⟨2001, 1, 1⟩, 1240),
     (⟨2002, 1, 1⟩, 1300),
     (⟨2003, 1, 1⟩, 1330),
     (⟨2004, 1, 1⟩, 1350),
     (⟨2005, 1, 1⟩, 1380),
     (⟨2006, 1, 1⟩, 1450),
     (⟨2007, 1, 1⟩, 1500),
     (⟨2008, 1, 1⟩, 1570),
     (⟨2009, 1, 1⟩, 1640),
     (⟨2010, 1, 1⟩, 1640),
     (⟨2011, 1, 1⟩, 1640),
     (⟨2012, 1, 1⟩, 1690),
     (⟨2013, 1, 1⟩, 1740),
     (⟨2014, 1, 1⟩, 1800),
     (⟨2015, 1, 1⟩, 1820),
     (⟨2016, 1, 1⟩, 1820),
     (⟨2017, 1, 1⟩, 1950),
     (⟨2018, 1, 1⟩, 1970),
     (⟨2019, 1, 1⟩, 2040),
     (⟨2020, 1, 1⟩, 2110),
     (⟨2021, 1, 1⟩, 2190),
     (⟨2022, 1, 1⟩, 2260),
     (⟨2023, 1, 1⟩, 2460),
     (⟨2024, 1, 1⟩, 2590),
     (⟨2025, 1, 1⟩, 2700),
     (⟨2026, 1, 1⟩, 2830)]⟩

/-- The Social Security Administration considers non-blind individuals earning more than this
    amount, net of impairment-related work expenses, to be engaging in Substantial Gainful
    Activity.
    `gov/ssa/sga/non_blind.yaml` (policyengine-us).
    * Substantial Gainful Activity:
      https://www.ssa.gov/oact/cola/sga.html
    * 416.974. Evaluation guides if you are an employee (b)(2)(ii)(B):
      https://www.ssa.gov/OP_Home/cfr20/416/416-0974.htm -/
def ssa.sga.non_blind : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 200),
    [(⟨1976, 1, 1⟩, 230),
     (⟨1977, 1, 1⟩, 240),
     (⟨1978, 1, 1⟩, 260),
     (⟨1979, 1, 1⟩, 280),
     (⟨1980, 1, 1⟩, 300),
     (⟨1990, 1, 1⟩, 500),
     (⟨1999, 1, 1⟩, 700),
     (⟨2001, 1, 1⟩, 740),
     (⟨2002, 1, 1⟩, 780),
     (⟨2003, 1, 1⟩, 800),
     (⟨2004, 1, 1⟩, 810),
     (⟨2005, 1, 1⟩, 830),
     (⟨2006, 1, 1⟩, 860),
     (⟨2007, 1, 1⟩, 900),
     (⟨2008, 1, 1⟩, 940),
     (⟨2009, 1, 1⟩, 980),
     (⟨2010, 1, 1⟩, 1000),
     (⟨2012, 1, 1⟩, 1010),
     (⟨2013, 1, 1⟩, 1040),
     (⟨2014, 1, 1⟩, 1070),
     (⟨2015, 1, 1⟩, 1090),
     (⟨2016, 1, 1⟩, 1130),
     (⟨2017, 1, 1⟩, 1170),
     (⟨2018, 1, 1⟩, 1180),
     (⟨2019, 1, 1⟩, 1220),
     (⟨2020, 1, 1⟩, 1260),
     (⟨2021, 1, 1⟩, 1310),
     (⟨2022, 1, 1⟩, 1350),
     (⟨2023, 1, 1⟩, 1470),
     (⟨2024, 1, 1⟩, 1550),
     (⟨2025, 1, 1⟩, 1620),
     (⟨2026, 1, 1⟩, 1690)]⟩

/-- Age at which Social Security indexes wages for AIME calculation.
    `gov/ssa/social_security/aime/indexing_age.yaml` (policyengine-us).
    * 42 U.S.C. § 415(b)(3)(A):
      https://www.law.cornell.edu/uscode/text/42/415#b_3_A
    * Social Security POMS RS 00605.020:
      https://secure.ssa.gov/poms.nsf/lnx/0300605020
    * SSA AIME Calculation:
      https://www.ssa.gov/OACT/COLA/aime.html -/
def ssa.social_security.aime.indexing_age : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 60), []⟩

/-- Maximum age for which Social Security counts earnings toward AIME calculation.
    `gov/ssa/social_security/aime/max_earnings_age.yaml` (policyengine-us).
    * 42 U.S.C. § 415(b)(2)(A):
      https://www.law.cornell.edu/uscode/text/42/415#b_2_A
    * 20 CFR § 404.211(a)(1):
      https://www.law.cornell.edu/cfr/text/20/404.211
    * Social Security POMS RS 00605.022:
      https://secure.ssa.gov/poms.nsf/lnx/0300605022 -/
def ssa.social_security.aime.max_earnings_age : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 62), []⟩

/-- Minimum age at which Social Security counts substantial earnings for AIME calculation.
    `gov/ssa/social_security/aime/minimum_age_for_earnings.yaml` (policyengine-us).
    * 42 U.S.C. § 415(b)(2)(B)(ii):
      https://www.law.cornell.edu/uscode/text/42/415#b_2_B_ii
    * 20 CFR § 404.211(b):
      https://www.law.cornell.edu/cfr/text/20/404.211
    * Social Security POMS RS 00605.022:
      https://secure.ssa.gov/poms.nsf/lnx/0300605022 -/
def ssa.social_security.aime.minimum_age_for_earnings : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 22), []⟩

/-- Number of months per year Social Security uses for AIME calculation.
    `gov/ssa/social_security/aime/months_per_year.yaml` (policyengine-us).
    * 42 U.S.C. § 415(b)(1):
      https://www.law.cornell.edu/uscode/text/42/415#b_1
    * Social Security POMS RS 00605.005:
      https://secure.ssa.gov/poms.nsf/lnx/0300605005 -/
def ssa.social_security.aime.months_per_year : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 12), []⟩

/-- Number of highest earning years Social Security uses in AIME calculation.
    `gov/ssa/social_security/aime/years_of_earnings.yaml` (policyengine-us).
    * 42 U.S.C. § 415(b)(1):
      https://www.law.cornell.edu/uscode/text/42/415#b_1
    * 20 CFR § 404.211(a):
      https://www.law.cornell.edu/cfr/text/20/404.211
    * Social Security POMS RS 00605.017:
      https://secure.ssa.gov/poms.nsf/lnx/0300605017 -/
def ssa.social_security.aime.years_of_earnings : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 35), []⟩

/-- The US reduces benefits if earnings exceed this amount for beneficiaries under full
    retirement age.
    `gov/ssa/social_security/earnings_test/exempt_amount_under_fra.yaml` (policyengine-us).
    * 42 U.S.C. § 403(f)(8)(B):
      https://www.law.cornell.edu/uscode/text/42/403#f_8_B
    * 20 CFR § 404.430:
      https://www.law.cornell.edu/cfr/text/20/404.430
    * Social Security Retirement Earnings Test Exempt Amounts:
      https://www.ssa.gov/OACT/COLA/rtea.html -/
def ssa.social_security.earnings_test.exempt_amount_under_fra : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 2520),
    [(⟨1976, 1, 1⟩, 2760),
     (⟨1977, 1, 1⟩, 3000),
     (⟨1978, 1, 1⟩, 3240),
     (⟨1979, 1, 1⟩, 3480),
     (⟨1980, 1, 1⟩, 3720),
     (⟨1981, 1, 1⟩, 4080),
     (⟨1982, 1, 1⟩, 4440),
     (⟨1983, 1, 1⟩, 4920),
     (⟨1984, 1, 1⟩, 5160),
     (⟨1985, 1, 1⟩, 5400),
     (⟨1986, 1, 1⟩, 5760),
     (⟨1987, 1, 1⟩, 6000),
     (⟨1988, 1, 1⟩, 6120),
     (⟨1989, 1, 1⟩, 6480),
     (⟨1990, 1, 1⟩, 6840),
     (⟨1991, 1, 1⟩, 7080),
     (⟨1992, 1, 1⟩, 7440),
     (⟨1993, 1, 1⟩, 7680),
     (⟨1994, 1, 1⟩, 8040),
     (⟨1995, 1, 1⟩, 8160),
     (⟨1996, 1, 1⟩, 8280),
     (⟨1997, 1, 1⟩, 8640),
     (⟨1998, 1, 1⟩, 9120),
     (⟨1999, 1, 1⟩, 9600),
     (⟨2000, 1, 1⟩, 10080),
     (⟨2001, 1, 1⟩, 10680),
     (⟨2002, 1, 1⟩, 11280),
     (⟨2003, 1, 1⟩, 11520),
     (⟨2004, 1, 1⟩, 11640),
     (⟨2005, 1, 1⟩, 12000),
     (⟨2006, 1, 1⟩, 12480),
     (⟨2007, 1, 1⟩, 12960),
     (⟨2008, 1, 1⟩, 13560),
     (⟨2009, 1, 1⟩, 14160),
     (⟨2010, 1, 1⟩, 14160),
     (⟨2011, 1, 1⟩, 14160),
     (⟨2012, 1, 1⟩, 14640),
     (⟨2013, 1, 1⟩, 15120),
     (⟨2014, 1, 1⟩, 15480),
     (⟨2015, 1, 1⟩, 15720),
     (⟨2016, 1, 1⟩, 15720),
     (⟨2017, 1, 1⟩, 16920),
     (⟨2018, 1, 1⟩, 17040),
     (⟨2019, 1, 1⟩, 17640),
     (⟨2020, 1, 1⟩, 18240),
     (⟨2021, 1, 1⟩, 18960),
     (⟨2022, 1, 1⟩, 19560),
     (⟨2023, 1, 1⟩, 21240),
     (⟨2024, 1, 1⟩, 22320),
     (⟨2025, 1, 1⟩, 23400),
     (⟨2026, 1, 1⟩, 24480)]⟩

/-- The US applies a higher exempt amount in the year a person reaches full retirement age.
    `gov/ssa/social_security/earnings_test/exempt_amount_year_of_fra.yaml` (policyengine-us).
    * 42 U.S.C. § 403(f)(8)(D):
      https://www.law.cornell.edu/uscode/text/42/403#f_8_D
    * 20 CFR § 404.430:
      https://www.law.cornell.edu/cfr/text/20/404.430
    * Social Security Retirement Earnings Test Exempt Amounts:
      https://www.ssa.gov/OACT/COLA/rtea.html -/
def ssa.social_security.earnings_test.exempt_amount_year_of_fra : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 2520),
    [(⟨1976, 1, 1⟩, 2760),
     (⟨1977, 1, 1⟩, 3000),
     (⟨1978, 1, 1⟩, 3240),
     (⟨1979, 1, 1⟩, 3480),
     (⟨1980, 1, 1⟩, 3720),
     (⟨1981, 1, 1⟩, 4080),
     (⟨1982, 1, 1⟩, 4440),
     (⟨1983, 1, 1⟩, 4920),
     (⟨1984, 1, 1⟩, 5160),
     (⟨1985, 1, 1⟩, 5400),
     (⟨1986, 1, 1⟩, 5760),
     (⟨1987, 1, 1⟩, 6000),
     (⟨1988, 1, 1⟩, 6120),
     (⟨1989, 1, 1⟩, 6480),
     (⟨1990, 1, 1⟩, 6840),
     (⟨1991, 1, 1⟩, 7080),
     (⟨1992, 1, 1⟩, 7440),
     (⟨1993, 1, 1⟩, 7680),
     (⟨1994, 1, 1⟩, 8040),
     (⟨1995, 1, 1⟩, 8160),
     (⟨1996, 1, 1⟩, 8280),
     (⟨1997, 1, 1⟩, 8640),
     (⟨1998, 1, 1⟩, 9120),
     (⟨1999, 1, 1⟩, 9600),
     (⟨2000, 1, 1⟩, 17000),
     (⟨2001, 1, 1⟩, 25000),
     (⟨2002, 1, 1⟩, 30000),
     (⟨2003, 1, 1⟩, 30720),
     (⟨2004, 1, 1⟩, 31080),
     (⟨2005, 1, 1⟩, 31800),
     (⟨2006, 1, 1⟩, 33240),
     (⟨2007, 1, 1⟩, 34440),
     (⟨2008, 1, 1⟩, 36120),
     (⟨2009, 1, 1⟩, 37680),
     (⟨2010, 1, 1⟩, 37680),
     (⟨2011, 1, 1⟩, 37680),
     (⟨2012, 1, 1⟩, 38880),
     (⟨2013, 1, 1⟩, 40080),
     (⟨2014, 1, 1⟩, 41400),
     (⟨2015, 1, 1⟩, 41880),
     (⟨2016, 1, 1⟩, 41880),
     (⟨2017, 1, 1⟩, 44880),
     (⟨2018, 1, 1⟩, 45360),
     (⟨2019, 1, 1⟩, 46920),
     (⟨2020, 1, 1⟩, 48600),
     (⟨2021, 1, 1⟩, 50520),
     (⟨2022, 1, 1⟩, 51960),
     (⟨2023, 1, 1⟩, 56520),
     (⟨2024, 1, 1⟩, 59520),
     (⟨2025, 1, 1⟩, 62160),
     (⟨2026, 1, 1⟩, 65160)]⟩

/-- The US withholds this amount from benefits for every $2 earned above the exempt amount.
    `gov/ssa/social_security/earnings_test/reduction_rate_under_fra.yaml` (policyengine-us).
    * 42 U.S.C. § 403(f)(3):
      https://www.law.cornell.edu/uscode/text/42/403#f_3
    * 20 CFR § 404.434(a):
      https://www.law.cornell.edu/cfr/text/20/404.434
    * Social Security POMS RS 02501.021:
      https://secure.ssa.gov/poms.nsf/lnx/0302501021 -/
def ssa.social_security.earnings_test.reduction_rate_under_fra : DatedParam Rate :=
  ⟨(⟨1940, 1, 1⟩, mkRat 1 2), []⟩

/-- The US withholds this amount from benefits for every $3 earned above the exempt amount in
    the year of reaching FRA.
    `gov/ssa/social_security/earnings_test/reduction_rate_year_of_fra.yaml` (policyengine-us).
    * 42 U.S.C. § 403(f)(3):
      https://www.law.cornell.edu/uscode/text/42/403#f_3
    * 20 CFR § 404.434(b):
      https://www.law.cornell.edu/cfr/text/20/404.434
    * Social Security POMS RS 02501.021:
      https://secure.ssa.gov/poms.nsf/lnx/0302501021 -/
def ssa.social_security.earnings_test.reduction_rate_year_of_fra : DatedParam Rate :=
  ⟨(⟨1940, 1, 1⟩, mkRat 333333 1000000), []⟩

/-- The US determines full retirement age based on year of birth.
    `gov/ssa/social_security/full_retirement_age_by_birth_year.yaml` (policyengine-us).
    * 42 U.S. Code § 416(l) - Retirement age:
      https://www.law.cornell.edu/uscode/text/42/416#l
    * SSA Full Retirement Age:
      https://www.ssa.gov/benefits/retirement/planner/agereduction.html -/
def ssa.social_security.full_retirement_age_by_birth_year : Scale :=
  ⟨[⟨⟨(⟨1900, 1, 1⟩, 1900), []⟩, ⟨(⟨1900, 1, 1⟩, 780), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1938), []⟩, ⟨(⟨1900, 1, 1⟩, 782), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1939), []⟩, ⟨(⟨1900, 1, 1⟩, 784), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1940), []⟩, ⟨(⟨1900, 1, 1⟩, 786), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1941), []⟩, ⟨(⟨1900, 1, 1⟩, 788), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1942), []⟩, ⟨(⟨1900, 1, 1⟩, 790), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1943), []⟩, ⟨(⟨1900, 1, 1⟩, 792), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1955), []⟩, ⟨(⟨1900, 1, 1⟩, 794), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1956), []⟩, ⟨(⟨1900, 1, 1⟩, 796), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1957), []⟩, ⟨(⟨1900, 1, 1⟩, 798), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1958), []⟩, ⟨(⟨1900, 1, 1⟩, 800), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1959), []⟩, ⟨(⟨1900, 1, 1⟩, 802), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1960), []⟩, ⟨(⟨1900, 1, 1⟩, 804), []⟩⟩]⟩

/-- Minimum age at which a person can claim Social Security retirement benefits.
    `gov/ssa/social_security/minimum_retirement_age.yaml` (policyengine-us).
    * 42 U.S. Code § 402(a) - Old-age insurance benefits:
      https://www.law.cornell.edu/uscode/text/42/402#a
    * SSA Early or Late Retirement:
      https://www.ssa.gov/OACT/quickcalc/early_late.html -/
def ssa.social_security.minimum_retirement_age : DatedParam Rat :=
  ⟨(⟨1956, 1, 1⟩, 62), []⟩

/-- The US applies these factors to Average Indexed Monthly Earnings in each bracket when
    calculating Social Security Primary Insurance Amount.
    `gov/ssa/social_security/pia/formula_factors.yaml` (policyengine-us).
    * 42 USC 415(a)(1)(A):
      https://www.law.cornell.edu/uscode/text/42/415#a_1_A
    * PIA Formula:
      https://www.ssa.gov/OACT/COLA/piaformula.html -/
def ssa.social_security.pia.formula_factors : Scale :=
  ⟨[⟨⟨(⟨2015, 1, 1⟩, 0),
    [(⟨2016, 1, 1⟩, 0),
     (⟨2017, 1, 1⟩, 0),
     (⟨2018, 1, 1⟩, 0),
     (⟨2019, 1, 1⟩, 0),
     (⟨2020, 1, 1⟩, 0),
     (⟨2021, 1, 1⟩, 0),
     (⟨2022, 1, 1⟩, 0),
     (⟨2023, 1, 1⟩, 0),
     (⟨2024, 1, 1⟩, 0),
     (⟨2025, 1, 1⟩, 0),
     (⟨2026, 1, 1⟩, 0)]⟩, ⟨(⟨1979, 1, 1⟩, mkRat 9 10), []⟩⟩,
    ⟨⟨(⟨2015, 1, 1⟩, 826),
    [(⟨2016, 1, 1⟩, 856),
     (⟨2017, 1, 1⟩, 885),
     (⟨2018, 1, 1⟩, 895),
     (⟨2019, 1, 1⟩, 926),
     (⟨2020, 1, 1⟩, 960),
     (⟨2021, 1, 1⟩, 996),
     (⟨2022, 1, 1⟩, 1024),
     (⟨2023, 1, 1⟩, 1115),
     (⟨2024, 1, 1⟩, 1174),
     (⟨2025, 1, 1⟩, 1226),
     (⟨2026, 1, 1⟩, 1286)]⟩, ⟨(⟨1979, 1, 1⟩, mkRat 8 25), []⟩⟩,
    ⟨⟨(⟨2015, 1, 1⟩, 4980),
    [(⟨2016, 1, 1⟩, 5157),
     (⟨2017, 1, 1⟩, 5336),
     (⟨2018, 1, 1⟩, 5397),
     (⟨2019, 1, 1⟩, 5583),
     (⟨2020, 1, 1⟩, 5785),
     (⟨2021, 1, 1⟩, 6002),
     (⟨2022, 1, 1⟩, 6172),
     (⟨2023, 1, 1⟩, 6721),
     (⟨2024, 1, 1⟩, 7078),
     (⟨2025, 1, 1⟩, 7391),
     (⟨2026, 1, 1⟩, 7749)]⟩, ⟨(⟨1979, 1, 1⟩, mkRat 3 20), []⟩⟩]⟩

/-- The US credits one Social Security quarter of coverage when a person earns at least this
    amount.
    `gov/ssa/social_security/quarters_of_coverage_threshold.yaml` (policyengine-us).
    * 42 U.S.C. § 413(d)(2):
      https://www.law.cornell.edu/uscode/text/42/413#d_2
    * 20 CFR § 404.143:
      https://www.law.cornell.edu/cfr/text/20/404.143
    * Social Security Quarters of Coverage:
      https://www.ssa.gov/OACT/COLA/QC.html -/
def ssa.social_security.quarters_of_coverage_threshold : DatedParam USD :=
  ⟨(⟨1978, 1, 1⟩, 250),
    [(⟨1979, 1, 1⟩, 260),
     (⟨1980, 1, 1⟩, 290),
     (⟨1981, 1, 1⟩, 310),
     (⟨1982, 1, 1⟩, 340),
     (⟨1983, 1, 1⟩, 370),
     (⟨1984, 1, 1⟩, 390),
     (⟨1985, 1, 1⟩, 410),
     (⟨1986, 1, 1⟩, 440),
     (⟨1987, 1, 1⟩, 460),
     (⟨1988, 1, 1⟩, 470),
     (⟨1989, 1, 1⟩, 500),
     (⟨1990, 1, 1⟩, 520),
     (⟨1991, 1, 1⟩, 540),
     (⟨1992, 1, 1⟩, 570),
     (⟨1993, 1, 1⟩, 590),
     (⟨1994, 1, 1⟩, 620),
     (⟨1995, 1, 1⟩, 630),
     (⟨1996, 1, 1⟩, 640),
     (⟨1997, 1, 1⟩, 670),
     (⟨1998, 1, 1⟩, 700),
     (⟨1999, 1, 1⟩, 740),
     (⟨2000, 1, 1⟩, 780),
     (⟨2001, 1, 1⟩, 830),
     (⟨2002, 1, 1⟩, 870),
     (⟨2003, 1, 1⟩, 890),
     (⟨2004, 1, 1⟩, 900),
     (⟨2005, 1, 1⟩, 920),
     (⟨2006, 1, 1⟩, 970),
     (⟨2007, 1, 1⟩, 1000),
     (⟨2008, 1, 1⟩, 1050),
     (⟨2009, 1, 1⟩, 1090),
     (⟨2010, 1, 1⟩, 1120),
     (⟨2011, 1, 1⟩, 1120),
     (⟨2012, 1, 1⟩, 1130),
     (⟨2013, 1, 1⟩, 1160),
     (⟨2014, 1, 1⟩, 1200),
     (⟨2015, 1, 1⟩, 1220),
     (⟨2016, 1, 1⟩, 1260),
     (⟨2017, 1, 1⟩, 1300),
     (⟨2018, 1, 1⟩, 1320),
     (⟨2019, 1, 1⟩, 1360),
     (⟨2020, 1, 1⟩, 1410),
     (⟨2021, 1, 1⟩, 1470),
     (⟨2022, 1, 1⟩, 1510),
     (⟨2023, 1, 1⟩, 1640),
     (⟨2024, 1, 1⟩, 1730),
     (⟨2025, 1, 1⟩, 1810),
     (⟨2026, 1, 1⟩, 1890)]⟩

/-- The US delayed retirement credit rates by birth year.
    `gov/ssa/social_security/retirement_age_adjustment/delayed_retirement/credit_rates.yaml` (policyengine-us).
    * 42 U.S. Code § 402(w):
      https://www.law.cornell.edu/uscode/text/42/402#w
    * SSA Delayed Retirement Credits:
      https://www.ssa.gov/OACT/quickcalc/early_late.html -/
def ssa.social_security.retirement_age_adjustment.delayed_retirement.credit_rates : Scale :=
  ⟨[⟨⟨(⟨1900, 1, 1⟩, 1900), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 3 100), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1925), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 7 200), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1927), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 1 25), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1929), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 9 200), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1931), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 1 20), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1933), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 11 200), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1935), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 3 50), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1937), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 13 200), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1939), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 7 100), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1941), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 3 40), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 1943), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 2 25), []⟩⟩]⟩

/-- The US applies these monthly reduction rates for early retirement based on months before
    full retirement age.
    `gov/ssa/social_security/retirement_age_adjustment/early_retirement/reduction_rates.yaml` (policyengine-us).
    * 42 U.S. Code § 402(q)(9) - Reduction of old-age insurance benefits:
      https://www.law.cornell.edu/uscode/text/42/402#q_9
    * 20 CFR § 404.410 - How reduction factors are computed:
      https://www.law.cornell.edu/cfr/text/20/404.410 -/
def ssa.social_security.retirement_age_adjustment.early_retirement.reduction_rates : Scale :=
  ⟨[⟨⟨(⟨1900, 1, 1⟩, 0), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 138889 25000000), []⟩⟩,
    ⟨⟨(⟨1900, 1, 1⟩, 36), []⟩, ⟨(⟨1900, 1, 1⟩, mkRat 416667 100000000), []⟩⟩]⟩

/-- The US limits delayed retirement credits to a maximum number of years past full retirement
    age.
    `gov/ssa/social_security/retirement_age_adjustment/max_delayed_years.yaml` (policyengine-us). -/
def ssa.social_security.retirement_age_adjustment.max_delayed_years : DatedParam Rat :=
  ⟨(⟨1900, 1, 1⟩, 4), []⟩

/-- The US caps Social Security taxable earnings at this amount per year.
    `gov/ssa/social_security/wage_base.yaml` (policyengine-us).
    * Contribution and Benefit Base:
      https://www.ssa.gov/OACT/COLA/cbb.html
    * 42 USC 430 - Adjustment of contribution and benefit base:
      https://www.law.cornell.edu/uscode/text/42/430 -/
def ssa.social_security.wage_base : DatedParam USD :=
  ⟨(⟨1937, 1, 1⟩, 3000),
    [(⟨1951, 1, 1⟩, 3600),
     (⟨1955, 1, 1⟩, 4200),
     (⟨1959, 1, 1⟩, 4800),
     (⟨1966, 1, 1⟩, 6600),
     (⟨1968, 1, 1⟩, 7800),
     (⟨1972, 1, 1⟩, 9000),
     (⟨1973, 1, 1⟩, 10800),
     (⟨1974, 1, 1⟩, 13200),
     (⟨1975, 1, 1⟩, 14100),
     (⟨1976, 1, 1⟩, 15300),
     (⟨1977, 1, 1⟩, 16500),
     (⟨1978, 1, 1⟩, 17700),
     (⟨1979, 1, 1⟩, 22900),
     (⟨1980, 1, 1⟩, 25900),
     (⟨1981, 1, 1⟩, 29700),
     (⟨1982, 1, 1⟩, 32400),
     (⟨1983, 1, 1⟩, 35700),
     (⟨1984, 1, 1⟩, 37800),
     (⟨1985, 1, 1⟩, 39600),
     (⟨1986, 1, 1⟩, 42000),
     (⟨1987, 1, 1⟩, 43800),
     (⟨1988, 1, 1⟩, 45000),
     (⟨1989, 1, 1⟩, 48000),
     (⟨1990, 1, 1⟩, 51300),
     (⟨1991, 1, 1⟩, 53400),
     (⟨1992, 1, 1⟩, 55500),
     (⟨1993, 1, 1⟩, 57600),
     (⟨1994, 1, 1⟩, 60600),
     (⟨1995, 1, 1⟩, 61200),
     (⟨1996, 1, 1⟩, 62700),
     (⟨1997, 1, 1⟩, 65400),
     (⟨1998, 1, 1⟩, 68400),
     (⟨1999, 1, 1⟩, 72600),
     (⟨2000, 1, 1⟩, 76200),
     (⟨2001, 1, 1⟩, 80400),
     (⟨2002, 1, 1⟩, 84900),
     (⟨2003, 1, 1⟩, 87000),
     (⟨2004, 1, 1⟩, 87900),
     (⟨2005, 1, 1⟩, 90000),
     (⟨2006, 1, 1⟩, 94200),
     (⟨2007, 1, 1⟩, 97500),
     (⟨2008, 1, 1⟩, 102000),
     (⟨2009, 1, 1⟩, 106800),
     (⟨2010, 1, 1⟩, 106800),
     (⟨2011, 1, 1⟩, 106800),
     (⟨2012, 1, 1⟩, 110100),
     (⟨2013, 1, 1⟩, 113700),
     (⟨2014, 1, 1⟩, 117000),
     (⟨2015, 1, 1⟩, 118500),
     (⟨2016, 1, 1⟩, 118500),
     (⟨2017, 1, 1⟩, 127200),
     (⟨2018, 1, 1⟩, 128400),
     (⟨2019, 1, 1⟩, 132900),
     (⟨2020, 1, 1⟩, 137700),
     (⟨2021, 1, 1⟩, 142800),
     (⟨2022, 1, 1⟩, 147000),
     (⟨2023, 1, 1⟩, 160200),
     (⟨2024, 1, 1⟩, 168600),
     (⟨2025, 1, 1⟩, 176100),
     (⟨2026, 1, 1⟩, 184500)]⟩

/-- Abolish SSI payments.
    `gov/ssa/ssi/abolish_ssi.yaml` (policyengine-us). -/
def ssa.ssi.abolish_ssi : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Monthly maximum Federal SSI payment amounts for an eligible individual with an eligible
    spouse.
    `gov/ssa/ssi/amount/couple.yaml` (policyengine-us).
    * SSI Federal Payment Amounts:
      https://www.ssa.gov/oact/cola/SSIamts.html -/
def ssa.ssi.amount.couple : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, mkRat 1183 5),
    [(⟨1976, 1, 1⟩, mkRat 1259 5),
     (⟨1977, 1, 1⟩, mkRat 2667 10),
     (⟨1978, 1, 1⟩, mkRat 2841 10),
     (⟨1979, 1, 1⟩, mkRat 3123 10),
     (⟨1980, 1, 1⟩, 357),
     (⟨1981, 1, 1⟩, 397),
     (⟨1982, 1, 1⟩, mkRat 2132 5),
     (⟨1983, 1, 1⟩, mkRat 2282 5),
     (⟨1984, 1, 1⟩, 472),
     (⟨1985, 1, 1⟩, 488),
     (⟨1986, 1, 1⟩, 504),
     (⟨1987, 1, 1⟩, 510),
     (⟨1988, 1, 1⟩, 532),
     (⟨1989, 1, 1⟩, 553),
     (⟨1990, 1, 1⟩, 579),
     (⟨1991, 1, 1⟩, 610),
     (⟨1992, 1, 1⟩, 633),
     (⟨1993, 1, 1⟩, 652),
     (⟨1994, 1, 1⟩, 669),
     (⟨1995, 1, 1⟩, 687),
     (⟨1996, 1, 1⟩, 705),
     (⟨1997, 1, 1⟩, 726),
     (⟨1998, 1, 1⟩, 741),
     (⟨1999, 1, 1⟩, 751),
     (⟨2000, 1, 1⟩, 769),
     (⟨2001, 1, 1⟩, 796),
     (⟨2002, 1, 1⟩, 817),
     (⟨2003, 1, 1⟩, 829),
     (⟨2004, 1, 1⟩, 846),
     (⟨2005, 1, 1⟩, 869),
     (⟨2006, 1, 1⟩, 904),
     (⟨2007, 1, 1⟩, 934),
     (⟨2008, 1, 1⟩, 956),
     (⟨2009, 1, 1⟩, 1011),
     (⟨2010, 1, 1⟩, 1011),
     (⟨2011, 1, 1⟩, 1011),
     (⟨2012, 1, 1⟩, 1048),
     (⟨2013, 1, 1⟩, 1066),
     (⟨2014, 1, 1⟩, 1082),
     (⟨2015, 1, 1⟩, 1100),
     (⟨2016, 1, 1⟩, 1100),
     (⟨2017, 1, 1⟩, 1103),
     (⟨2018, 1, 1⟩, 1125),
     (⟨2019, 1, 1⟩, 1157),
     (⟨2020, 1, 1⟩, 1175),
     (⟨2021, 1, 1⟩, 1191),
     (⟨2022, 1, 1⟩, 1261),
     (⟨2023, 1, 1⟩, 1371),
     (⟨2024, 1, 1⟩, 1415),
     (⟨2025, 1, 1⟩, 1450),
     (⟨2026, 1, 1⟩, 1491)]⟩

/-- Monthly maximum Federal SSI payment amounts for an eligible individual.
    `gov/ssa/ssi/amount/individual.yaml` (policyengine-us).
    * SSI Federal Payment Amounts:
      https://www.ssa.gov/oact/cola/SSIamts.html -/
def ssa.ssi.amount.individual : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, mkRat 1577 10),
    [(⟨1976, 1, 1⟩, mkRat 839 5),
     (⟨1977, 1, 1⟩, mkRat 889 5),
     (⟨1978, 1, 1⟩, mkRat 947 5),
     (⟨1979, 1, 1⟩, mkRat 1041 5),
     (⟨1980, 1, 1⟩, 238),
     (⟨1981, 1, 1⟩, mkRat 2647 10),
     (⟨1982, 1, 1⟩, mkRat 2843 10),
     (⟨1983, 1, 1⟩, mkRat 3043 10),
     (⟨1984, 1, 1⟩, 314),
     (⟨1985, 1, 1⟩, 325),
     (⟨1986, 1, 1⟩, 336),
     (⟨1987, 1, 1⟩, 340),
     (⟨1988, 1, 1⟩, 354),
     (⟨1989, 1, 1⟩, 368),
     (⟨1990, 1, 1⟩, 386),
     (⟨1991, 1, 1⟩, 407),
     (⟨1992, 1, 1⟩, 422),
     (⟨1993, 1, 1⟩, 434),
     (⟨1994, 1, 1⟩, 446),
     (⟨1995, 1, 1⟩, 458),
     (⟨1996, 1, 1⟩, 470),
     (⟨1997, 1, 1⟩, 484),
     (⟨1998, 1, 1⟩, 494),
     (⟨1999, 1, 1⟩, 500),
     (⟨2000, 1, 1⟩, 513),
     (⟨2001, 1, 1⟩, 531),
     (⟨2002, 1, 1⟩, 545),
     (⟨2003, 1, 1⟩, 552),
     (⟨2004, 1, 1⟩, 564),
     (⟨2005, 1, 1⟩, 579),
     (⟨2006, 1, 1⟩, 603),
     (⟨2007, 1, 1⟩, 623),
     (⟨2008, 1, 1⟩, 637),
     (⟨2009, 1, 1⟩, 674),
     (⟨2010, 1, 1⟩, 674),
     (⟨2011, 1, 1⟩, 674),
     (⟨2012, 1, 1⟩, 698),
     (⟨2013, 1, 1⟩, 710),
     (⟨2014, 1, 1⟩, 721),
     (⟨2015, 1, 1⟩, 733),
     (⟨2016, 1, 1⟩, 733),
     (⟨2017, 1, 1⟩, 735),
     (⟨2018, 1, 1⟩, 750),
     (⟨2019, 1, 1⟩, 771),
     (⟨2020, 1, 1⟩, 783),
     (⟨2021, 1, 1⟩, 794),
     (⟨2022, 1, 1⟩, 841),
     (⟨2023, 1, 1⟩, 914),
     (⟨2024, 1, 1⟩, 943),
     (⟨2025, 1, 1⟩, 967),
     (⟨2026, 1, 1⟩, 994)]⟩

/-- The Social Security Administration provides this reduced Supplemental Security Income amount
    for an eligible couple both residing in a Medicaid-funded institution.
    `gov/ssa/ssi/amount/institutional/couple.yaml` (policyengine-us).
    * 42 USC 1382(e)(1)(B):
      https://www.law.cornell.edu/uscode/text/42/1382
    * HHSC MEPD Handbook Section H-6000 - Co-Payment for SSI Cases:
      https://www.hhs.texas.gov/handbooks/medicaid-elderly-people-disabilities-handbook/h-6000-co-payment-ssi-cases -/
def ssa.ssi.amount.institutional.couple : DatedParam USD :=
  ⟨(⟨1988, 7, 1⟩, 60), []⟩

/-- The Social Security Administration provides this reduced Supplemental Security Income amount
    for an eligible individual residing in a Medicaid-funded institution.
    `gov/ssa/ssi/amount/institutional/individual.yaml` (policyengine-us).
    * 42 USC 1382(e)(1)(B):
      https://www.law.cornell.edu/uscode/text/42/1382
    * HHSC MEPD Handbook Section H-6000 - Co-Payment for SSI Cases:
      https://www.hhs.texas.gov/handbooks/medicaid-elderly-people-disabilities-handbook/h-6000-co-payment-ssi-cases -/
def ssa.ssi.amount.institutional.individual : DatedParam USD :=
  ⟨(⟨1988, 7, 1⟩, 30), []⟩

/-- SSA sets this amount as the monthly federal SSI payment for an eligible individual residing
    in a medical treatment facility where Medicaid pays more than half the cost of care.
    `gov/ssa/ssi/amount/medical_facility.yaml` (policyengine-us).
    * 42 U.S.C. § 1382(e)(1)(A) - Amount of benefits for individuals in medical treatment
    facilities:
      https://www.law.cornell.edu/uscode/text/42/1382#e_1_A
    * 20 CFR § 416.414 - Amount of benefits; eligible individual or eligible couple in a medical
    treatment facility:
      https://www.law.cornell.edu/cfr/text/20/416.414 -/
def ssa.ssi.amount.medical_facility : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 25), [(⟨1988, 7, 1⟩, 30)]⟩

/-- SSA reduces this share of the federal benefit rate for SSI recipients living in another
    person's household under the one-third reduction rule.
    `gov/ssa/ssi/amount/one_third_reduction_rate.yaml` (policyengine-us).
    * 42 U.S.C. § 1382a(a)(2)(A)(i) - One-third reduction in lieu of counting in-kind support
    and maintenance:
      https://www.law.cornell.edu/uscode/text/42/1382a#a_2_A_i
    * 20 CFR § 416.1131 - The one-third reduction rule:
      https://www.law.cornell.edu/cfr/text/20/416.1131 -/
def ssa.ssi.amount.one_third_reduction_rate : DatedParam Rate :=
  ⟨(⟨1975, 1, 1⟩, mkRat 333333333 1000000000), []⟩

/-- Age to qualify for Supplemental Security Income.
    `gov/ssa/ssi/eligibility/aged_threshold.yaml` (policyengine-us).
    * 20 CFR § 416.202(a)(1):
      https://www.law.cornell.edu/cfr/text/20/416.202#a_1 -/
def ssa.ssi.eligibility.aged_threshold : DatedParam Rat :=
  ⟨(⟨1975, 1, 1⟩, 65), []⟩

/-- The US counts these asset types as countable resources for SSI eligibility. Excludes home,
    one vehicle, household goods, burial plots, and retirement accounts.
    `gov/ssa/ssi/eligibility/resources/countable.yaml` (policyengine-us).
    * SSA POMS SI 01140.200 - Checking and Savings Accounts:
      https://secure.ssa.gov/poms.nsf/lnx/0501140200
    * SSA POMS SI 01140.220 - Stocks:
      https://secure.ssa.gov/poms.nsf/lnx/0501140220
    * SSA POMS SI 01140.240 - U.S. Savings Bonds:
      https://secure.ssa.gov/poms.nsf/lnx/0501140240
    * SSA POMS SI 01140.250 - Municipal, Corporate and Government Bonds:
      https://secure.ssa.gov/poms.nsf/lnx/0501140250 -/
def ssa.ssi.eligibility.resources.countable : DatedParam (List String) :=
  ⟨(⟨1975, 1, 1⟩, ["bank_account_assets", "stock_assets", "bond_assets"]), []⟩

/-- SSI resource limit for couples.
    `gov/ssa/ssi/eligibility/resources/limit/couple.yaml` (policyengine-us).
    * 20 CFR § 416.1205 - Limitation on resources.:
      https://www.law.cornell.edu/cfr/text/20/416.1205#c -/
def ssa.ssi.eligibility.resources.limit.couple : DatedParam USD :=
  ⟨(⟨1985, 1, 1⟩, 2400),
    [(⟨1986, 1, 1⟩, 2550),
     (⟨1987, 1, 1⟩, 2700),
     (⟨1988, 1, 1⟩, 2850),
     (⟨1989, 1, 1⟩, 3000)]⟩

/-- SSI resource limit for individuals.
    `gov/ssa/ssi/eligibility/resources/limit/individual.yaml` (policyengine-us).
    * 20 CFR § 416.1205 - Limitation on resources.:
      https://www.law.cornell.edu/cfr/text/20/416.1205#c -/
def ssa.ssi.eligibility.resources.limit.individual : DatedParam USD :=
  ⟨(⟨1985, 1, 1⟩, 1600),
    [(⟨1986, 1, 1⟩, 1700),
     (⟨1987, 1, 1⟩, 1800),
     (⟨1988, 1, 1⟩, 1900),
     (⟨1989, 1, 1⟩, 2000)]⟩

/-- The US considers these statuses as qualified noncitizens for Supplemental Security Income.
    `gov/ssa/ssi/eligibility/status/qualified_noncitizen_status.yaml` (policyengine-us).
    * SI 00502.100 - Basic SSI Noncitizen Eligibility Requirements:
      https://secure.ssa.gov/poms.nsf/lnx/0500502100 -/
def ssa.ssi.eligibility.status.qualified_noncitizen_status : DatedParam (List String) :=
  ⟨(⟨1975, 1, 1⟩, ["LEGAL_PERMANENT_RESIDENT",
      "REFUGEE",
      "ASYLEE",
      "DEPORTATION_WITHHELD",
      "CUBAN_HAITIAN_ENTRANT",
      "CONDITIONAL_ENTRANT",
      "PAROLED_ONE_YEAR"]), []⟩

/-- The Social Security Administration limits the blind or disabled Supplemental Security Income
    amount to student filers below this age limit.
    `gov/ssa/ssi/income/exclusions/blind_or_disabled_working_student/age_limit.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_3
    * 2011 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI11/Exclusions.html#39619
    * 2012 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI12/V_B_Exclusions.html#39619
    * 2013 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI13/V_B_Exclusions.html#39619
    * 2014 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI14/V_B_Exclusions.html#39619
    * 2015 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI15/V_B_Exclusions.html#39619
    * 2016 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI16/V_B_Exclusions.html#39619
    * 2017 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI17/V_B_Exclusions.html#39619
    * 2018 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI18/V_B_Exclusions.html#39619
    * 2019 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI19/V_B_Exclusions.html#39619
    * 2020 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI20/V_B_Exclusions.html#39619
    * 2021 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI21/V_B_Exclusions.html#39619
    * 2022 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI22/V_B_Exclusions.html#39619
    * 2023 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI23/V_B_Exclusions.html#39619
    * 2024 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI24/V_E_WorkIncentives.html -/
def ssa.ssi.income.exclusions.blind_or_disabled_working_student.age_limit : DatedParam Rat :=
  ⟨(⟨1974, 1, 1⟩, 22), []⟩

/-- The Social Security Administration excludes the following earned income amount for blind or
    disabled student filers under the Supplemental Security Income.
    `gov/ssa/ssi/income/exclusions/blind_or_disabled_working_student/amount.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_3
    * 2011 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI11/Exclusions.html#39619
    * 2012 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI12/V_B_Exclusions.html#39619
    * 2013 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI13/V_B_Exclusions.html#39619
    * 2014 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI14/V_B_Exclusions.html#39619
    * 2015 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI15/V_B_Exclusions.html#39619
    * 2016 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI16/V_B_Exclusions.html#39619
    * 2017 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI17/V_B_Exclusions.html#39619
    * 2018 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI18/V_B_Exclusions.html#39619
    * 2019 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI19/V_B_Exclusions.html#39619
    * 2020 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI20/V_B_Exclusions.html#39619
    * 2021 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI21/V_B_Exclusions.html#39619
    * 2022 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI22/V_B_Exclusions.html#39619
    * 2023 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI23/V_B_Exclusions.html#39619
    * 2024 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI24/V_E_WorkIncentives.html
    * Student Earned Income Exclusion for SSI:
      https://www.ssa.gov/oact/cola/studentEIE.html -/
def ssa.ssi.income.exclusions.blind_or_disabled_working_student.amount : DatedParam USD :=
  ⟨(⟨1974, 1, 1⟩, 400),
    [(⟨2001, 1, 1⟩, 1290),
     (⟨2002, 1, 1⟩, 1320),
     (⟨2003, 1, 1⟩, 1340),
     (⟨2004, 1, 1⟩, 1370),
     (⟨2005, 1, 1⟩, 1410),
     (⟨2006, 1, 1⟩, 1460),
     (⟨2007, 1, 1⟩, 1510),
     (⟨2008, 1, 1⟩, 1550),
     (⟨2009, 1, 1⟩, 1640),
     (⟨2012, 1, 1⟩, 1700),
     (⟨2013, 1, 1⟩, 1730),
     (⟨2014, 1, 1⟩, 1750),
     (⟨2015, 1, 1⟩, 1780),
     (⟨2017, 1, 1⟩, 1790),
     (⟨2018, 1, 1⟩, 1820),
     (⟨2019, 1, 1⟩, 1870),
     (⟨2020, 1, 1⟩, 1900),
     (⟨2021, 1, 1⟩, 1930),
     (⟨2022, 1, 1⟩, 2040),
     (⟨2023, 1, 1⟩, 2220),
     (⟨2024, 1, 1⟩, 2290),
     (⟨2025, 1, 1⟩, 2350),
     (⟨2026, 1, 1⟩, 2410)]⟩

/-- The Social Security Administration caps the annual earned income exclusion for blind or
    disabled students receiving Supplemental Security Income at this amount.
    `gov/ssa/ssi/income/exclusions/blind_or_disabled_working_student/cap.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_3
    * 2011 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI11/Exclusions.html#39619
    * 2012 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI12/V_B_Exclusions.html#39619
    * 2013 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI13/V_B_Exclusions.html#39619
    * 2014 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI14/V_B_Exclusions.html#39619
    * 2015 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI15/V_B_Exclusions.html#39619
    * 2016 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI16/V_B_Exclusions.html#39619
    * 2017 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI17/V_B_Exclusions.html#39619
    * 2018 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI18/V_B_Exclusions.html#39619
    * 2019 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI19/V_B_Exclusions.html#39619
    * 2020 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI20/V_B_Exclusions.html#39619
    * 2021 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI21/V_B_Exclusions.html#39619
    * 2022 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI22/V_B_Exclusions.html#39619
    * 2023 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/oact/ssir/SSI23/V_B_Exclusions.html#39619
    * 2024 Annual Report of the SSI Program - B. INCOME AND RESOURCE EXCLUSIONS:
      https://www.ssa.gov/OACT/ssir/SSI24/V_E_WorkIncentives.html
    * Student Earned Income Exclusion for SSI:
      https://www.ssa.gov/oact/cola/studentEIE.html -/
def ssa.ssi.income.exclusions.blind_or_disabled_working_student.cap : DatedParam USD :=
  ⟨(⟨1974, 1, 1⟩, 1620),
    [(⟨2001, 1, 1⟩, 5200),
     (⟨2002, 1, 1⟩, 5340),
     (⟨2003, 1, 1⟩, 5410),
     (⟨2004, 1, 1⟩, 5520),
     (⟨2005, 1, 1⟩, 5670),
     (⟨2006, 1, 1⟩, 5910),
     (⟨2007, 1, 1⟩, 6100),
     (⟨2008, 1, 1⟩, 6240),
     (⟨2009, 1, 1⟩, 6600),
     (⟨2012, 1, 1⟩, 6840),
     (⟨2013, 1, 1⟩, 6960),
     (⟨2014, 1, 1⟩, 7060),
     (⟨2015, 1, 1⟩, 7180),
     (⟨2017, 1, 1⟩, 7200),
     (⟨2018, 1, 1⟩, 7350),
     (⟨2019, 1, 1⟩, 7550),
     (⟨2020, 1, 1⟩, 7670),
     (⟨2021, 1, 1⟩, 7770),
     (⟨2022, 1, 1⟩, 8230),
     (⟨2023, 1, 1⟩, 8950),
     (⟨2024, 1, 1⟩, 9230),
     (⟨2025, 1, 1⟩, 9460),
     (⟨2026, 1, 1⟩, 9730)]⟩

/-- Flat amount of earned income excluded from SSI countable income.
    `gov/ssa/ssi/income/exclusions/earned.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_5 -/
def ssa.ssi.income.exclusions.earned : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 65), []⟩

/-- Share of earned income above the flat exclusion that is excluded from SSI countable income.
    `gov/ssa/ssi/income/exclusions/earned_share.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_7 -/
def ssa.ssi.income.exclusions.earned_share : DatedParam Rate :=
  ⟨(⟨1975, 1, 1⟩, mkRat 1 2), []⟩

/-- Flat amount of income excluded from SSI countable income.
    `gov/ssa/ssi/income/exclusions/general.yaml` (policyengine-us).
    * 20 CFR § 416.1112 - Earned income we do not count.:
      https://www.law.cornell.edu/cfr/text/20/416.1112#c_4 -/
def ssa.ssi.income.exclusions.general : DatedParam USD :=
  ⟨(⟨1975, 1, 1⟩, 20), []⟩

/-- SSA uses this indicator to determine whether food counts in SSI in-kind support and
    maintenance calculations.
    `gov/ssa/ssi/income/ism/food_counts.yaml` (policyengine-us).
    * 20 CFR § 416.1130 - Introduction to in-kind support and maintenance (as amended):
      https://www.law.cornell.edu/cfr/text/20/416.1130
    * 89 FR 21199 - Omitting Food from In-Kind Support and Maintenance Calculations:
      https://www.federalregister.gov/documents/2024/03/27/2024-06464/omitting-food-from-in-kind-support-and-maintenance-calculations -/
def ssa.ssi.income.ism.food_counts : DatedParam Bool :=
  ⟨(⟨1975, 1, 1⟩, true), [(⟨2024, 10, 1⟩, false)]⟩

/-- SSA uses this share of the federal benefit rate in calculating the presumed maximum value of
    in-kind support and maintenance.
    `gov/ssa/ssi/income/ism/pmv_fbr_fraction.yaml` (policyengine-us).
    * 20 CFR § 416.1140 - The presumed value rule:
      https://www.law.cornell.edu/cfr/text/20/416.1140
    * POMS SI 00835.300 - Presumed Maximum Value (PMV) Rule:
      https://secure.ssa.gov/apps10/poms.nsf/lnx/0500835300 -/
def ssa.ssi.income.ism.pmv_fbr_fraction : DatedParam Rate :=
  ⟨(⟨1975, 1, 1⟩, mkRat 333333333 1000000000), []⟩

/-- The US counts these income sources as unearned income for Supplemental Security Income.
    `gov/ssa/ssi/income/sources/earned.yaml` (policyengine-us).
    * 20 CFR § 416.1110 - What is earned income.:
      https://www.law.cornell.edu/cfr/text/20/416.1110 -/
def ssa.ssi.income.sources.earned : DatedParam (List String) :=
  ⟨(⟨1975, 1, 1⟩, ["employment_income", "self_employment_income", "sstb_self_employment_income"]), []⟩

/-- The US provides SSI to legal permanent residents with this minimum number of qualifying
    quarters of earnings.
    `gov/ssa/ssi/income/sources/qualifying_quarters_threshold.yaml` (policyengine-us).
    * SI 00502.135 - Lawfully Admitted for Permanent Residence (LAPR) with 40 Qualifying
    Quarters of Earnings:
      https://secure.ssa.gov/poms.nsf/lnx/0500502135 -/
def ssa.ssi.income.sources.qualifying_quarters_threshold : DatedParam Rat :=
  ⟨(⟨1975, 1, 1⟩, 40), []⟩

/-- The US counts these income sources as unearned income for Supplemental Security Income.
    `gov/ssa/ssi/income/sources/unearned.yaml` (policyengine-us).
    * United States Code of Federal Regulations, Title 20, Subsection 416.1121:
      https://www.law.cornell.edu/cfr/text/20/416.1121 -/
def ssa.ssi.income.sources.unearned : DatedParam (List String) :=
  ⟨(⟨1975, 1, 1⟩, ["pension_income",
      "social_security",
      "disability_benefits",
      "veterans_benefits",
      "survivor_benefits",
      "workers_compensation",
      "unemployment_compensation",
      "retirement_distributions",
      "gi_cash_assistance",
      "alimony_income",
      "child_support_received",
      "financial_assistance",
      "dividend_income",
      "interest_income",
      "rental_income"]), []⟩

/-- The US indexes Social Security benefits (OASDI and SSI) according to this schedule, annually
    updating based on CPI-W in the third quarter of the prior year.
    `gov/ssa/uprating.yaml` (policyengine-us).
    * Historical values:
      https://www.ssa.gov/oact/cola/colaseries.html
    * CBO Economic Projections, February 2024.:
      https://www.cbo.gov/publication/59710 -/
def ssa.uprating : DatedParam USD :=
  ⟨(⟨2022, 1, 1⟩, mkRat 268421 1000),
    [(⟨2023, 1, 1⟩, mkRat 291901 1000),
     (⟨2024, 1, 1⟩, mkRat 75309 250),
     (⟨2025, 1, 1⟩, mkRat 308729 1000),
     (⟨2026, 1, 1⟩, mkRat 63453 200),
     (⟨2027, 1, 1⟩, mkRat 326149 1000),
     (⟨2028, 1, 1⟩, mkRat 332241 1000),
     (⟨2029, 1, 1⟩, mkRat 339431 1000),
     (⟨2030, 1, 1⟩, mkRat 346917 1000),
     (⟨2031, 1, 1⟩, mkRat 1773 5),
     (⟨2032, 1, 1⟩, mkRat 362579 1000),
     (⟨2033, 1, 1⟩, mkRat 46332 125),
     (⟨2034, 1, 1⟩, mkRat 94757 250),
     (⟨2035, 1, 1⟩, mkRat 193799 500)]⟩

end Lawlib.Parameters
