/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Parameters
open Lawlib

/-- Arkansas requires adults within these age brackets to meet this Medicaid work requirement
    approximation under the Arkansas Works program.
    `gov/states/ar/dhs/medicaid/work_requirements/age_range.yaml` (policyengine-us).
    * State Data for Medicaid Work Requirements in Arkansas | KFF:
      https://www.kff.org/medicaid/issue-brief/state-data-for-medicaid-work-requirements-in-arkansas/
    * State Annual Report January-December 2018 | Arkansas Works Section 1115:
      https://www.medicaid.gov/Medicaid-CHIP-Program-Information/By-Topics/Waivers/1115/downloads/ar/Health-Care-Independence-Program-Private-Option/ar-works-annl-rpt-jan-dec-2018.pdf#page=11 -/
def states.ar.dhs.medicaid.work_requirements.age_range : Scale :=
  ⟨[⟨⟨(⟨2018, 1, 1⟩, 0), []⟩, ⟨(⟨2018, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2018, 1, 1⟩, 30), []⟩, ⟨(⟨2018, 1, 1⟩, 1), []⟩⟩,
    ⟨⟨(⟨2018, 1, 1⟩, 50), []⟩, ⟨(⟨2018, 1, 1⟩, 0), []⟩⟩]⟩

/-- Arkansas limits Medicaid expansion coverage to adults who meet a work requirement under the
    Arkansas Works program, if this is true.
    `gov/states/ar/dhs/medicaid/work_requirements/applies.yaml` (policyengine-us).
    * Arkansas Works | Medicaid:
      https://www.medicaid.gov/medicaid/section-1115-demo/demonstration-and-waiver-list/81021
    * State Annual Report January-December 2018 | Arkansas Works Section 1115:
      https://www.medicaid.gov/Medicaid-CHIP-Program-Information/By-Topics/Waivers/1115/downloads/ar/Health-Care-Independence-Program-Private-Option/ar-works-annl-rpt-jan-dec-2018.pdf#page=11 -/
def states.ar.dhs.medicaid.work_requirements.applies : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), [(⟨2018, 1, 1⟩, true), (⟨2020, 1, 1⟩, false)]⟩

/-- Arkansas exempts adults caring for a dependent child at or below this age from the Medicaid
    work requirement approximation under the Arkansas Works program.
    `gov/states/ar/dhs/medicaid/work_requirements/dependent_age_limit.yaml` (policyengine-us).
    * Arkansas Works Program Updates | Arkansas Code Rule 016.20.18 Ark. Code R. 003:
      https://www.law.cornell.edu/regulations/arkansas/016-20-18-Ark-Code-R-003
    * State Data for Medicaid Work Requirements in Arkansas | KFF:
      https://www.kff.org/medicaid/issue-brief/state-data-for-medicaid-work-requirements-in-arkansas/ -/
def states.ar.dhs.medicaid.work_requirements.dependent_age_limit : DatedParam Rat :=
  ⟨(⟨2018, 1, 1⟩, 17), []⟩

/-- Arkansas limits the Medicaid work requirement approximation to adults below this share of
    the poverty line under the Arkansas Works program.
    `gov/states/ar/dhs/medicaid/work_requirements/income_limit.yaml` (policyengine-us).
    * State Data for Medicaid Work Requirements in Arkansas | KFF:
      https://www.kff.org/medicaid/issue-brief/state-data-for-medicaid-work-requirements-in-arkansas/
    * State Annual Report January-December 2018 | Arkansas Works Section 1115:
      https://www.medicaid.gov/Medicaid-CHIP-Program-Information/By-Topics/Waivers/1115/downloads/ar/Health-Care-Independence-Program-Private-Option/ar-works-annl-rpt-jan-dec-2018.pdf#page=11 -/
def states.ar.dhs.medicaid.work_requirements.income_limit : DatedParam Rate :=
  ⟨(⟨2018, 1, 1⟩, 1), [(⟨2019, 1, 1⟩, mkRat 69 50)]⟩

/-- Arkansas limits Medicaid expansion coverage to adults completing at least this number of
    monthly work or community engagement hours under the Arkansas Works program.
    `gov/states/ar/dhs/medicaid/work_requirements/monthly_hours_threshold.yaml` (policyengine-us).
    * State Annual Report January-December 2018 | Arkansas Works Section 1115:
      https://www.medicaid.gov/Medicaid-CHIP-Program-Information/By-Topics/Waivers/1115/downloads/ar/Health-Care-Independence-Program-Private-Option/ar-works-annl-rpt-jan-dec-2018.pdf#page=11
    * An Early Look at Implementation of Medicaid Work Requirements in Arkansas | KFF:
      https://www.kff.org/medicaid/issue-brief/an-early-look-at-implementation-of-medicaid-work-requirements-in-arkansas/ -/
def states.ar.dhs.medicaid.work_requirements.monthly_hours_threshold : DatedParam Rat :=
  ⟨(⟨2018, 1, 1⟩, 80), []⟩

end Lawlib.Parameters
