/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- The US levies payroll taxes on earnings greater than this amount, in addition to earnings below the maximum taxable amount under current law.
    `gov/contrib/cbo/payroll/secondary_earnings_threshold.yaml` (policyengine-us).
    * Increase the Maximum Taxable Earnings That Are Subject to Social Security Payroll Taxes, option alternative 2: https://www.cbo.gov/budget-options/58630 -/
def gov.contrib.cbo.payroll.secondary_earnings_threshold : DatedParam ExtRat :=
  ⟨(⟨2021, 1, 1⟩, .posInf), []⟩

end Lawlib.Gen.Params
