/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- The CDCTC single parent work requirement reform is in effect.
    `gov/contrib/cdcc/single_parent_work_requirement/in_effect.yaml` (policyengine-us). -/
def gov.contrib.cdcc.single_parent_work_requirement.in_effect : DatedParam Bool :=
  ⟨(⟨1, 1, 1⟩, false), []⟩

end Lawlib.Gen.Params
