/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Senator Michael Bennet proposed a child tax credit with a baby bonus of this percentage of the base amount, in the first month of the child's life.
    `gov/contrib/congress/afa/ctc/amount/baby_bonus.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=3 -/
def gov.contrib.congress.afa.ctc.amount.baby_bonus : DatedParam Rate :=
  ⟨(⟨2025, 1, 1⟩, 8), []⟩

/-- Senator Michael Bennet proposed a child tax credit of this base amount.
    `gov/contrib/congress/afa/ctc/amount/base.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=2 -/
def gov.contrib.congress.afa.ctc.amount.base : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 3600), []⟩

/-- Senator Michael Bennet proposed a child tax credit with a multiplier of this amount of the base amount, based on the child's age.
    `gov/contrib/congress/afa/ctc/amount/multiplier.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=2 -/
def gov.contrib.congress.afa.ctc.amount.multiplier : Scale :=
  ⟨[⟨⟨(⟨2025, 1, 1⟩, 0), []⟩, ⟨(⟨2025, 1, 1⟩, mkRat 6 5), []⟩⟩,
    ⟨⟨(⟨2025, 1, 1⟩, 6), []⟩, ⟨(⟨2025, 1, 1⟩, 1), []⟩⟩,
    ⟨⟨(⟨2025, 1, 1⟩, 18), []⟩, ⟨(⟨2025, 1, 1⟩, 0), []⟩⟩]⟩

/-- Senator Michael Bennet proposed a child tax credit and other dependent credit which phase out by this amount for each increment by which one's income exceeds the phase-out thresholds.
    `gov/contrib/congress/afa/ctc/phase_out/amount.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=28 -/
def gov.contrib.congress.afa.ctc.phase_out.amount : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 50), []⟩

/-- Senator Michael Bennet proposed a child tax credit and other dependent credit which phase out by a certain amount for each increment by which one's income exceeds the phase-out thresholds.
    `gov/contrib/congress/afa/ctc/phase_out/increment.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=28 -/
def gov.contrib.congress.afa.ctc.phase_out.increment : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 1000), []⟩

/-- Senator Michael Bennet proposed a child tax credit which is partially reduced to this amount beginning at the lower threshold before being fully phased out at the higher threshold.
    `gov/contrib/congress/afa/ctc/phase_out/lower_floor.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=3 -/
def gov.contrib.congress.afa.ctc.phase_out.lower_floor : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 2000), []⟩

/-- Senator Michael Bennet proposed an other dependent credit which phases out fully for filers with AGI above these thresholds, based on filing status.
    `gov/contrib/congress/afa/ctc/phase_out/threshold/higher.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=5 -/
def gov.contrib.congress.afa.ctc.phase_out.threshold.higher.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 300000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.higher.JOINT : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 400000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.higher.SEPARATE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 200000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.higher.SINGLE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 300000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.higher.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 400000), []⟩

/-- Senator Michael Bennet proposed a child tax credit which phases out partially for filers with AGI above these thresholds, based on filing status.
    `gov/contrib/congress/afa/ctc/phase_out/threshold/lower.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=5 -/
def gov.contrib.congress.afa.ctc.phase_out.threshold.lower.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 112500), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.lower.JOINT : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 150000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.lower.SEPARATE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 75000), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.lower.SINGLE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 112500), []⟩
def gov.contrib.congress.afa.ctc.phase_out.threshold.lower.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 150000), []⟩

/-- Senator Michael Bennet's American Family Act of 2025 applies if this is true.
    `gov/contrib/congress/afa/in_effect.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf -/
def gov.contrib.congress.afa.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Senator Michael Bennet proposed a nonrefundable other dependent credit for each qualifying child of this amount.
    `gov/contrib/congress/afa/other_dependent_credit/amount.yaml` (policyengine-us).
    * American Family Act of 2025: https://www.bennet.senate.gov/wp-content/uploads/2025/04/American-Family-Act-2025.pdf#page=28 -/
def gov.contrib.congress.afa.other_dependent_credit.amount : DatedParam USD :=
  ⟨(⟨2025, 1, 1⟩, 500), []⟩

/-- The Child Tax Credit increases by this amount for newborns, above the normal amount for young children.
    `gov/contrib/congress/delauro/american_family_act/baby_bonus.yaml` (policyengine-us).
    * American Family Act of 2023: https://delauro.house.gov/sites/evo-subsites/delauro.house.gov/files/evo-media-document/delaur_017_xml.pdf#page=3 -/
def gov.contrib.congress.delauro.american_family_act.baby_bonus : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- Representative Jared Golden capped his proposed monthly family income supplement at this fraction of adjusted gross income in the prior tax year.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/agi_fraction.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(4): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=7 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.agi_fraction : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, 1), []⟩

/-- Representative Jared Golden proposed a family income supplement of this amount for each child, based on age.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/amount/base.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(2): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=6 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.amount.base : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 8000), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 1), []⟩, ⟨(⟨2026, 1, 1⟩, 4800), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 6), []⟩, ⟨(⟨2026, 1, 1⟩, 3000), []⟩⟩]⟩

/-- Representative Jared Golden proposed a family income supplement of this amount for pregnant women.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/amount/pregnancy.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(1): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=5 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.amount.pregnancy : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 3200), []⟩

/-- Representative Jared Golden proposed a family income supplement which is limited to caregivers of this age or older.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/caregiver_age_threshold.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (b)(2)(A)(i): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=4 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.caregiver_age_threshold : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 18), []⟩

/-- Representative Jared Golden proposed a family income supplement which is limited to children under this age.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/child_age_limit.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (b)(1)(A): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=4 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.child_age_limit : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 18), []⟩

/-- Representative Jared Golden proposed a family income supplement with a marriage bonus of this percentage of the total credit.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/marriage_bonus_rate.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(2): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=6 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.marriage_bonus_rate : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 1 5), []⟩

/-- Representative Jared Golden proposed a family income supplement which is phased out at this rate for joint filers, based on adjusted gross income.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/phase_out/joint.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(3)(A): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=6 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.phase_out.joint : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 250000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 5), []⟩⟩]⟩

/-- Representative Jared Golden proposed a family income supplement which is phased out at this rate for non-joint filers, based on adjusted gross income.
    `gov/contrib/congress/golden/fisc_act/family_income_supplement/phase_out/other.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act, Sec. 2, (d)(3)(A): https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf#page=6 -/
def gov.contrib.congress.golden.fisc_act.family_income_supplement.phase_out.other : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 125000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 5), []⟩⟩]⟩

/-- The proposed Family Income Supplemental Credit Act applies if this is true.
    `gov/contrib/congress/golden/fisc_act/in_effect.yaml` (policyengine-us).
    * Family Income Supplemental Credit Act: https://golden.house.gov/sites/evo-subsites/golden.house.gov/files/evo-media-document/GoldenFISC.pdf -/
def gov.contrib.congress.golden.fisc_act.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The American Worker Rebate Act, proposed by Senator Josh Hawley, provides this multiple of the non-joint rebate amount for joint filers.
    `gov/contrib/congress/hawley/awra/amount/joint_multiplier.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf#page=2 -/
def gov.contrib.congress.hawley.awra.amount.joint_multiplier : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 2), []⟩

/-- The American Worker Rebate Act, proposed by Senator Josh Hawley, provides this amount for non-joint filers.
    `gov/contrib/congress/hawley/awra/amount/non_joint.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf#page=2 -/
def gov.contrib.congress.hawley.awra.amount.non_joint : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩

/-- The tax rebate, proposed by the American Worker Rebate Act, is limited to filers of the following immigration statuses.
    `gov/contrib/congress/hawley/awra/eligible_immigration_statuses.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf#page=4 -/
def gov.contrib.congress.hawley.awra.eligible_immigration_statuses : DatedParam (List String) :=
  ⟨(⟨0, 1, 1⟩, ["CITIZEN", "LEGAL_PERMANENT_RESIDENT"]), []⟩

/-- The American Worker Rebate Act, proposed by Senator Josh Hawley, applies, if this is true.
    `gov/contrib/congress/hawley/awra/in_effect.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf -/
def gov.contrib.congress.hawley.awra.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The tax rebate, proposed by the American Worker Rebate Act, phases out at this rate of adjusted gross income above the phase-out start.
    `gov/contrib/congress/hawley/awra/phase_out/rate.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf#page=4 -/
def gov.contrib.congress.hawley.awra.phase_out.rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, mkRat 1 20), []⟩

/-- The tax rebate, proposed by the American Worker Rebate Act, phases out the rebate for filers with adjusted gross income above this threshold, based on filing status.
    `gov/contrib/congress/hawley/awra/phase_out/start.yaml` (policyengine-us).
    * American Worker Rebate Act: https://www.hawley.senate.gov/wp-content/uploads/2025/07/Hawley-American-Worker-Rebate-Act-Bill-Text.pdf#page=4 -/
def gov.contrib.congress.hawley.awra.phase_out.start.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 112500), []⟩
def gov.contrib.congress.hawley.awra.phase_out.start.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 150000), []⟩
def gov.contrib.congress.hawley.awra.phase_out.start.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 75000), []⟩
def gov.contrib.congress.hawley.awra.phase_out.start.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 75000), []⟩
def gov.contrib.congress.hawley.awra.phase_out.start.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 75000), []⟩

/-- The Working Parents Tax Relief Act increases the EITC credit percentage by this amount for filers with one qualifying child who has not attained age 4.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/credit_percentage_increase_one_child.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.credit_percentage_increase_one_child : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 264 625), []⟩

/-- The Working Parents Tax Relief Act increases the EITC credit percentage by this amount per qualifying young child for filers with two or more qualifying children.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/credit_percentage_increase_per_young_child.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.credit_percentage_increase_per_young_child : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 3007 10000), []⟩

/-- The Working Parents Tax Relief Act uses this indicator to determine whether the EITC enhancement for parents of young children is in effect.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/in_effect.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Working Parents Tax Relief Act limits the EITC percentage bonus to this many qualifying young children.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/max_young_children.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.max_young_children : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, 3), []⟩

/-- The Working Parents Tax Relief Act increases the EITC phaseout percentage by this amount per qualifying young child.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/phaseout_percentage_increase_per_young_child.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.phaseout_percentage_increase_per_young_child : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 1 20), []⟩

/-- The Working Parents Tax Relief Act sets this age as the threshold below which qualifying children receive the EITC enhancement.
    `gov/contrib/congress/mcdonald_rivet/working_parents_tax_relief_act/young_child_age_threshold.yaml` (policyengine-us).
    * IRC §32(b) - Percentages and amounts (baseline structure being amended): https://www.law.cornell.edu/uscode/text/26/32#b -/
def gov.contrib.congress.mcdonald_rivet.working_parents_tax_relief_act.young_child_age_threshold : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 4), []⟩

/-- The head of household filing status will be eliminated if this is true.
    `gov/contrib/congress/romney/family_security_act/remove_head_of_household.yaml` (policyengine-us).
    * Family Security Act: https://cdn.vox-cdn.com/uploads/chorus_asset/file/22279576/family_security_act_one_pager_appendix.pdf -/
def gov.contrib.congress.romney.family_security_act.remove_head_of_household : DatedParam Bool :=
  ⟨(⟨2000, 1, 1⟩, false), []⟩

/-- Under the Family Security Act 3.0, senator Mitt Romney proposed the following pregnant mothers credit amount for newborn children.
    `gov/contrib/congress/romney/family_security_act_2024/pregnant_mothers_credit/amount.yaml` (policyengine-us).
    * Family Security Act 3.0: https://www.romney.senate.gov/wp-content/uploads/2024/09/FSA-Scanned-and-Final.pdf#page=15 -/
def gov.contrib.congress.romney.family_security_act_2024.pregnant_mothers_credit.amount : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 1), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩]⟩

/-- Senator Mitt Romney proposed phasing in the Pregnant Mothers Tax Credit linearly from zero to this earnings level under the Family Security Act 3.0.
    `gov/contrib/congress/romney/family_security_act_2024/pregnant_mothers_credit/income_phase_in_end.yaml` (policyengine-us).
    * Family Security Act 3.0: https://www.romney.senate.gov/wp-content/uploads/2024/09/FSA-Scanned-and-Final.pdf#page=16 -/
def gov.contrib.congress.romney.family_security_act_2024.pregnant_mothers_credit.income_phase_in_end : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 0), []⟩

/-- Senator Mitt Romney proposed structural changes to the Child Tax Credit in the Family Security Act 2.0, which apply if this is true.
    `gov/contrib/congress/romney/family_security_act_2_0/ctc/apply_ctc_structure.yaml` (policyengine-us). -/
def gov.contrib.congress.romney.family_security_act_2_0.ctc.apply_ctc_structure : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Senator Mitt Romney proposed providing the following Child Tax Credit amount per child under the Family Security Act 2.0, based on age.
    `gov/contrib/congress/romney/family_security_act_2_0/ctc/base.yaml` (policyengine-us). -/
def gov.contrib.congress.romney.family_security_act_2_0.ctc.base : Scale :=
  ⟨[⟨⟨(⟨2022, 1, 1⟩, 0), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2022, 1, 1⟩, 6), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2022, 1, 1⟩, 18), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩]⟩

/-- Senator Mitt Romney proposed limiting the Child Tax Credit to this number of children per filer under the Family Security Act 2.0.
    `gov/contrib/congress/romney/family_security_act_2_0/ctc/child_cap.yaml` (policyengine-us).
    * Family Security Act 2.0: https://www.romney.senate.gov/wp-content/uploads/2022/06/family-security-act-2.0_one-pager_appendix.pdf -/
def gov.contrib.congress.romney.family_security_act_2_0.ctc.child_cap : DatedParam Rat :=
  ⟨(⟨2022, 1, 1⟩, 0), []⟩

/-- Senator Mitt Romney proposed phasing in the Child Tax Credit linearly from zero to this earnings level under the Family Security Act 2.0.
    `gov/contrib/congress/romney/family_security_act_2_0/ctc/phase_in/income_phase_in_end.yaml` (policyengine-us).
    * Family Security Act 2.0: https://www.romney.senate.gov/wp-content/uploads/2022/06/family-security-act-2.0_one-pager_appendix.pdf -/
def gov.contrib.congress.romney.family_security_act_2_0.ctc.phase_in.income_phase_in_end : DatedParam USD :=
  ⟨(⟨2022, 1, 1⟩, 0), []⟩

/-- Under the Family Security Act 2.0, this maximum EITC amount is provided for joint filers, based on number of children.
    `gov/contrib/congress/romney/family_security_act_2_0/eitc/amount/joint.yaml` (policyengine-us).
    * Family Security Act 2.0: https://www.romney.senate.gov/wp-content/uploads/2022/06/family-security-act-2.0_one-pager_appendix.pdf -/
def gov.contrib.congress.romney.family_security_act_2_0.eitc.amount.joint : Scale :=
  ⟨[⟨⟨(⟨2022, 1, 1⟩, 0), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2022, 1, 1⟩, 1), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩]⟩

/-- Under the Family Security Act 2.0, this maximum EITC amount is provided for single filers, based on number of children.
    `gov/contrib/congress/romney/family_security_act_2_0/eitc/amount/single.yaml` (policyengine-us).
    * Family Security Act 2.0: https://www.romney.senate.gov/wp-content/uploads/2022/06/family-security-act-2.0_one-pager_appendix.pdf -/
def gov.contrib.congress.romney.family_security_act_2_0.eitc.amount.single : Scale :=
  ⟨[⟨⟨(⟨2022, 1, 1⟩, 0), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2022, 1, 1⟩, 1), []⟩, ⟨(⟨2022, 1, 1⟩, 0), []⟩⟩]⟩

/-- Senator Mitt Romney proposed structural changes to the Earned Income Tax Credit in the Family Security Act 2.0, which apply if this is true.
    `gov/contrib/congress/romney/family_security_act_2_0/eitc/apply_eitc_structure.yaml` (policyengine-us). -/
def gov.contrib.congress.romney.family_security_act_2_0.eitc.apply_eitc_structure : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The BOOST Act middle class credit is administered through the Social Security Administration if this is true.
    `gov/contrib/congress/tlaib/boost/middle_class_tax_credit/administered_through_ssa.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.boost.middle_class_tax_credit.administered_through_ssa : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act provides this credit amount per qualifying adult dependent.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/adult_dependent_credit/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.adult_dependent_credit.amount : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 700), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act sets this minimum age for adult dependent credit eligibility.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/adult_dependent_credit/min_age.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.adult_dependent_credit.min_age : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 19), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act sets this age as the cutoff for child benefit eligibility.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/child_benefit/age_limit.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.child_benefit.age_limit : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 19), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act provides this filer credit amount by filing status.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/filer_credit/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.amount.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 700), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.amount.JOINT : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 1400), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.amount.SEPARATE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 700), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.amount.SINGLE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 700), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.amount.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 700), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act limits filer credit to those below this age.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/filer_credit/eligibility/max_age.yaml` (policyengine-us).
    * placeholder - bill not yet introduced: placeholder -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.eligibility.max_age : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 65), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act sets this minimum age for filer credit eligibility.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/filer_credit/eligibility/min_age.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.eligibility.min_age : DatedParam Rat :=
  ⟨(⟨2026, 1, 1⟩, 19), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act is phased out at the following rate.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/filer_credit/phase_out/rate.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.rate : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 1 20), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act is phased out for filers with adjusted gross income above this threshold.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/filer_credit/phase_out/start.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.start.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.start.JOINT : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 40000), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.start.SEPARATE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.start.SINGLE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.filer_credit.phase_out.start.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 20000), []⟩

/-- Representative Rashida Tlaib's End Child Poverty Act is in effect when this is true.
    `gov/contrib/congress/tlaib/economic_dignity_for_all_agenda/end_child_poverty_act/in_effect.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.economic_dignity_for_all_agenda.end_child_poverty_act.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Amount of Rep Tlaib's End Child Poverty Act (2022) adult dependent credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/adult_dependent_credit/amount.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.adult_dependent_credit.amount : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 600), []⟩

/-- Minimum age to qualify for Rep Tlaib's End Child Poverty Act (2022) adult dependent credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/adult_dependent_credit/min_age.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.adult_dependent_credit.min_age : DatedParam Rat :=
  ⟨(⟨2023, 1, 1⟩, 19), []⟩

/-- The child benefit component under the End Child Poverty Act is limited to dependents below this age.
    `gov/contrib/congress/tlaib/end_child_poverty_act/child_benefit/age_limit.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.child_benefit.age_limit : DatedParam Rat :=
  ⟨(⟨2023, 1, 1⟩, 19), []⟩

/-- Amount of Rep Tlaib's End Child Poverty Act (2022) filer credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/filer_credit/amount.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.amount.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 600), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.amount.JOINT : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 1200), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.amount.SEPARATE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 600), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.amount.SINGLE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 600), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.amount.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 600), []⟩

/-- Maximum age to qualify for Rep Tlaib's End Child Poverty Act (2022) filer credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/filer_credit/eligibility/max_age.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.eligibility.max_age : DatedParam Rat :=
  ⟨(⟨2023, 1, 1⟩, 64), []⟩

/-- Minimum age to qualify for Rep Tlaib's End Child Poverty Act (2022) filer credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/filer_credit/eligibility/min_age.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.eligibility.min_age : DatedParam Rat :=
  ⟨(⟨2023, 1, 1⟩, 19), []⟩

/-- Phase-out rate for Rep Tlaib's End Child Poverty Act (2022) filer credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/filer_credit/phase_out/rate.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.rate : DatedParam Rate :=
  ⟨(⟨2023, 1, 1⟩, mkRat 1 20), []⟩

/-- Phase-out start for Rep Tlaib's End Child Poverty Act (2022) filer credit
    `gov/contrib/congress/tlaib/end_child_poverty_act/filer_credit/phase_out/start.yaml` (policyengine-us).
    * End Child Poverty Act: https://www.congress.gov/bill/118th-congress/house-bill/2540/text?s=1&r=14 -/
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.start.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.start.JOINT : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 40000), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.start.SEPARATE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.start.SINGLE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 20000), []⟩
def gov.contrib.congress.tlaib.end_child_poverty_act.filer_credit.phase_out.start.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2023, 1, 1⟩, 20000), []⟩

/-- Rep Tlaib's End Child Poverty Act applies if this is true.
    `gov/contrib/congress/tlaib/end_child_poverty_act/in_effect.yaml` (policyengine-us). -/
def gov.contrib.congress.tlaib.end_child_poverty_act.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Working Americans' Tax Cut Act alternative maximum tax rate applied to MAGI above the cost of living exemption.
    `gov/contrib/congress/watca/cost_of_living_exemption/alternative_tax_rate.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 1A(a): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=2 -/
def gov.contrib.congress.watca.cost_of_living_exemption.alternative_tax_rate : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 51 200), []⟩

/-- The Working Americans' Tax Cut Act provides a cost of living exemption amount by filing status, indexed for inflation using CPI-U.
    `gov/contrib/congress/watca/cost_of_living_exemption/amount.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 1A(c): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=3 -/
def gov.contrib.congress.watca.cost_of_living_exemption.amount.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 64400), []⟩
def gov.contrib.congress.watca.cost_of_living_exemption.amount.JOINT : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 92000), []⟩
def gov.contrib.congress.watca.cost_of_living_exemption.amount.SEPARATE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 46000), []⟩
def gov.contrib.congress.watca.cost_of_living_exemption.amount.SINGLE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 46000), []⟩
def gov.contrib.congress.watca.cost_of_living_exemption.amount.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2026, 1, 1⟩, 92000), []⟩

/-- The Working Americans' Tax Cut Act limits eligibility for the alternative maximum tax to filers with MAGI below this multiple of the cost of living exemption amount.
    `gov/contrib/congress/watca/cost_of_living_exemption/income_limit_multiple.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 1A(b)(1): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=2 -/
def gov.contrib.congress.watca.cost_of_living_exemption.income_limit_multiple : DatedParam Rate :=
  ⟨(⟨2026, 1, 1⟩, mkRat 7 4), []⟩

/-- The Working Americans' Tax Cut Act applies if this is true.
    `gov/contrib/congress/watca/in_effect.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 2(c), 3(d): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=4 -/
def gov.contrib.congress.watca.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Working Americans' Tax Cut Act millionaire surtax applies if this is true.
    `gov/contrib/congress/watca/surtax/in_effect.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 3(d): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=8 -/
def gov.contrib.congress.watca.surtax.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, true), []⟩

/-- The Working Americans' Tax Cut Act millionaire surtax rate for joint filers, based on modified AGI.
    `gov/contrib/congress/watca/surtax/rate/joint.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 59B(a), (c): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=5 -/
def gov.contrib.congress.watca.surtax.rate.joint : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 1500000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 20), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 3000000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 10), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 7500000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 3 25), []⟩⟩]⟩

/-- The Working Americans' Tax Cut Act millionaire surtax rate for single filers, based on modified AGI.
    `gov/contrib/congress/watca/surtax/rate/single.yaml` (policyengine-us).
    * Working Americans' Tax Cut Act Section 59B(a): https://www.vanhollen.senate.gov/imo/media/doc/working_americans_tax_cut_act_bill_text.pdf#page=5 -/
def gov.contrib.congress.watca.surtax.rate.single : Scale :=
  ⟨[⟨⟨(⟨2026, 1, 1⟩, 0), []⟩, ⟨(⟨2026, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 1000000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 20), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 2000000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 1 10), []⟩⟩,
    ⟨⟨(⟨2026, 1, 1⟩, 5000000), []⟩, ⟨(⟨2026, 1, 1⟩, mkRat 3 25), []⟩⟩]⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.amount.SINGLE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.amount.SEPARATE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.amount.HEAD_OF_HOUSEHOLD : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.amount.JOINT : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/amount.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.amount.SURVIVING_SPOUSE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- Rate at which the bonus guaranteed deduction reduces with AGI.
    `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/rate.yaml` (policyengine-us).
    * Ways and Means Committee press release: https://waysandmeans.house.gov/malliotakis-steel-lead-legislation-to-provide-tax-relief-to-working-families/ -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.rate : DatedParam Rate :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.threshold.SINGLE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.threshold.SEPARATE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.threshold.HEAD_OF_HOUSEHOLD : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.threshold.JOINT : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- `gov/contrib/congress/wftca/bonus_guaranteed_deduction/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.congress.wftca.bonus_guaranteed_deduction.phase_out.threshold.SURVIVING_SPOUSE : DatedParam Rat :=
  ⟨(⟨2000, 1, 1⟩, 0), []⟩

/-- The US phases in the Additional Child Tax Credit on the greater of current and prior year earnings if this is true.
    `gov/contrib/congress/wyden_smith/actc_lookback.yaml` (policyengine-us).
    * The Tax Relief for American Families and Workers Act of 2024: https://www.finance.senate.gov/imo/media/doc/the_tax_relief_for_american_families_and_workers_act_of_2024_technical_summary.pdf#page=2 -/
def gov.contrib.congress.wyden_smith.actc_lookback : DatedParam Bool :=
  ⟨(⟨2020, 1, 1⟩, false), []⟩

/-- The US phases in the Additional Child Tax Credit on a per child basis if this is true.
    `gov/contrib/congress/wyden_smith/per_child_actc_phase_in.yaml` (policyengine-us).
    * The Tax Relief for American Families and Workers Act of 2024: https://www.finance.senate.gov/imo/media/doc/the_tax_relief_for_american_families_and_workers_act_of_2024_technical_summary.pdf#page=2 -/
def gov.contrib.congress.wyden_smith.per_child_actc_phase_in : DatedParam Bool :=
  ⟨(⟨2000, 1, 1⟩, false), []⟩

end Lawlib.Gen.Params
