/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- The senior deduction is extended beyond tax year 2028 if this is true.
    `gov/contrib/crfb/senior_deduction_extension/applies.yaml` (policyengine-us). -/
def gov.contrib.crfb.senior_deduction_extension.applies : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Committee for a Responsible Federal Budget proposes to replace the additional senior deduction with a nonrefundable credit of this amount to offset taxes from Social Security benefits.
    `gov/contrib/crfb/ss_credit/amount.yaml` (policyengine-us). -/
def gov.contrib.crfb.ss_credit.amount.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩
def gov.contrib.crfb.ss_credit.amount.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩
def gov.contrib.crfb.ss_credit.amount.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩
def gov.contrib.crfb.ss_credit.amount.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩
def gov.contrib.crfb.ss_credit.amount.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 600), []⟩

/-- The Committee for a Responsible Federal Budget's proposed replacement of the additional senior deduction with a nonrefundable credit to offset taxes from Social Security benefits is active if this is true.
    `gov/contrib/crfb/ss_credit/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.ss_credit.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Committee for a Responsible Federal Budget's proposed replacement of the additional senior deduction with a nonrefundable credit which is phased out if this is true.
    `gov/contrib/crfb/ss_credit/phase_out/applies.yaml` (policyengine-us). -/
def gov.contrib.crfb.ss_credit.phase_out.applies : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Committee for a Responsible Federal Budget proposes to replace the additional senior deduction with a nonrefundable credit which is phased out at this rate for joint filers.
    `gov/contrib/crfb/ss_credit/phase_out/rate/joint.yaml` (policyengine-us). -/
def gov.contrib.crfb.ss_credit.phase_out.rate.joint : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 150000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 3 50), []⟩⟩]⟩

/-- The Committee for a Responsible Federal Budget proposes to replace the additional senior deduction with a nonrefundable credit which is phased out at this rate for non-joint filers.
    `gov/contrib/crfb/ss_credit/phase_out/rate/other.yaml` (policyengine-us). -/
def gov.contrib.crfb.ss_credit.phase_out.rate.other : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 75000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 3 50), []⟩⟩]⟩

/-- The Committee for a Responsible Federal Budget's proposed a surtax on adjusted gross income which applies, if this is true.
    `gov/contrib/crfb/surtax/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.surtax.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Committee for a Responsible Federal Budget's proposed a surtax on adjusted gross income which is increased by other income sources, if this is true.
    `gov/contrib/crfb/surtax/increased_base/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.surtax.increased_base.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Additional income sources for CRFB surtax expanded base beyond IRS gross income.
    `gov/contrib/crfb/surtax/increased_base/sources.yaml` (policyengine-us). -/
def gov.contrib.crfb.surtax.increased_base.sources : DatedParam (List String) :=
  ⟨(⟨2010, 1, 1⟩, ["traditional_ira_contributions", "traditional_401k_contributions", "traditional_403b_contributions", "health_savings_account_ald", "student_loan_interest_ald", "tax_exempt_social_security", "foreign_earned_income_exclusion", "tax_exempt_interest_income", "health_insurance_premiums"]), []⟩

/-- The Committee for a Responsible Federal Budget proposes a surtax on adjusted gross income which applies at this rate for joint filers, based on adjusted gross income.
    `gov/contrib/crfb/surtax/rate/joint.yaml` (policyengine-us). -/
def gov.contrib.crfb.surtax.rate.joint : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 200000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 1 100), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 1000000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 1 50), []⟩⟩]⟩

/-- The Committee for a Responsible Federal Budget proposes a surtax on adjusted gross income which applies at this rate for single filers, based on adjusted gross income.
    `gov/contrib/crfb/surtax/rate/single.yaml` (policyengine-us). -/
def gov.contrib.crfb.surtax.rate.single : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 100000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 1 100), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 1000000), []⟩, ⟨(⟨0, 1, 1⟩, mkRat 1 50), []⟩⟩]⟩

/-- Employer side Medicare taxes are added to gross income, if this is true.
    `gov/contrib/crfb/tax_employer_medicare_tax/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.tax_employer_medicare_tax.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Employer side payroll taxes--Social Security and Medicare--are added to gross income, if this is true.
    `gov/contrib/crfb/tax_employer_payroll_tax/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.tax_employer_payroll_tax.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The following percentage of employer-side payroll taxes are included in gross income.
    `gov/contrib/crfb/tax_employer_payroll_tax/percentage.yaml` (policyengine-us). -/
def gov.contrib.crfb.tax_employer_payroll_tax.percentage : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 1), []⟩

/-- Employer side Social Security taxes are added to gross income, if this is true.
    `gov/contrib/crfb/tax_employer_social_security_tax/in_effect.yaml` (policyengine-us). -/
def gov.contrib.crfb.tax_employer_social_security_tax.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

end Lawlib.Gen.Params
