/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- The IRS provides a maximum ACTC of this amount with an additional bracket, depending on the child's age.
    `gov/contrib/ctc/additional_bracket/amount/actc.yaml` (policyengine-us). -/
def gov.contrib.ctc.additional_bracket.amount.actc : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 6), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 17), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩]⟩

/-- The IRS provides a maximum Child Tax Credit of this amount with an additional bracket, depending on the child's age.
    `gov/contrib/ctc/additional_bracket/amount/base.yaml` (policyengine-us). -/
def gov.contrib.ctc.additional_bracket.amount.base : Scale :=
  ⟨[⟨⟨(⟨0, 1, 1⟩, 0), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 6), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨0, 1, 1⟩, 17), []⟩, ⟨(⟨0, 1, 1⟩, 0), []⟩⟩]⟩

/-- An expanded Child Tax Credit bracket is applied, if this is true.
    `gov/contrib/ctc/additional_bracket/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.additional_bracket.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The CTC fully phases out at this income, by filing status.
    `gov/contrib/ctc/linear_phase_out/end.yaml` (policyengine-us). -/
def gov.contrib.ctc.linear_phase_out.end.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 240000), []⟩
def gov.contrib.ctc.linear_phase_out.end.JOINT : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 440000), []⟩
def gov.contrib.ctc.linear_phase_out.end.SEPARATE : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 175000), []⟩
def gov.contrib.ctc.linear_phase_out.end.SINGLE : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 240000), []⟩
def gov.contrib.ctc.linear_phase_out.end.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 440000), []⟩

/-- The CTC linear phase-out reform is in effect if this is true.
    `gov/contrib/ctc/linear_phase_out/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.linear_phase_out.in_effect : DatedParam Bool :=
  ⟨(⟨2020, 1, 1⟩, false), []⟩

/-- Minimum refundable amount per child for the CTC, exempt from phase-in but subject to phase-out
    `gov/contrib/ctc/minimum_refundable/amount.yaml` (policyengine-us). -/
def gov.contrib.ctc.minimum_refundable.amount : Scale :=
  ⟨[⟨⟨(⟨2024, 1, 1⟩, 0), []⟩, ⟨(⟨2024, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2024, 1, 1⟩, 6), []⟩, ⟨(⟨2024, 1, 1⟩, 0), []⟩⟩]⟩

/-- Whether the CTC minimum refundable amount reform is in effect
    `gov/contrib/ctc/minimum_refundable/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.minimum_refundable.in_effect : DatedParam Bool :=
  ⟨(⟨2020, 1, 1⟩, false), []⟩

/-- An increased Child Tax Credit of this amount is provided to the oldest child in a household.
    `gov/contrib/ctc/oldest_child_supplement/amount.yaml` (policyengine-us). -/
def gov.contrib.ctc.oldest_child_supplement.amount : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- An increased Child Tax Credit amount is provided to the oldest child in a household, if this is true.
    `gov/contrib/ctc/oldest_child_supplement/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.oldest_child_supplement.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Child Tax Credit is phased-in per qualifying child in the household, if this is true.
    `gov/contrib/ctc/per_child_phase_in/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.per_child_phase_in.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Prevent overlap between regular and ARPA CTC phase-outs by subtracting ARPA phase-out amount from regular phase-out calculation.
    `gov/contrib/ctc/per_child_phase_out/avoid_overlap.yaml` (policyengine-us). -/
def gov.contrib.ctc.per_child_phase_out.avoid_overlap : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The Child Tax Credit is phased-out per qualifying child in the household, if this is true.
    `gov/contrib/ctc/per_child_phase_out/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ctc.per_child_phase_out.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

end Lawlib.Gen.Params
