/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Flat refundable credit amount per CTC-qualifying child in the tax unit under the refundable credit conversion reform.
    `gov/contrib/refundable_credit_conversion/credit/per_ctc_dependent.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.per_ctc_dependent : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Flat refundable credit amount per tax filing unit (household credit) under the refundable credit conversion reform.
    `gov/contrib/refundable_credit_conversion/credit/per_household.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.per_household : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Provides this flat refundable credit per tax-unit dependent who does not also meet the CTC definition.
    `gov/contrib/refundable_credit_conversion/credit/per_other_dependent.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.per_other_dependent : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Flat refundable credit amount per taxpayer (head of tax unit and spouse if filing jointly) under the refundable credit conversion reform.
    `gov/contrib/refundable_credit_conversion/credit/per_taxpayer.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.per_taxpayer : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Apply the per-CTC-qualifying-dependent flat credit. When false, the per_ctc_dependent amount is ignored.
    `gov/contrib/refundable_credit_conversion/credit/use_ctc_dependent_credit.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.use_ctc_dependent_credit : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Apply the per-tax-unit (household) flat credit. When false, the per-household amount is ignored.
    `gov/contrib/refundable_credit_conversion/credit/use_household_credit.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.use_household_credit : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Apply the per-other-dependent flat credit, which counts tax-unit dependents who do NOT meet the CTC definition. When false, the per_other_dependent amount is ignored.
    `gov/contrib/refundable_credit_conversion/credit/use_other_dependent_credit.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.use_other_dependent_credit : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Apply the per-taxpayer flat credit (each head of tax unit and spouse if filing jointly). When false, the per-taxpayer amount is ignored.
    `gov/contrib/refundable_credit_conversion/credit/use_taxpayer_credit.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.credit.use_taxpayer_credit : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Per-worker cap on earnings counted for the refundable credit conversion reform's earnings credit. The credit per worker equals min(earnings, cap) times the earnings credit rate.
    `gov/contrib/refundable_credit_conversion/earnings_credit/cap.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.earnings_credit.cap : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Rate at which earnings are credited under the refundable credit conversion reform's earnings credit. Applied to each worker's earnings up to the per-worker cap. "Earnings" follows the EITC convention of wages plus self-employment income.
    `gov/contrib/refundable_credit_conversion/earnings_credit/rate.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.earnings_credit.rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Apply the per-earner refundable earnings subsidy (rate times capped earnings, summed across earners in the tax unit). When false, the earnings credit is zero regardless of the rate or cap parameters.
    `gov/contrib/refundable_credit_conversion/earnings_credit/use_earnings_credit.yaml` (policyengine-us). -/
def gov.contrib.refundable_credit_conversion.earnings_credit.use_earnings_credit : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The refundable credit conversion contrib reform is in effect when this is true.
    `gov/contrib/refundable_credit_conversion/in_effect.yaml` (policyengine-us).
    * PolicyEngine-US PR: https://github.com/PolicyEngine/policyengine-us/pull/8219 -/
def gov.contrib.refundable_credit_conversion.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

end Lawlib.Gen.Params
