/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- The streamlined EITC reform is in effect if this is true.
    `gov/contrib/streamlined_eitc/in_effect.yaml` (policyengine-us). -/
def gov.contrib.streamlined_eitc.in_effect : DatedParam Bool :=
  ⟨(⟨2020, 1, 1⟩, false), []⟩

/-- The EITC is capped at this amount for joint filers, based on number of children.
    `gov/contrib/streamlined_eitc/max/joint.yaml` (policyengine-us). -/
def gov.contrib.streamlined_eitc.max.joint : Scale :=
  ⟨[⟨⟨(⟨2020, 1, 1⟩, 0), []⟩, ⟨(⟨2020, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2020, 1, 1⟩, 1), []⟩, ⟨(⟨2020, 1, 1⟩, 4993), []⟩⟩]⟩

/-- The EITC is capped at this amount for single and head of household filers, based on number of children.
    `gov/contrib/streamlined_eitc/max/single.yaml` (policyengine-us). -/
def gov.contrib.streamlined_eitc.max.single : Scale :=
  ⟨[⟨⟨(⟨2020, 1, 1⟩, 0), []⟩, ⟨(⟨2020, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2020, 1, 1⟩, 1), []⟩, ⟨(⟨2020, 1, 1⟩, 3995), []⟩⟩]⟩

end Lawlib.Gen.Params
