/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean params` (design §5).
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale

namespace Lawlib.Gen.Params
open Lawlib

/-- Tax units are eligible for basic income payments unless their adjusted gross income exceeds this threshold.
    `gov/contrib/ubi_center/basic_income/agi_limit/amount.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.agi_limit.amount.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.agi_limit.amount.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.agi_limit.amount.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.agi_limit.amount.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.agi_limit.amount.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Basic income is limited to tax units below an AGI level if this switch is activated.
    `gov/contrib/ubi_center/basic_income/agi_limit/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.agi_limit.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Basic income amounts by age.
    `gov/contrib/ubi_center/basic_income/amount/person/by_age.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.amount.person.by_age : Scale :=
  ⟨[⟨⟨(⟨2010, 1, 1⟩, 0), []⟩, ⟨(⟨2010, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2010, 1, 1⟩, 6), []⟩, ⟨(⟨2010, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2010, 1, 1⟩, 18), []⟩, ⟨(⟨2010, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2010, 1, 1⟩, 25), []⟩, ⟨(⟨2010, 1, 1⟩, 0), []⟩⟩,
    ⟨⟨(⟨2010, 1, 1⟩, 65), []⟩, ⟨(⟨2010, 1, 1⟩, 0), []⟩⟩]⟩

/-- Payment to individuals with SSI-qualifying disabilities.
    `gov/contrib/ubi_center/basic_income/amount/person/disability.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.amount.person.disability : DatedParam USD :=
  ⟨(⟨2020, 1, 1⟩, 0), []⟩

/-- Basic income amount.
    `gov/contrib/ubi_center/basic_income/amount/person/flat.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.amount.person.flat : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- The following bonus is provided to married couples as a percentage of their basic income amount.
    `gov/contrib/ubi_center/basic_income/amount/person/marriage_bonus.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.amount.person.marriage_bonus : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- A basic income is provided to tax units at this percentage of the federal poverty guideline
    `gov/contrib/ubi_center/basic_income/amount/tax_unit/fpg_percent.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.amount.tax_unit.fpg_percent : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Basic income is phased in if this is true.
    `gov/contrib/ubi_center/basic_income/phase_in/in_effect.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_in.in_effect : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Social Security benefits are treated as earnings under the basic income phase in if this is selected.
    `gov/contrib/ubi_center/basic_income/phase_in/include_ss_benefits_as_earnings.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_in.include_ss_benefits_as_earnings : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Basic incomes phase in per person if this is selected; otherwise, they phase in at a flat rate irrespective of household size.
    `gov/contrib/ubi_center/basic_income/phase_in/per_person.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_in.per_person : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The basic income phases in at this rate.
    `gov/contrib/ubi_center/basic_income/phase_in/rate.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_in.rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 1), []⟩

/-- Basic incomes phase out as a rate above a threshold if this is selected; otherwise, they phase out between the threshold and a phase-out end.
    `gov/contrib/ubi_center/basic_income/phase_out/by_rate.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_out.by_rate : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, true), []⟩

/-- The basic income phases out for adjusted gross income between the threshold and this value.
    `gov/contrib/ubi_center/basic_income/phase_out/end.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_out.end.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.end.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.end.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.end.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.end.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- The basic income phases out at this rate for tax filers with adjusted gross income above the threshold.
    `gov/contrib/ubi_center/basic_income/phase_out/rate.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_out.rate : DatedParam Rate :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- The basic income phases out for adjusted gross income above this value.
    `gov/contrib/ubi_center/basic_income/phase_out/threshold.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.phase_out.threshold.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.threshold.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.threshold.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.threshold.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.basic_income.phase_out.threshold.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Whether the IRS counts basic income in adjusted gross income. If true, this overrides and eliminates all other basic income phase-out parameters.
    `gov/contrib/ubi_center/basic_income/taxable.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.basic_income.taxable : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Abolish all federal income tax liabilities.
    `gov/contrib/ubi_center/flat_tax/abolish_federal_income_tax.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.abolish_federal_income_tax : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Abolish all payroll tax liabilities.
    `gov/contrib/ubi_center/flat_tax/abolish_payroll_tax.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.abolish_payroll_tax : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- Abolish self-employment tax liabilities.
    `gov/contrib/ubi_center/flat_tax/abolish_self_emp_tax.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.abolish_self_emp_tax : DatedParam Bool :=
  ⟨(⟨2000, 1, 1⟩, false), []⟩

/-- Deduct the Premium Tax Credit from the flat tax.
    `gov/contrib/ubi_center/flat_tax/deduct_ptc.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.deduct_ptc : DatedParam Bool :=
  ⟨(⟨0, 1, 1⟩, false), []⟩

/-- The following amount is exempt under the flat AGI tax structure, based on filing status.
    `gov/contrib/ubi_center/flat_tax/exemption/agi.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.exemption.agi.HEAD_OF_HOUSEHOLD : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.flat_tax.exemption.agi.JOINT : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.flat_tax.exemption.agi.SEPARATE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.flat_tax.exemption.agi.SINGLE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩
def gov.contrib.ubi_center.flat_tax.exemption.agi.SURVIVING_SPOUSE : DatedParam USD :=
  ⟨(⟨0, 1, 1⟩, 0), []⟩

/-- Flat tax rate applied to federal adjusted gross income.
    `gov/contrib/ubi_center/flat_tax/rate/agi.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.rate.agi : DatedParam Rate :=
  ⟨(⟨2010, 1, 1⟩, 0), []⟩

/-- Flat tax rate applied to federal gross income.
    `gov/contrib/ubi_center/flat_tax/rate/gross_income.yaml` (policyengine-us). -/
def gov.contrib.ubi_center.flat_tax.rate.gross_income : DatedParam Rate :=
  ⟨(⟨2010, 1, 1⟩, 0), []⟩

end Lawlib.Gen.Params
