/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (design §5).
-/
import Lawlib.Gen.Vars.Trunk.P004

namespace Lawlib.Gen.Vars
open Lawlib Lawlib.Gen

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/homestead/wi_homestead_property_tax.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_homestead_property_tax (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((sumBy t.members fun p => p.core_p2.real_estate_taxes) + ((sumBy t.members fun p => p.core_p2.rent) * (Params.gov.states.wi.tax.income.credits.homestead.property_tax.rent_ratio.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/wi_income_tax_before_refundable_credits.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_income_tax_before_refundable_credits (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (max (0 : Rat) (t.states_wi.wi_income_tax_before_credits - t.states_wi.wi_non_refundable_credits)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/itemized_deduction/wi_itemized_deduction_credit_potential.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_itemized_deduction_credit_potential (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((max (0 : Rat) (t.irs.itemized_deductions_less_salt - t.states_wi.wi_standard_deduction)) * (Params.gov.states.wi.tax.income.credits.itemized_deduction.rate.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/property_tax/wi_property_tax_credit_potential.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_property_tax_credit_potential (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (min ((Params.gov.states.wi.tax.income.credits.property_tax.max.atDate d) : Rat) (((sumBy t.members fun p => p.core_p2.real_estate_taxes) + ((sumBy t.members fun p => p.core_p2.rent) * (Params.gov.states.wi.tax.income.credits.property_tax.rent_fraction.atDate d))) * (Params.gov.states.wi.tax.income.credits.property_tax.rate.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_retirement_income_subtraction_agi_eligible.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def wi_retirement_income_subtraction_agi_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.WI then (decide (t.irs.adjusted_gross_income < (match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.wi.tax.income.subtractions.retirement_income.max_agi.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.wi.tax.income.subtractions.retirement_income.max_agi.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.wi.tax.income.subtractions.retirement_income.max_agi.SURVIVING_SPOUSE.atDate d)))) else false)

/-- `policyengine_us/variables/gov/states/wi/dcf/works/eligibility/wi_works_resources_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def wi_works_resources_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.WI then (decide (t.states_wi.wi_works_countable_resources ≤ (Params.gov.states.wi.dcf.works.asset.limit.atDate d))) else false)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_529_plan_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_529_plan_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (min ((investment_in_529_plan t d) : Rat) ((match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.wi.tax.income.subtractions.plan_529.cap.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.wi.tax.income.subtractions.plan_529.cap.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.wi.tax.income.subtractions.plan_529.cap.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.wi.tax.income.subtractions.plan_529.cap.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.wi.tax.income.subtractions.plan_529.cap.SURVIVING_SPOUSE.atDate d)) * (sumBy t.members fun p => p.core_p1.count_529_contribution_beneficiaries))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/exemptions/wi_base_exemption.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_base_exemption (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((exemptions_count t d) * (Params.gov.states.wi.tax.income.exemption.base.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_capital_gain_loss_subtraction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_capital_gain_loss_subtraction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (max (0 : Rat) ((max (0 : Rat) ((sumBy t.members fun p => p.core_p2.short_term_capital_gains) + (sumBy t.members fun p => (long_term_capital_gains t p d)))) - ((max (0 : Rat) ((sumBy t.members fun p => p.core_p2.short_term_capital_gains) + (sumBy t.members fun p => (long_term_capital_gains t p d)))) - ((min ((max (0 : Rat) ((sumBy t.members fun p => p.core_p2.short_term_capital_gains) + (sumBy t.members fun p => (long_term_capital_gains t p d)))) : Rat) (max (0 : Rat) (sumBy t.members fun p => (long_term_capital_gains t p d)))) * (Params.gov.states.wi.tax.income.subtractions.capital_gain.fraction.atDate d))))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/additions/wi_capital_loss.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_capital_loss (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (if (decide (((sumBy t.members fun p => p.core_p2.short_term_capital_gains) + (sumBy t.members fun p => (long_term_capital_gains t p d))) < 0)) then (min ((match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.wi.tax.income.additions.capital_loss.limit.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.wi.tax.income.additions.capital_loss.limit.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.wi.tax.income.additions.capital_loss.limit.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.wi.tax.income.additions.capital_loss.limit.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.wi.tax.income.additions.capital_loss.limit.SURVIVING_SPOUSE.atDate d)) : Rat) (0 - ((sumBy t.members fun p => p.core_p2.short_term_capital_gains) + (sumBy t.members fun p => (long_term_capital_gains t p d))))) else 0) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/homestead/wi_homestead_credit.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_homestead_credit (t : TaxUnit) (d : Date) : Rat :=
  (if t.states_wi.wi_homestead_eligible then ((max (0 : Rat) ((min ((Params.gov.states.wi.tax.income.credits.homestead.property_tax.max.atDate d) : Rat) (wi_homestead_property_tax t d)) - ((max (0 : Rat) (t.states_wi.wi_homestead_income - (Params.gov.states.wi.tax.income.credits.homestead.phase_out.start.atDate d))) * (Params.gov.states.wi.tax.income.credits.homestead.phase_out.rate.atDate d)))) * (Params.gov.states.wi.tax.income.credits.homestead.rate.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_retirement_income_exclusion_eligible.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def wi_retirement_income_exclusion_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.WI then (anyBy t.members fun p => (decide (((boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.min_age.atDate d)))) * (boolToRat (is_tax_unit_head_or_spouse t p d))) ≠ 0))) else false)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_retirement_income_subtraction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_retirement_income_subtraction (t : TaxUnit) (d : Date) : Rat :=
  (if (wi_retirement_income_subtraction_agi_eligible t d) then (sumBy t.members fun p => (min ((Params.gov.states.wi.tax.income.subtractions.retirement_income.max_amount.atDate d) : Rat) (((taxable_pension_income t p d) * (boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.wi.tax.income.subtractions.retirement_income.min_age.atDate d))))) * (boolToRat (!(is_tax_unit_dependent t p d)))))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/exemptions/wi_exemption.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_exemption (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((wi_base_exemption t d) + t.states_wi.wi_additional_exemption) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/wi_refundable_credits.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_refundable_credits (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (t.states_wi.wi_earned_income_credit + (wi_homestead_credit t d)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_retirement_income_exclusion_amount.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_retirement_income_exclusion_amount (t : TaxUnit) (d : Date) : Rat :=
  (if (wi_retirement_income_exclusion_eligible t d) then (if ((t.core.filing_status == FilingStatus.JOINT) && (decide ((sumBy t.members fun p => ((boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.min_age.atDate d)))) * (boolToRat (is_tax_unit_head_or_spouse t p d)))) ≥ 2))) then (min ((Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.max_amount.joint.atDate d) : Rat) (sumBy t.members fun p => (((taxable_pension_income t p d) + p.core_p2.taxable_ira_distributions) * ((boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.min_age.atDate d)))) * (boolToRat (is_tax_unit_head_or_spouse t p d)))))) else (sumBy t.members fun p => (min ((Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.max_amount.single.atDate d) : Rat) (((taxable_pension_income t p d) + p.core_p2.taxable_ira_distributions) * ((boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.min_age.atDate d)))) * (boolToRat (is_tax_unit_head_or_spouse t p d))))))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/wi_income_tax.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_income_tax (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (if (Params.gov.states.wi.tax.income.subtractions.retirement_income.exclusion.in_effect.atDate d) then (min (((wi_income_tax_before_refundable_credits t d) - (wi_refundable_credits t d)) : Rat) t.states_wi.wi_retirement_income_exclusion_tax) else ((wi_income_tax_before_refundable_credits t d) - (wi_refundable_credits t d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/dcf/works/income/wi_works_countable_income.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def wi_works_countable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (((sumBy t.members fun p => (tanf_gross_earned_income t p d)) + (sumBy t.members fun p => (tanf_gross_unearned_income t p d))) - (sumBy t.members fun p => (p.core_p1.child_support_received / 12))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/additions/wi_capital_gain_loss_addition.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_capital_gain_loss_addition (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (max (0 : Rat) ((limited_capital_loss t d) - (wi_capital_loss t d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/dcf/works/eligibility/wi_works_income_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def wi_works_income_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.WI then (decide ((wi_works_countable_income t d) ≤ ((t.hhs.spm_unit_fpg / 12) * (Params.gov.states.wi.dcf.works.income_limit.rate.atDate d)))) else false)

/-- `policyengine_us/variables/gov/states/wi/tax/income/additions/wi_additions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_additions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (((sumBy t.members fun p => p.core_p2.tax_exempt_interest_income) + (wi_capital_gain_loss_addition t d)) + t.core.form_4972_lumpsum_distributions) else 0)

/-- `policyengine_us/variables/gov/states/wi/dcf/works/eligibility/wi_works_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def wi_works_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.WI then ((((is_demographic_tanf_eligible t d) && (anyBy t.members fun p => (is_citizen_or_legal_immigrant t p d))) && (wi_works_income_eligible t d)) && (wi_works_resources_eligible t d)) else false)

/-- `policyengine_us/variables/gov/states/wi/tax/income/wi_agi.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_agi (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((t.irs.adjusted_gross_income + (wi_additions t d)) - t.states_wi.wi_income_subtractions) else 0)

/-- `policyengine_us/variables/gov/states/wi/dcf/works/wi_works.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def wi_works (t : TaxUnit) (d : Date) : Rat :=
  (if (wi_works_eligible t d) then (match t.states_wi.wi_works_placement with | WIWorksPlacement.CSJ => (Params.gov.states.wi.dcf.works.placement.amount.CSJ.atDate d) | WIWorksPlacement.W2_TRANSITION => (Params.gov.states.wi.dcf.works.placement.amount.W2_TRANSITION.atDate d) | WIWorksPlacement.CMC => (Params.gov.states.wi.dcf.works.placement.amount.CMC.atDate d) | WIWorksPlacement.ARP => (Params.gov.states.wi.dcf.works.placement.amount.ARP.atDate d) | WIWorksPlacement.NONE => (Params.gov.states.wi.dcf.works.placement.amount.NONE.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/wi_taxable_income.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_taxable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (max (0 : Rat) (((wi_agi t d) - t.states_wi.wi_standard_deduction) - (wi_exemption t d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/subtractions/wi_childcare_expense_subtraction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_childcare_expense_subtraction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then ((boolToRat (cdcc_filing_status_eligible t d)) * (min ((min ((t.core.tax_unit_childcare_expenses + (sumBy t.members fun p => (care_expenses t p d))) : Rat) ((min ((count_cdcc_eligible t d) : Rat) (Params.gov.states.wi.tax.income.subtractions.childcare_expense.max_dependents.atDate d)) * (Params.gov.states.wi.tax.income.subtractions.childcare_expense.max_amount.atDate d))) : Rat) (min_head_spouse_earned t d))) else 0)

/-- `policyengine_us/variables/gov/states/wi/tax/income/credits/childcare_expense/wi_childcare_expense_credit_potential.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def wi_childcare_expense_credit_potential (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.WI then (if (decide ((Params.gov.states.wi.tax.income.credits.childcare_expense.max_expense.atDate d) > 0)) then ((((boolToRat (cdcc_filing_status_eligible t d)) * (min ((min ((t.core.tax_unit_childcare_expenses + (sumBy t.members fun p => (care_expenses t p d))) : Rat) ((Params.gov.states.wi.tax.income.credits.childcare_expense.max_expense.atDate d) * (capped_count_cdcc_eligible t d))) : Rat) (min_head_spouse_earned t d))) * t.irs.cdcc_rate) * (Params.gov.states.wi.tax.income.credits.childcare_expense.fraction.atDate d)) else ((cdcc_potential t d) * (Params.gov.states.wi.tax.income.credits.childcare_expense.fraction.atDate d))) else 0)

end Lawlib.Gen.Vars
