/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (design §5).
-/
import Lawlib.Gen.Vars.Trunk.P004

namespace Lawlib.Gen.Vars
open Lawlib Lawlib.Gen

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/states/ny/tax/income/adjusted_gross_income/ny_agi.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_agi (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((t.irs.adjusted_gross_income + t.states_ny.ny_additions) - t.states_ny.ny_agi_subtractions) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/ny_allowable_college_tuition_expenses.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_allowable_college_tuition_expenses (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (sumBy t.members fun p => (min (p.core_p2.qualified_tuition_expenses : Rat) (Params.gov.states.ny.tax.income.college_tuition.cap.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/payroll/disability_benefits/ny_disability_benefits_taxable_wages.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_disability_benefits_taxable_wages (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then (max (0 : Rat) p.core_p1.employment_income) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ny_geothermal_energy_system_credit_potential.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_geothermal_energy_system_credit_potential (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (min ((t.states_ny.ny_qualified_geothermal_energy_system_expenditures * (Params.gov.states.ny.tax.income.credits.geothermal_energy_system.rate.atDate d)) : Rat) (Params.gov.states.ny.tax.income.credits.geothermal_energy_system.cap.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/ny_income_tax_before_credits.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_income_tax_before_credits (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (t.states_ny.ny_main_income_tax + t.states_ny.ny_supplemental_tax) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/payroll/paid_family_leave/ny_paid_family_leave_taxable_wages.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_paid_family_leave_taxable_wages (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then (max (0 : Rat) p.core_p1.employment_income) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/pre_tcja/ny_salt_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_salt_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (sumBy t.members fun p => p.core_p2.real_estate_taxes) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/solar_energy_systems/ny_solar_energy_systems_equipment_credit_potential.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_solar_energy_systems_equipment_credit_potential (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (min ((t.states_ny.ny_qualified_solar_energy_systems_equipment_expenditures * (Params.gov.states.ny.tax.income.credits.solar_energy_systems_equipment.rate.atDate d)) : Rat) (Params.gov.states.ny.tax.income.credits.solar_energy_systems_equipment.cap.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/ny_tanf_need_standard.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def ny_tanf_need_standard (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (((t.states_ny.ny_tanf_basic_monthly_allowance + t.states_ny.ny_tanf_home_energy_allowance) + t.states_ny.ny_tanf_supplemental_home_energy_allowance) + t.states_ny.ny_tanf_shelter_allowance) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/pre_tcja/ny_casualty_loss_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_casualty_loss_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max (0 : Rat) ((sumBy t.members fun p => p.core_p1.casualty_loss) - ((positive_agi t d) * (Params.gov.irs.deductions.itemized.casualty.floor.atDate d)))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/cdcc/ny_cdcc_rate.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_cdcc_rate (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((if (decide ((ny_agi t d) < (Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.max_agi.atDate d))) then ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.base_percentage.atDate d) + (((max (0 : Rat) (min ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.fraction.numerator.min.atDate d) : Rat) ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.fraction.numerator.top.atDate d) - (ny_agi t d)))) / (Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.fraction.denominator.atDate d)) * (Params.gov.states.ny.tax.income.credits.cdcc.percentage.alternate.multiplier.atDate d))) else ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.main.base_percentage.atDate d) + (((max (0 : Rat) (min ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.main.fraction.numerator.min.atDate d) : Rat) ((Params.gov.states.ny.tax.income.credits.cdcc.percentage.main.fraction.numerator.top.atDate d) - (ny_agi t d)))) / (Params.gov.states.ny.tax.income.credits.cdcc.percentage.main.fraction.denominator.atDate d)) * (Params.gov.states.ny.tax.income.credits.cdcc.percentage.main.multiplier.atDate d)))) * (Params.gov.states.ny.tax.income.credits.cdcc.percentage.multiplier.atDate d (ny_agi t d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/ny_college_tuition_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_college_tuition_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((ny_allowable_college_tuition_expenses t d) * (Params.gov.states.ny.tax.income.deductions.itemized.college_tuition.applicable_percentage.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/payroll/disability_benefits/ny_employee_disability_benefits_contribution.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_employee_disability_benefits_contribution (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then (min (((Params.gov.states.ny.tax.payroll.disability_benefits.employee_rate.atDate d) * (ny_disability_benefits_taxable_wages t p d)) : Rat) (Params.gov.states.ny.tax.payroll.disability_benefits.annual_max_contribution.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/payroll/paid_family_leave/ny_employee_paid_family_leave_contribution.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_employee_paid_family_leave_contribution (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then (min (((Params.gov.states.ny.tax.payroll.paid_family_leave.employee_rate.atDate d) * (ny_paid_family_leave_taxable_wages t p d)) : Rat) (Params.gov.states.ny.tax.payroll.paid_family_leave.annual_max_contribution.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_escc_qualifying_child.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def ny_escc_qualifying_child (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (if (is_tax_unit_dependent t p d) then ((p.core_p1.has_tin && (decide (p.core_p1.age < (Params.gov.states.ny.tax.income.credits.ctc.post_2024.amount.lastThreshold d)))) && (decide (p.core_p1.age ≥ (Params.gov.states.ny.tax.income.credits.ctc.minimum_age.atDate d)))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/ny_income_tax_before_refundable_credits.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_income_tax_before_refundable_credits (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max (((ny_income_tax_before_credits t d) - t.states_ny.ny_non_refundable_credits) : Rat) 0) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/pre_tcja/ny_misc_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_misc_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max (0 : Rat) ((total_misc_deductions t d) - ((Params.gov.irs.deductions.itemized.misc.floor.atDate d) * (positive_agi t d)))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/adjusted_gross_income/ny_pension_exclusion.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_pension_exclusion (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  ((boolToRat (decide (p.core_p1.age ≥ (Params.gov.states.ny.tax.income.agi.subtractions.pension_exclusion.min_age.atDate d)))) * (min ((taxable_pension_income t p d) : Rat) (Params.gov.states.ny.tax.income.agi.subtractions.pension_exclusion.cap.atDate d)))

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ny_real_property_tax_credit.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_real_property_tax_credit (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (min (((boolToRat (((decide ((sumBy t.members fun p => p.local_tax.assessed_property_value) ≤ (Params.gov.states.ny.tax.income.credits.real_property_tax.max_property_value.atDate d))) && (decide (((sumBy t.members fun p => p.core_p2.rent) * (Params.gov.states.ny.tax.income.credits.real_property_tax.rent_tax_equivalent.atDate d)) ≤ (Params.gov.states.ny.tax.income.credits.real_property_tax.max_rent.atDate d)))) && (decide (t.irs.adjusted_gross_income < (Params.gov.states.ny.tax.income.credits.real_property_tax.max_agi.atDate d))))) * ((Params.gov.states.ny.tax.income.credits.real_property_tax.rate.atDate d) * (max (0 : Rat) (((sumBy t.members fun p => p.core_p2.real_estate_taxes) + ((sumBy t.members fun p => p.core_p2.rent) * (Params.gov.states.ny.tax.income.credits.real_property_tax.rent_tax_equivalent.atDate d))) - (t.irs.adjusted_gross_income * (Params.gov.states.ny.tax.income.credits.real_property_tax.excess_real_property_tax.atDate d t.irs.adjusted_gross_income)))))) : Rat) (if (anyBy t.members fun p => ((!(is_tax_unit_dependent t p d)) && (decide (p.core_p1.age ≥ (Params.gov.states.ny.tax.income.credits.real_property_tax.elderly_age.atDate d))))) then (Params.gov.states.ny.tax.income.credits.real_property_tax.maximum.elderly.atDate d t.irs.adjusted_gross_income) else (Params.gov.states.ny.tax.income.credits.real_property_tax.maximum.non_elderly.atDate d t.irs.adjusted_gross_income))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/ny_standard_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_standard_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (if (head_is_dependent_elsewhere t d) then (Params.gov.states.ny.tax.income.deductions.standard.dependent_elsewhere.atDate d) else (match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.ny.tax.income.deductions.standard.amount.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.ny.tax.income.deductions.standard.amount.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.ny.tax.income.deductions.standard.amount.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.ny.tax.income.deductions.standard.amount.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.ny.tax.income.deductions.standard.amount.SURVIVING_SPOUSE.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/income/ny_tanf_countable_earned_income.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_tanf_countable_earned_income (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then (if (Params.gov.states.ny.otda.tanf.reform_2022.in_effect.atDate d) then (max ((((tanf_gross_earned_income t p d) * (1 - (Params.gov.states.ny.otda.tanf.income.earned_income_deduction.percent.atDate d))) - (Params.gov.states.ny.otda.tanf.income.earned_income_deduction.flat.atDate d)) : Rat) 0) else ((max (((tanf_gross_earned_income t p d) - (Params.gov.states.ny.otda.tanf.income.earned_income_deduction.flat.atDate d)) : Rat) 0) * (1 - (Params.gov.states.ny.otda.tanf.income.earned_income_deduction.percent.atDate d)))) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/eligibility/ny_tanf_resources_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def ny_tanf_resources_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (decide ((spm_unit_cash_assets t d) ≤ (if (if (Params.gov.states.ny.otda.tanf.reform_2022.in_effect.atDate d) then ((anyBy t.members fun p => (decide (p.core_p1.age ≥ (Params.gov.states.ny.otda.tanf.resource_limit.higher.age_threshold.atDate d)))) || (anyBy t.members fun p => p.core_p1.is_disabled)) else (anyBy t.members fun p => (decide (p.core_p1.age ≥ (Params.gov.states.ny.otda.tanf.resource_limit.higher.age_threshold.atDate d))))) then (Params.gov.states.ny.otda.tanf.resource_limit.higher.amount.atDate d) else (Params.gov.states.ny.otda.tanf.resource_limit.lower.amount.atDate d)))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_ctc_post_2024_eligible.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def ny_ctc_post_2024_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (if (!(Params.gov.states.ny.tax.income.credits.ctc.post_2024.in_effect.atDate d)) then false else (decide ((sumBy t.members fun p => (boolToRat ((ny_escc_qualifying_child t p d) && (decide ((Params.gov.states.ny.tax.income.credits.ctc.post_2024.amount.atDate d p.core_p1.age) > 0))))) > 0))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/payroll/ny_employee_state_payroll_tax.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def ny_employee_state_payroll_tax (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if t.core.NY then ((ny_employee_paid_family_leave_contribution t p d) + (ny_employee_disability_benefits_contribution t p d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/ny_income_tax.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_income_tax (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((ny_income_tax_before_refundable_credits t d) - t.states_ny.ny_refundable_credits) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_ctc_post_2024_base.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_ctc_post_2024_base (t : TaxUnit) (d : Date) : Rat :=
  (if (ny_ctc_post_2024_eligible t d) then (sumBy t.members fun p => ((boolToRat (ny_escc_qualifying_child t p d)) * (Params.gov.states.ny.tax.income.credits.ctc.post_2024.amount.atDate d p.core_p1.age))) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/income/ny_tanf_countable_income.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def ny_tanf_countable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((sumBy t.members fun p => (ny_tanf_countable_earned_income t p d)) + (sumBy t.members fun p => (tanf_gross_unearned_income t p d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/eligibility/ny_tanf_gross_income_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def ny_tanf_gross_income_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (decide (((sumBy t.members fun p => (tanf_gross_earned_income t p d)) + (sumBy t.members fun p => (tanf_gross_unearned_income t p d))) ≤ ((ny_tanf_need_standard t d) * (Params.gov.states.ny.otda.tanf.gross_income_test.rate.atDate d)))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_ctc_post_2024.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_ctc_post_2024 (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max (((ny_ctc_post_2024_base t d) - t.states_ny.ny_ctc_post_2024_phase_out) : Rat) 0) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/eligibility/ny_tanf_income_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def ny_tanf_income_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (if (Params.gov.states.ny.otda.tanf.reform_2022.in_effect.atDate d) then (decide ((ny_tanf_countable_income t d) < (ny_tanf_need_standard t d))) else ((ny_tanf_gross_income_eligible t d) && (decide ((ny_tanf_countable_income t d) < (ny_tanf_need_standard t d))))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_ctc.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_ctc (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((ny_ctc_post_2024 t d) + t.states_ny.ny_ctc_pre_2024) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/ny_exemptions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_exemptions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((Params.gov.states.ny.tax.income.exemptions.dependent.atDate d) * (tax_unit_child_dependents t d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/eligibility/ny_tanf_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def ny_tanf_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then ((((is_demographic_tanf_eligible t d) && (decide ((sumBy t.members fun p => boolToRat (is_citizen_or_legal_immigrant t p d)) > 0))) && (ny_tanf_income_eligible t d)) && (ny_tanf_resources_eligible t d)) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ctc/ny_additional_ctc.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_additional_ctc (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((boolToRat (decide (((ny_ctc t d) * (Params.gov.states.ny.tax.income.credits.ctc.additional.amount.atDate d t.irs.adjusted_gross_income)) ≥ (Params.gov.states.ny.tax.income.credits.ctc.additional.min_credit_value.atDate d)))) * ((ny_ctc t d) * (Params.gov.states.ny.tax.income.credits.ctc.additional.amount.atDate d t.irs.adjusted_gross_income))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/ny_itemized_deductions_max.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions_max (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (((((((charitable_deduction t d) + (interest_deduction t d)) + (medical_expense_deduction t d)) + (ny_salt_deduction t d)) + (ny_misc_deduction t d)) + (ny_casualty_loss_deduction t d)) + (ny_college_tuition_deduction t d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/otda/tanf/ny_tanf.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def ny_tanf (t : TaxUnit) (d : Date) : Rat :=
  (if (ny_tanf_eligible t d) then (min ((max (((ny_tanf_need_standard t d) - (ny_tanf_countable_income t d)) : Rat) 0) : Rat) (ny_tanf_need_standard t d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/reduction/based_on_charitable_deduction/incremental/ny_itemized_deductions_higher_incremental_reduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions_higher_incremental_reduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.states_ny.ny_itemized_deductions_reduction_applies then (((ny_itemized_deductions_max t d) * (Params.gov.states.ny.tax.income.deductions.itemized.reduction.incremental.higher.rate.atDate d)) * ((min ((Params.gov.states.ny.tax.income.deductions.itemized.reduction.incremental.higher.numerator.atDate d) : Rat) (max (((ny_agi t d) - (Params.gov.states.ny.tax.income.deductions.itemized.reduction.incremental.higher.income_threshold.atDate d)) : Rat) 0)) / (Params.gov.states.ny.tax.income.deductions.itemized.reduction.incremental.higher.denominator.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/reduction/based_on_charitable_deduction/ny_itemized_deductions_reduction_based_on_charitable_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions_reduction_based_on_charitable_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.states_ny.ny_itemized_deductions_reduction_based_on_charitable_deduction_applies then (max (((ny_itemized_deductions_max t d) - ((charitable_deduction t d) * (Params.gov.states.ny.tax.income.deductions.itemized.reduction.charitable_deduction_rate.atDate d (ny_agi t d)))) : Rat) 0) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/reduction/based_on_charitable_deduction/incremental/ny_itemized_deductions_incremental_reduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions_incremental_reduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.states_ny.ny_itemized_deductions_reduction_applies then ((ny_itemized_deductions_higher_incremental_reduction t d) + t.states_ny.ny_itemized_deductions_lower_incremental_reduction) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/reduction/ny_itemized_deductions_reduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions_reduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.states_ny.ny_itemized_deductions_reduction_applies then (if t.states_ny.ny_itemized_deductions_reduction_based_on_charitable_deduction_applies then (ny_itemized_deductions_reduction_based_on_charitable_deduction t d) else (ny_itemized_deductions_incremental_reduction t d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/ny_itemized_deductions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_itemized_deductions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((ny_itemized_deductions_max t d) - (t.states_ny.ny_itemized_deductions_phase_out + (ny_itemized_deductions_reduction t d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/ny_supplemental_eitc.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_supplemental_eitc (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((eitc t d) * (Params.gov.states.ny.tax.income.credits.eitc.supplemental_match.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/ny_deductions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_deductions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max ((ny_itemized_deductions t d) : Rat) (ny_standard_deduction t d)) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/deductions/itemized/ny_itemizes.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def ny_itemizes (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (t.irs.tax_unit_itemizes && (decide ((ny_itemized_deductions t d) ≥ (ny_standard_deduction t d)))) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/cdcc/ny_cdcc_max.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_cdcc_max (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (min ((cdcc_relevant_expenses t d) : Rat) (min ((Params.gov.states.ny.tax.income.credits.cdcc.max.atDate d (count_cdcc_eligible t d)) : Rat) (min_head_spouse_earned t d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/college_tuition/ny_college_tuition_credit_eligible.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def ny_college_tuition_credit_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.NY then (!(ny_itemizes t d)) else false)

/-- `policyengine_us/variables/gov/states/ny/tax/income/taxable_income/ny_taxable_income.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_taxable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then (max (0 : Rat) (((ny_agi t d) - (ny_deductions t d)) - (ny_exemptions t d))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/cdcc/ny_cdcc.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_cdcc (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.NY then ((boolToRat (cdcc_filing_status_eligible t d)) * (min ((ny_cdcc_max t d) : Rat) ((cdcc_relevant_expenses t d) * ((ny_cdcc_rate t d) * t.irs.cdcc_rate)))) else 0)

/-- `policyengine_us/variables/gov/states/ny/tax/income/credits/college_tuition/ny_college_tuition_credit.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def ny_college_tuition_credit (t : TaxUnit) (d : Date) : Rat :=
  (if (ny_college_tuition_credit_eligible t d) then ((Params.gov.states.ny.tax.income.credits.college_tuition.rate.atDate d (ny_allowable_college_tuition_expenses t d)) * (Params.gov.states.ny.tax.income.credits.college_tuition.applicable_percentage.atDate d)) else 0)

end Lawlib.Gen.Vars
