/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (design §5).
-/
import Lawlib.Gen.Vars.Trunk.P004

namespace Lawlib.Gen.Vars
open Lawlib Lawlib.Gen

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/itemized/al_casualty_loss_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_casualty_loss_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (max (0 : Rat) ((sumBy t.members fun p => p.core_p1.casualty_loss) - (t.states_al.al_agi * (Params.gov.irs.deductions.itemized.casualty.floor.atDate d)))) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/copay/al_ccsp_copay_protective_services.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def al_ccsp_copay_protective_services (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then ((decide ((sumBy t.members fun p => boolToRat p.core_p1.is_in_foster_care) > 0)) || (decide ((sumBy t.members fun p => boolToRat p.core_p2.receives_or_needs_protective_services) > 0))) else false)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/al_child_care_subsidies.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def al_child_care_subsidies (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (t.states_al.al_ccsp * 12) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/al_income_tax_before_refundable_credits.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_income_tax_before_refundable_credits (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (max ((t.states_al.al_income_tax_before_non_refundable_credits - t.states_al.al_non_refundable_credits) : Rat) 0) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/exemptions/al_personal_exemption.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_personal_exemption (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.al.tax.income.exemptions.personal.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.al.tax.income.exemptions.personal.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.al.tax.income.exemptions.personal.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.al.tax.income.exemptions.personal.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.al.tax.income.exemptions.personal.SURVIVING_SPOUSE.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/plan_529/al_529_plan_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_529_plan_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (min ((investment_in_529_plan t d) : Rat) (match t.core.filing_status with | FilingStatus.SINGLE => (Params.gov.states.al.tax.income.deductions.plan_529.cap.SINGLE.atDate d) | FilingStatus.JOINT => (Params.gov.states.al.tax.income.deductions.plan_529.cap.JOINT.atDate d) | FilingStatus.SEPARATE => (Params.gov.states.al.tax.income.deductions.plan_529.cap.SEPARATE.atDate d) | FilingStatus.HEAD_OF_HOUSEHOLD => (Params.gov.states.al.tax.income.deductions.plan_529.cap.HEAD_OF_HOUSEHOLD.atDate d) | FilingStatus.SURVIVING_SPOUSE => (Params.gov.states.al.tax.income.deductions.plan_529.cap.SURVIVING_SPOUSE.atDate d))) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/copay/al_ccsp_copay_waived.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def al_ccsp_copay_waived (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then (((anyBy t.members fun p => ((p.core_p1.is_disabled && (decide (p.core_p1.age < (Params.gov.states.al.dhr.ccsp.age.disabled_child_limit.atDate d)))) && (is_tax_unit_dependent t p d))) || (decide ((sumBy t.members fun p => boolToRat p.core_p1.is_enrolled_in_head_start) > 0))) || (al_ccsp_copay_protective_services t d)) else false)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/eligibility/al_ccsp_eligible_child.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def al_ccsp_eligible_child (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (if t.core.AL then (((if p.core_p1.is_disabled then (decide (p.core_p1.age < (Params.gov.states.al.dhr.ccsp.age.disabled_child_limit.atDate d))) else (decide (p.core_p1.age < (Params.gov.states.al.dhr.ccsp.age.child_limit.atDate d)))) && (is_ccdf_immigration_eligible_child t p d)) && (is_tax_unit_dependent t p d)) else false)

/-- `policyengine_us/variables/gov/states/al/tax/income/al_income_tax.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_income_tax (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then ((al_income_tax_before_refundable_credits t d) - t.states_al.al_refundable_credits) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_eligible_person.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def al_retirement_exemption_eligible_person (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (if t.core.AL then ((decide (p.core_p1.age ≥ (Params.gov.states.al.tax.income.exemptions.retirement.age_threshold.atDate d))) && (is_tax_unit_head_or_spouse t p d)) else false)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/eligibility/al_ccsp_activity_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def al_ccsp_activity_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then (((decide ((sumBy t.members fun p => (boolToRat (is_tax_unit_head_or_spouse t p d))) ≥ 1)) && (decide ((sumBy t.members fun p => (boolToRat ((is_tax_unit_head_or_spouse t p d) && (!((decide ((weekly_hours_worked t p d) ≥ (Params.gov.states.al.dhr.ccsp.activity.hours_minimum.atDate d))) || (is_full_time_student t p d)))))) = 0))) || t.hhs.meets_ccdf_activity_test) else false)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/itemized/al_misc_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_misc_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (max (0 : Rat) ((misc_deduction t d) - ((Params.gov.states.al.tax.income.deductions.itemized.work_related_expense_rate.atDate d) * t.states_al.al_agi))) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption_person.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def al_retirement_exemption_person (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if (al_retirement_exemption_eligible_person t p d) then (min (((taxable_retirement_distributions t p d) + (taxable_pension_income t p d)) : Rat) (Params.gov.states.al.tax.income.exemptions.retirement.cap.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/property/senior_homestead_exemption/al_senior_homestead_exemption_eligible.py`
    policyengine-us 1.783.0, entity tax_unit, value_type bool. -/
def al_senior_homestead_exemption_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then ((decide ((greater_age_head_spouse t d) ≥ (Params.gov.states.al.tax.property.senior_homestead_exemption.age_threshold.atDate d))) && (decide ((sumBy t.members fun p => p.core_p2.real_estate_taxes) > 0))) else false)

/-- `policyengine_us/variables/gov/states/al/tax/income/exemptions/retirement/al_retirement_exemption.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_retirement_exemption (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (sumBy t.members fun p => (al_retirement_exemption_person t p d)) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/property/senior_homestead_exemption/al_senior_homestead_exemption.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_senior_homestead_exemption (t : TaxUnit) (d : Date) : Rat :=
  (if (al_senior_homestead_exemption_eligible t d) then (min (((sumBy t.members fun p => p.local_tax.assessed_property_value) * (Params.gov.states.al.tax.property.senior_homestead_exemption.state_property_tax_rate.atDate d)) : Rat) (sumBy t.members fun p => p.core_p2.real_estate_taxes)) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/itemized/al_investment_interest.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_interest_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then ((sumBy t.members fun p => (mortgage_interest t p d)) + (sumBy t.members fun p => p.core_p1.investment_interest_expense)) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/itemized/al_medical_expense_deduction.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_medical_expense_deduction (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (max (0 : Rat) ((itemized_medical_expenses t d) - ((Params.gov.states.al.tax.income.deductions.itemized.medical_expense.income_floor.atDate d) * t.states_al.al_agi))) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ssp/al_ssp_eligible.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def al_ssp_eligible (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (if t.core.AL then ((((((is_ssi_eligible t p d) && (decide ((uncapped_ssi t p d) > 0))) && (!(p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.NONE))) && (!(p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.CEREBRAL_PALSY))) && ((!(((p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.IHC_LEVEL_A) || (p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.IHC_LEVEL_B)) || (p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.FOSTER_CARE))) || (p.states_al.al_receives_elderly_disabled_medicaid_waiver && p.states_al.al_meets_snf_criteria))) || (p.states_al.al_ssp_grandfathered && (!(p.states_al.al_ssp_payment_category == ALSSPPaymentCategory.NONE)))) else false)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/itemized/al_itemized_deductions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_itemized_deductions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then ((((((((sumBy t.members fun p => p.core_p2.real_estate_taxes) + t.irs.employee_payroll_tax) + (sumBy t.members fun p => (self_employment_tax t p d))) + (charitable_deduction t d)) + (al_medical_expense_deduction t d)) + (al_casualty_loss_deduction t d)) + (al_misc_deduction t d)) + (al_interest_deduction t d)) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ssp/al_ssp.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def al_ssp (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if (al_ssp_eligible t p d) then (match p.states_al.al_ssp_payment_category with | ALSSPPaymentCategory.FCMP_NURSING_CARE => (Params.gov.states.al.dhr.ssp.amount.FCMP_NURSING_CARE.atDate d) | ALSSPPaymentCategory.NURSING_CARE => (Params.gov.states.al.dhr.ssp.amount.NURSING_CARE.atDate d) | ALSSPPaymentCategory.IHC_LEVEL_A => (Params.gov.states.al.dhr.ssp.amount.IHC_LEVEL_A.atDate d) | ALSSPPaymentCategory.IHC_LEVEL_B => (Params.gov.states.al.dhr.ssp.amount.IHC_LEVEL_B.atDate d) | ALSSPPaymentCategory.FOSTER_CARE => (Params.gov.states.al.dhr.ssp.amount.FOSTER_CARE.atDate d) | ALSSPPaymentCategory.CEREBRAL_PALSY => (Params.gov.states.al.dhr.ssp.amount.CEREBRAL_PALSY.atDate d) | ALSSPPaymentCategory.NONE => (Params.gov.states.al.dhr.ssp.amount.NONE.atDate d)) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/al_ccsp_countable_income.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def al_ccsp_countable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (((((((((((((sumBy t.members fun p => (p.core_p1.employment_income / 12)) + (sumBy t.members fun p => (p.core_p2.self_employment_income / 12))) + (sumBy t.members fun p => (p.core_p1.farm_operations_income / 12))) + (sumBy t.members fun p => ((social_security t p d) / 12))) + (sumBy t.members fun p => ((pension_income t p d) / 12))) + (sumBy t.members fun p => (p.states.unemployment_compensation / 12))) + (sumBy t.members fun p => (p.states.workers_compensation / 12))) + (sumBy t.members fun p => (ssi t p d))) + (sumBy t.members fun p => (al_ssp t p d))) + (sumBy t.members fun p => ((interest_income t p d) / 12))) + (sumBy t.members fun p => ((dividend_income t p d) / 12))) + (sumBy t.members fun p => (p.core_p1.alimony_income / 12))) + (sumBy t.members fun p => (p.core_p2.veterans_benefits / 12))) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/deductions/al_deductions.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_deductions (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then ((((max ((al_itemized_deductions t d) : Rat) t.states_al.al_standard_deduction) + t.states_al.al_federal_income_tax_deduction) + ((al_personal_exemption t d) + t.states_al.al_dependent_exemption)) + (al_529_plan_deduction t d)) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/eligibility/al_ccsp_income_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def al_ccsp_income_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then ((decide ((al_ccsp_countable_income t d) ≤ ((t.hhs.spm_unit_fpg / 12) * (if t.states_al.al_ccsp_enrolled then (Params.gov.states.al.dhr.ccsp.income.limit.fpl_continuing.atDate d) else (Params.gov.states.al.dhr.ccsp.income.limit.fpl_initial.atDate d))))) && (decide ((al_ccsp_countable_income t d) ≤ ((t.hhs.hhs_smi / 12) * (Params.gov.states.al.dhr.ccsp.income.limit.smi_cap.atDate d))))) else false)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/copay/al_ccsp_weekly_copay_per_child.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def al_ccsp_weekly_copay_per_child (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (if (al_ccsp_copay_waived t d) then 0 else (Params.gov.states.al.dhr.ccsp.copay.fee_by_fpl.atDate d (if (decide ((t.hhs.spm_unit_fpg / 12) > 0)) then ((max ((al_ccsp_countable_income t d) : Rat) 0) / (t.hhs.spm_unit_fpg / 12)) else 0))) else 0)

/-- `policyengine_us/variables/gov/states/al/tax/income/al_taxable_income.py`
    policyengine-us 1.783.0, entity tax_unit, value_type float. -/
def al_taxable_income (t : TaxUnit) (d : Date) : Rat :=
  (if t.core.AL then (max ((t.states_al.al_agi - (al_deductions t d)) : Rat) 0) else 0)

/-- `policyengine_us/variables/gov/states/al/dhr/ccsp/eligibility/al_ccsp_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def al_ccsp_eligible (t : TaxUnit) (d : Date) : Bool :=
  (if t.core.AL then (((((decide ((sumBy t.members fun p => boolToRat (al_ccsp_eligible_child t p d)) > 0)) && (al_ccsp_income_eligible t d)) && (is_ccdf_asset_eligible t d)) && (al_ccsp_activity_eligible t d)) || (((decide ((sumBy t.members fun p => boolToRat (al_ccsp_eligible_child t p d)) > 0)) && (is_ccdf_asset_eligible t d)) && t.states_al.al_ccsp_protective_services)) else false)

end Lawlib.Gen.Vars
