/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (DESIGN.md §5).

Health and Human Services programs: Medicaid, CHIP, TANF, Medicare cost sharing.

Continues the module of the same name. The law
here quotes rules from other agencies, which Lean
must see first; the split is a compilation order,
not a distinction in the law.
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.Entity
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale
import Lawlib.Household
import Lawlib.Parameters
import Lawlib.USA.DOE
import Lawlib.USA.SSA
import Lawlib.USA.HUD
import Lawlib.USA.FCC
import Lawlib.USA.IRS
import Lawlib.USA.ED
import Lawlib.USA.ACA
import Lawlib.USA.General
import Lawlib.USA.USDA
import Lawlib.USA.HHS
import Lawlib.USA.SSA.Part2
import Lawlib.USA.HUD.Part2
import Lawlib.USA.IRS.Part2
import Lawlib.USA.ED.Part2
import Lawlib.USA.ACA.Part2
import Lawlib.USA.General.Part2
import Lawlib.USA.USDA.Part2
import Lawlib.USA.HHS.Part2
import Lawlib.USA.HUD.Part3
import Lawlib.USA.FCC.Part3
import Lawlib.USA.ED.Part3
import Lawlib.USA.USDA.Part3
import Lawlib.USA.HHS.Part3
import Lawlib.USA.ACA.Part4

namespace Lawlib.USA
open Lawlib
open Lawlib.Parameters

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/hhs/tanf/non_cash/meets_tanf_non_cash_gross_income_test.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def meetsTanfNonCashGrossIncomeTest (t : TaxUnit) (d : Date) : Bool :=
  (ExtRat.leCap (snapGrossTestIncomeFpgRatio t d) (if (t.core.stateCodeStr == "NY") then (if
      ((decide ((snapDependentCareDeduction t d) > 0)) || (isTanfNonCashHheod t d)) then
      (ExtRat.fin (gov.hhs.tanf.non_cash.income_limit.ny.dependent_care.atDate d)) else (if
      (decide ((snapEarnedIncome t d) > 0)) then
      (ExtRat.fin (gov.hhs.tanf.non_cash.income_limit.ny.earned_income.atDate d)) else
      (ExtRat.fin (gov.hhs.tanf.non_cash.income_limit.gross.NY.atDate d)))) else (if
      (isTanfNonCashHheod t d) then (if t.core.stateCodeStr == "AK" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.AK.atDate d)
  else if t.core.stateCodeStr == "AL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.AL.atDate d))
  else if t.core.stateCodeStr == "AR" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.AR.atDate d)
  else if t.core.stateCodeStr == "AZ" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.AZ.atDate d))
  else if t.core.stateCodeStr == "CA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.CA.atDate d))
  else if t.core.stateCodeStr == "CO" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.CO.atDate d))
  else if t.core.stateCodeStr == "CT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.CT.atDate d))
  else if t.core.stateCodeStr == "DC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.DC.atDate d))
  else if t.core.stateCodeStr == "DE" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.DE.atDate d))
  else if t.core.stateCodeStr == "FL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.FL.atDate d))
  else if t.core.stateCodeStr == "GA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.GA.atDate d))
  else if t.core.stateCodeStr == "GU" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.GU.atDate d))
  else if t.core.stateCodeStr == "HI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.HI.atDate d))
  else if t.core.stateCodeStr == "IA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.IA.atDate d))
  else if t.core.stateCodeStr == "ID" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.ID.atDate d)
  else if t.core.stateCodeStr == "IL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.IL.atDate d))
  else if t.core.stateCodeStr == "IN" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.IN.atDate d)
  else if t.core.stateCodeStr == "KS" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.KS.atDate d)
  else if t.core.stateCodeStr == "KY" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.KY.atDate d))
  else if t.core.stateCodeStr == "LA" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.LA.atDate d)
  else if t.core.stateCodeStr == "MA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MA.atDate d))
  else if t.core.stateCodeStr == "MD" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MD.atDate d))
  else if t.core.stateCodeStr == "ME" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.ME.atDate d))
  else if t.core.stateCodeStr == "MI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MI.atDate d))
  else if t.core.stateCodeStr == "MN" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MN.atDate d)
  else if t.core.stateCodeStr == "MO" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MO.atDate d)
  else if t.core.stateCodeStr == "MS" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MS.atDate d)
  else if t.core.stateCodeStr == "MT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.MT.atDate d))
  else if t.core.stateCodeStr == "NC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NC.atDate d))
  else if t.core.stateCodeStr == "ND" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.ND.atDate d))
  else if t.core.stateCodeStr == "NE" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NE.atDate d)
  else if t.core.stateCodeStr == "NH" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NH.atDate d))
  else if t.core.stateCodeStr == "NJ" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NJ.atDate d))
  else if t.core.stateCodeStr == "NM" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NM.atDate d))
  else if t.core.stateCodeStr == "NV" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NV.atDate d))
  else if t.core.stateCodeStr == "NY" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.NY.atDate d))
  else if t.core.stateCodeStr == "OH" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.OH.atDate d))
  else if t.core.stateCodeStr == "OK" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.OK.atDate d)
  else if t.core.stateCodeStr == "OR" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.OR.atDate d))
  else if t.core.stateCodeStr == "PA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.PA.atDate d))
  else if t.core.stateCodeStr == "RI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.RI.atDate d))
  else if t.core.stateCodeStr == "SC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.SC.atDate d))
  else if t.core.stateCodeStr == "SD" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.SD.atDate d)
  else if t.core.stateCodeStr == "TN" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.TN.atDate d)
  else if t.core.stateCodeStr == "TX" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.TX.atDate d))
  else if t.core.stateCodeStr == "UT" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.UT.atDate d)
  else if t.core.stateCodeStr == "VA" then
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.VA.atDate d)
  else if t.core.stateCodeStr == "VI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.VI.atDate d))
  else if t.core.stateCodeStr == "VT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.VT.atDate d))
  else if t.core.stateCodeStr == "WA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.WA.atDate d))
  else if t.core.stateCodeStr == "WI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.WI.atDate d))
  else if t.core.stateCodeStr == "WV" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross_hheod.WV.atDate d))
  else (gov.hhs.tanf.non_cash.income_limit.gross_hheod.WY.atDate d)) else (if
      t.core.stateCodeStr == "AK" then (gov.hhs.tanf.non_cash.income_limit.gross.AK.atDate
      d)
  else if t.core.stateCodeStr == "AL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.AL.atDate d))
  else if t.core.stateCodeStr == "AR" then
      (gov.hhs.tanf.non_cash.income_limit.gross.AR.atDate d)
  else if t.core.stateCodeStr == "AZ" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.AZ.atDate d))
  else if t.core.stateCodeStr == "CA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.CA.atDate d))
  else if t.core.stateCodeStr == "CO" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.CO.atDate d))
  else if t.core.stateCodeStr == "CT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.CT.atDate d))
  else if t.core.stateCodeStr == "DC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.DC.atDate d))
  else if t.core.stateCodeStr == "DE" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.DE.atDate d))
  else if t.core.stateCodeStr == "FL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.FL.atDate d))
  else if t.core.stateCodeStr == "GA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.GA.atDate d))
  else if t.core.stateCodeStr == "GU" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.GU.atDate d))
  else if t.core.stateCodeStr == "HI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.HI.atDate d))
  else if t.core.stateCodeStr == "IA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.IA.atDate d))
  else if t.core.stateCodeStr == "ID" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.ID.atDate d))
  else if t.core.stateCodeStr == "IL" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.IL.atDate d))
  else if t.core.stateCodeStr == "IN" then
      (gov.hhs.tanf.non_cash.income_limit.gross.IN.atDate d)
  else if t.core.stateCodeStr == "KS" then
      (gov.hhs.tanf.non_cash.income_limit.gross.KS.atDate d)
  else if t.core.stateCodeStr == "KY" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.KY.atDate d))
  else if t.core.stateCodeStr == "LA" then
      (gov.hhs.tanf.non_cash.income_limit.gross.LA.atDate d)
  else if t.core.stateCodeStr == "MA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.MA.atDate d))
  else if t.core.stateCodeStr == "MD" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.MD.atDate d))
  else if t.core.stateCodeStr == "ME" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.ME.atDate d))
  else if t.core.stateCodeStr == "MI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.MI.atDate d))
  else if t.core.stateCodeStr == "MN" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.MN.atDate d))
  else if t.core.stateCodeStr == "MO" then
      (gov.hhs.tanf.non_cash.income_limit.gross.MO.atDate d)
  else if t.core.stateCodeStr == "MS" then
      (gov.hhs.tanf.non_cash.income_limit.gross.MS.atDate d)
  else if t.core.stateCodeStr == "MT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.MT.atDate d))
  else if t.core.stateCodeStr == "NC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NC.atDate d))
  else if t.core.stateCodeStr == "ND" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.ND.atDate d))
  else if t.core.stateCodeStr == "NE" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NE.atDate d))
  else if t.core.stateCodeStr == "NH" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NH.atDate d))
  else if t.core.stateCodeStr == "NJ" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NJ.atDate d))
  else if t.core.stateCodeStr == "NM" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NM.atDate d))
  else if t.core.stateCodeStr == "NV" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NV.atDate d))
  else if t.core.stateCodeStr == "NY" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.NY.atDate d))
  else if t.core.stateCodeStr == "OH" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.OH.atDate d))
  else if t.core.stateCodeStr == "OK" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.OK.atDate d))
  else if t.core.stateCodeStr == "OR" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.OR.atDate d))
  else if t.core.stateCodeStr == "PA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.PA.atDate d))
  else if t.core.stateCodeStr == "RI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.RI.atDate d))
  else if t.core.stateCodeStr == "SC" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.SC.atDate d))
  else if t.core.stateCodeStr == "SD" then
      (gov.hhs.tanf.non_cash.income_limit.gross.SD.atDate d)
  else if t.core.stateCodeStr == "TN" then
      (gov.hhs.tanf.non_cash.income_limit.gross.TN.atDate d)
  else if t.core.stateCodeStr == "TX" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.TX.atDate d))
  else if t.core.stateCodeStr == "UT" then
      (gov.hhs.tanf.non_cash.income_limit.gross.UT.atDate d)
  else if t.core.stateCodeStr == "VA" then
      (gov.hhs.tanf.non_cash.income_limit.gross.VA.atDate d)
  else if t.core.stateCodeStr == "VI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.VI.atDate d))
  else if t.core.stateCodeStr == "VT" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.VT.atDate d))
  else if t.core.stateCodeStr == "WA" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.WA.atDate d))
  else if t.core.stateCodeStr == "WI" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.WI.atDate d))
  else if t.core.stateCodeStr == "WV" then (ExtRat.fin
      (gov.hhs.tanf.non_cash.income_limit.gross.WV.atDate d))
  else (gov.hhs.tanf.non_cash.income_limit.gross.WY.atDate d)))))

/-- `policyengine_us/variables/gov/hhs/tanf/non_cash/meets_tanf_non_cash_net_income_test.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def meetsTanfNonCashNetIncomeTest (t : TaxUnit) (d : Date) : Bool :=
  ((!(decide ((boolToRat (if (isTanfNonCashHheod t d) then (if t.core.stateCodeStr == "AL"
      then gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.AL.atDate d
  else if t.core.stateCodeStr == "AZ" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.AZ.atDate d
  else if t.core.stateCodeStr == "CA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.CA.atDate d
  else if t.core.stateCodeStr == "CO" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.CO.atDate d
  else if t.core.stateCodeStr == "CT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.CT.atDate d
  else if t.core.stateCodeStr == "DC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.DC.atDate d
  else if t.core.stateCodeStr == "DE" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.DE.atDate d
  else if t.core.stateCodeStr == "FL" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.FL.atDate d
  else if t.core.stateCodeStr == "GA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.GA.atDate d
  else if t.core.stateCodeStr == "GU" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.GU.atDate d
  else if t.core.stateCodeStr == "HI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.HI.atDate d
  else if t.core.stateCodeStr == "IA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.IA.atDate d
  else if t.core.stateCodeStr == "ID" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.ID.atDate d
  else if t.core.stateCodeStr == "IL" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.IL.atDate d
  else if t.core.stateCodeStr == "IN" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.IN.atDate d
  else if t.core.stateCodeStr == "KY" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.KY.atDate d
  else if t.core.stateCodeStr == "LA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.LA.atDate d
  else if t.core.stateCodeStr == "MA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MA.atDate d
  else if t.core.stateCodeStr == "MD" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MD.atDate d
  else if t.core.stateCodeStr == "ME" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.ME.atDate d
  else if t.core.stateCodeStr == "MI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MI.atDate d
  else if t.core.stateCodeStr == "MN" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MN.atDate d
  else if t.core.stateCodeStr == "MS" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MS.atDate d
  else if t.core.stateCodeStr == "MT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.MT.atDate d
  else if t.core.stateCodeStr == "NC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NC.atDate d
  else if t.core.stateCodeStr == "ND" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.ND.atDate d
  else if t.core.stateCodeStr == "NE" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NE.atDate d
  else if t.core.stateCodeStr == "NH" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NH.atDate d
  else if t.core.stateCodeStr == "NJ" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NJ.atDate d
  else if t.core.stateCodeStr == "NM" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NM.atDate d
  else if t.core.stateCodeStr == "NV" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NV.atDate d
  else if t.core.stateCodeStr == "NY" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.NY.atDate d
  else if t.core.stateCodeStr == "OH" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.OH.atDate d
  else if t.core.stateCodeStr == "OK" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.OK.atDate d
  else if t.core.stateCodeStr == "OR" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.OR.atDate d
  else if t.core.stateCodeStr == "PA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.PA.atDate d
  else if t.core.stateCodeStr == "RI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.RI.atDate d
  else if t.core.stateCodeStr == "SC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.SC.atDate d
  else if t.core.stateCodeStr == "TX" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.TX.atDate d
  else if t.core.stateCodeStr == "VA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.VA.atDate d
  else if t.core.stateCodeStr == "VI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.VI.atDate d
  else if t.core.stateCodeStr == "VT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.VT.atDate d
  else if t.core.stateCodeStr == "WA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.WA.atDate d
  else if t.core.stateCodeStr == "WI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.WI.atDate d
  else gov.hhs.tanf.non_cash.income_limit.net_applies.hheod.WV.atDate d) else (if
      t.core.stateCodeStr == "AL" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.AL.atDate d
  else if t.core.stateCodeStr == "AZ" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.AZ.atDate d
  else if t.core.stateCodeStr == "CA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.CA.atDate d
  else if t.core.stateCodeStr == "CO" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.CO.atDate d
  else if t.core.stateCodeStr == "CT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.CT.atDate d
  else if t.core.stateCodeStr == "DC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.DC.atDate d
  else if t.core.stateCodeStr == "DE" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.DE.atDate d
  else if t.core.stateCodeStr == "FL" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.FL.atDate d
  else if t.core.stateCodeStr == "GA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.GA.atDate d
  else if t.core.stateCodeStr == "GU" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.GU.atDate d
  else if t.core.stateCodeStr == "HI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.HI.atDate d
  else if t.core.stateCodeStr == "IA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.IA.atDate d
  else if t.core.stateCodeStr == "ID" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.ID.atDate d
  else if t.core.stateCodeStr == "IL" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.IL.atDate d
  else if t.core.stateCodeStr == "IN" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.IN.atDate d
  else if t.core.stateCodeStr == "KY" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.KY.atDate d
  else if t.core.stateCodeStr == "LA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.LA.atDate d
  else if t.core.stateCodeStr == "MA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MA.atDate d
  else if t.core.stateCodeStr == "MD" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MD.atDate d
  else if t.core.stateCodeStr == "ME" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.ME.atDate d
  else if t.core.stateCodeStr == "MI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MI.atDate d
  else if t.core.stateCodeStr == "MN" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MN.atDate d
  else if t.core.stateCodeStr == "MS" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MS.atDate d
  else if t.core.stateCodeStr == "MT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.MT.atDate d
  else if t.core.stateCodeStr == "NC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NC.atDate d
  else if t.core.stateCodeStr == "ND" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.ND.atDate d
  else if t.core.stateCodeStr == "NE" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NE.atDate d
  else if t.core.stateCodeStr == "NH" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NH.atDate d
  else if t.core.stateCodeStr == "NJ" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NJ.atDate d
  else if t.core.stateCodeStr == "NM" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NM.atDate d
  else if t.core.stateCodeStr == "NV" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NV.atDate d
  else if t.core.stateCodeStr == "NY" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.NY.atDate d
  else if t.core.stateCodeStr == "OH" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.OH.atDate d
  else if t.core.stateCodeStr == "OK" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.OK.atDate d
  else if t.core.stateCodeStr == "OR" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.OR.atDate d
  else if t.core.stateCodeStr == "PA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.PA.atDate d
  else if t.core.stateCodeStr == "RI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.RI.atDate d
  else if t.core.stateCodeStr == "SC" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.SC.atDate d
  else if t.core.stateCodeStr == "TX" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.TX.atDate d
  else if t.core.stateCodeStr == "VA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.VA.atDate d
  else if t.core.stateCodeStr == "VI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.VI.atDate d
  else if t.core.stateCodeStr == "VT" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.VT.atDate d
  else if t.core.stateCodeStr == "WA" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.WA.atDate d
  else if t.core.stateCodeStr == "WI" then
      gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.WI.atDate d
  else gov.hhs.tanf.non_cash.income_limit.net_applies.non_hheod.WV.atDate d))) ≠ 0))) ||
      (decide ((snapNetIncomeFpgRatio t d) ≤ (gov.usda.snap.income.limit.net.atDate d))))

/-- `policyengine_us/variables/gov/hhs/tanf/non_cash/is_tanf_non_cash_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def isTanfNonCashEligible (t : TaxUnit) (d : Date) : Bool :=
  (((meetsTanfNonCashGrossIncomeTest t d) && (meetsTanfNonCashNetIncomeTest t d)) &&
      (meetsTanfNonCashAssetTest t d))

end Lawlib.USA
