/-
Generated by pe2lean 0.1.0 from policyengine-us 1.783.0.
DO NOT EDIT — regenerate with `pe2lean extract` (DESIGN.md §5).

Agriculture Department programs, chiefly SNAP and school meals.

Continues the module of the same name. The law
here quotes rules from other agencies, which Lean
must see first; the split is a compilation order,
not a distinction in the law.
-/
import Lawlib.Core.Money
import Lawlib.Core.Date
import Lawlib.Core.Entity
import Lawlib.Core.ExtRat
import Lawlib.Core.Scale
import Lawlib.Household
import Lawlib.Parameters
import Lawlib.USA.DOE
import Lawlib.USA.SSA
import Lawlib.USA.HUD
import Lawlib.USA.FCC
import Lawlib.USA.IRS
import Lawlib.USA.ED
import Lawlib.USA.ACA
import Lawlib.USA.General
import Lawlib.USA.USDA
import Lawlib.USA.HHS
import Lawlib.USA.SSA.Part2
import Lawlib.USA.HUD.Part2
import Lawlib.USA.IRS.Part2
import Lawlib.USA.ED.Part2
import Lawlib.USA.ACA.Part2
import Lawlib.USA.General.Part2
import Lawlib.USA.USDA.Part2
import Lawlib.USA.HHS.Part2
import Lawlib.USA.HUD.Part3
import Lawlib.USA.FCC.Part3
import Lawlib.USA.ED.Part3
import Lawlib.USA.USDA.Part3
import Lawlib.USA.HHS.Part3
import Lawlib.USA.ACA.Part4
import Lawlib.USA.HHS.Part4
import Lawlib.USA.IRS.Part5

namespace Lawlib.USA
open Lawlib
open Lawlib.Parameters

set_option linter.unusedVariables false

set_option maxHeartbeats 1000000
set_option maxRecDepth 8192

/-- `policyengine_us/variables/gov/usda/snap/eligibility/meets_snap_categorical_eligibility.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def meetsSnapCategoricalEligibility (t : TaxUnit) (d : Date) : Bool :=
  (((allBy t.members fun p => ((decide ((ssi t p d) > 0)) || p.ssa.receivesSsi)) ||
      (decide ((boolToRat (isTanfNonCashEligible t d) + ((tanf t d) / 12)) > 0))) ||
      t.hhs.receivesTanf)

/-- `policyengine_us/variables/gov/usda/snap/eligibility/is_snap_eligible.py`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def isSnapEligible (t : TaxUnit) (d : Date) : Bool :=
  ((((((meetsSnapNetIncomeTest t d) && (meetsSnapGrossIncomeTest t d)) &&
      (meetsSnapAssetTest t d)) || (meetsSnapCategoricalEligibility t d)) && (anyBy
      t.members fun p => ((!(isSnapIneligibleStudent t p d)) &&
      (isSnapImmigrationStatusEligible t p d)))) && (meetsSnapWorkRequirements t d))

/-- `policyengine_us/variables/gov/usda/snap/snap_normal_allotment.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def snapNormalAllotment (t : TaxUnit) (d : Date) : Rat :=
  (if (isSnapEligible t d) then (max (t.usda.snapMinAllotment : Rat)
      ((snapMaxAllotment t d) - (snapExpectedContribution t d))) else 0)

/-- `policyengine_us/variables/gov/usda/snap/snap_if_takes_up.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def snapIfTakesUp (t : TaxUnit) (d : Date) : Rat :=
  (if (gov.usda.snap.abolish_snap.atDate d) then 0 else ((snapNormalAllotment t d)
  + t.usda.snapEmergencyAllotment
  + t.statesDc.dcSnapTemporaryLocalBenefit))

/-- `policyengine_us/variables/gov/usda/snap/snap.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def snap (t : TaxUnit) (d : Date) : Rat :=
  (if t.usda.takesUpSnapIfEligible then (snapIfTakesUp t d) else 0)

/-- `meets_school_meal_categorical_eligibility.py`
    in `policyengine_us/variables/gov/usda/school_meals/`
    policyengine-us 1.783.0, entity spm_unit, value_type bool. -/
def meetsSchoolMealCategoricalEligibility (t : TaxUnit) (d : Date) : Bool :=
  (decide ((((snap t d) * 12)
  + (tanf t d)
  + t.usda.fdpir
  + (sumBy t.members fun p => boolToRat p.coreP2.wasInFosterCare)
  + boolToRat t.core.isHomeless
  + (sumBy t.members fun p => boolToRat p.coreP1.isRunawayChild)
  + (sumBy t.members fun p => boolToRat p.coreP1.isMigratoryChild)
  + (sumBy t.members fun p => boolToRat p.hhs.isHeadStartEligible)) ≠ 0))

/-- `policyengine_us/variables/gov/usda/wic/meets_wic_categorical_eligibility.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def meetsWicCategoricalEligibility (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (((((decide (((snap t d) + ((tanf t d) / 12)) > 0)) || t.usda.receivesSnap) ||
      t.hhs.receivesTanf) || (medicaidEnrolled t p d)) || (anyBy t.members fun p =>
      ((medicaidEnrolled t p d) && (p.coreP1.isPregnant ||
      (p.usda.wicCategory == WICCategory.INFANT)))))

/-- `policyengine_us/variables/gov/usda/wic/is_wic_eligible.py`
    policyengine-us 1.783.0, entity person, value_type bool. -/
def isWicEligible (t : TaxUnit) (p : Person) (d : Date) : Bool :=
  (((!(p.usda.wicCategory == WICCategory.NONE)) &&
      ((meetsWicIncomeTest t d) || (meetsWicCategoricalEligibility t p d))) &&
      p.usda.isWicAtNutritionalRisk)

/-- `policyengine_us/variables/gov/usda/school_meals/school_meal_tier.py`
    policyengine-us 1.783.0, entity spm_unit, value_type Enum. -/
def schoolMealTier (t : TaxUnit) (d : Date) : SchoolMealTier :=
  (if (((decide
      ((schoolMealFpgRatio t d) ≤ (gov.usda.school_meals.income.limit.FREE.atDate d))) ||
      (meetsSchoolMealCategoricalEligibility t d)) || (stateHasUniversalFreeSchoolMeals t
      d)) then SchoolMealTier.FREE else (if (decide ((schoolMealFpgRatio t d) ≤
      (gov.usda.school_meals.income.limit.REDUCED.atDate d))) then SchoolMealTier.REDUCED
      else SchoolMealTier.PAID))

/-- `policyengine_us/variables/gov/usda/school_meals/free_school_meals.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def freeSchoolMeals (t : TaxUnit) (d : Date) : Rat :=
  ((boolToRat ((schoolMealTier t d) == SchoolMealTier.FREE)) * (schoolMealNetSubsidy t d))

/-- `policyengine_us/variables/gov/usda/school_meals/reduced_price_school_meals.py`
    policyengine-us 1.783.0, entity spm_unit, value_type float. -/
def reducedPriceSchoolMeals (t : TaxUnit) (d : Date) : Rat :=
  ((boolToRat ((schoolMealTier t d) == SchoolMealTier.REDUCED)) * (schoolMealNetSubsidy t
      d))

/-- `policyengine_us/variables/gov/usda/wic/wic_if_takes_up.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def wicIfTakesUp (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if (isWicEligible t p d) then (if (gov.usda.wic.abolish_wic.atDate d) then 0 else (max (0
      : Rat) ((if p.usda.wicFoodPackageStr == "BREASTFEEDING" then
      gov.usda.wic.value.BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD" then gov.usda.wic.value.CHILD.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_12_23_MONTHS" then
      gov.usda.wic.value.CHILD_12_23_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_24_59_MONTHS" then
      gov.usda.wic.value.CHILD_24_59_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING" then
      gov.usda.wic.value.FULLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING_MULTIPLES" then
      gov.usda.wic.value.FULLY_BREASTFEEDING_MULTIPLES.atDate d
  else if p.usda.wicFoodPackageStr == "I-BF-A" then gov.usda.wic.value.«I-BF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF-B" then gov.usda.wic.value.«I-BF-B».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-A" then gov.usda.wic.value.«I-BF/FF-A».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-B" then gov.usda.wic.value.«I-BF/FF-B».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-C" then gov.usda.wic.value.«I-BF/FF-C».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-FF-A" then gov.usda.wic.value.«I-FF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-FF-B" then gov.usda.wic.value.«I-FF-B».atDate d
  else if p.usda.wicFoodPackageStr == "II-BF" then gov.usda.wic.value.«II-BF».atDate d
  else if p.usda.wicFoodPackageStr == "II-BF/FF" then gov.usda.wic.value.«II-BF/FF».atDate d
  else if p.usda.wicFoodPackageStr == "II-FF" then gov.usda.wic.value.«II-FF».atDate d
  else if p.usda.wicFoodPackageStr == "INFANT" then gov.usda.wic.value.INFANT.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_FULLY_FORMULA_FED" then
      gov.usda.wic.value.INFANT_0_3_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_PARTIALLY_BREASTFED" then
      gov.usda.wic.value.INFANT_0_3_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_5_FULLY_BREASTFED" then
      gov.usda.wic.value.INFANT_0_5_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_FULLY_FORMULA_FED" then
      gov.usda.wic.value.INFANT_4_5_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_PARTIALLY_BREASTFED" then
      gov.usda.wic.value.INFANT_4_5_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_BREASTFED" then
      gov.usda.wic.value.INFANT_6_11_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_FORMULA_FED" then
      gov.usda.wic.value.INFANT_6_11_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_PARTIALLY_BREASTFED" then
      gov.usda.wic.value.INFANT_6_11_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_AVERAGE" then
      gov.usda.wic.value.INFANT_AVERAGE.atDate d
  else if p.usda.wicFoodPackageStr == "IV-A" then gov.usda.wic.value.«IV-A».atDate d
  else if p.usda.wicFoodPackageStr == "IV-B" then gov.usda.wic.value.«IV-B».atDate d
  else if p.usda.wicFoodPackageStr == "NONE" then gov.usda.wic.value.NONE.atDate d
  else if p.usda.wicFoodPackageStr == "PARTIALLY_BREASTFEEDING" then
      gov.usda.wic.value.PARTIALLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM" then gov.usda.wic.value.POSTPARTUM.atDate
      d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM_NON_BREASTFEEDING" then
      gov.usda.wic.value.POSTPARTUM_NON_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT" then gov.usda.wic.value.PREGNANT.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_MULTIPLE_FETUSES" then
      gov.usda.wic.value.PREGNANT_MULTIPLE_FETUSES.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_SINGLETON" then
      gov.usda.wic.value.PREGNANT_SINGLETON.atDate d
  else if p.usda.wicFoodPackageStr == "V" then gov.usda.wic.value.V.atDate d
  else if p.usda.wicFoodPackageStr == "VI" then gov.usda.wic.value.VI.atDate d
  else gov.usda.wic.value.VII.atDate d) + ((boolToRat
      (gov.usda.wic.cvb.replaces_included_value.atDate d)) * ((if p.usda.wicFoodPackageStr
      == "BREASTFEEDING" then gov.usda.wic.cvb.current.BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD" then gov.usda.wic.cvb.current.CHILD.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_12_23_MONTHS" then
      gov.usda.wic.cvb.current.CHILD_12_23_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_24_59_MONTHS" then
      gov.usda.wic.cvb.current.CHILD_24_59_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING" then
      gov.usda.wic.cvb.current.FULLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING_MULTIPLES" then
      gov.usda.wic.cvb.current.FULLY_BREASTFEEDING_MULTIPLES.atDate d
  else if p.usda.wicFoodPackageStr == "I-BF-A" then gov.usda.wic.cvb.current.«I-BF-A».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-BF-B" then gov.usda.wic.cvb.current.«I-BF-B».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-A" then
      gov.usda.wic.cvb.current.«I-BF/FF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-B" then
      gov.usda.wic.cvb.current.«I-BF/FF-B».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-C" then
      gov.usda.wic.cvb.current.«I-BF/FF-C».atDate d
  else if p.usda.wicFoodPackageStr == "I-FF-A" then gov.usda.wic.cvb.current.«I-FF-A».atDate
      d
  else if p.usda.wicFoodPackageStr == "I-FF-B" then gov.usda.wic.cvb.current.«I-FF-B».atDate
      d
  else if p.usda.wicFoodPackageStr == "II-BF" then gov.usda.wic.cvb.current.«II-BF».atDate d
  else if p.usda.wicFoodPackageStr == "II-BF/FF" then
      gov.usda.wic.cvb.current.«II-BF/FF».atDate d
  else if p.usda.wicFoodPackageStr == "II-FF" then gov.usda.wic.cvb.current.«II-FF».atDate d
  else if p.usda.wicFoodPackageStr == "INFANT" then gov.usda.wic.cvb.current.INFANT.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.current.INFANT_0_3_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.current.INFANT_0_3_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_5_FULLY_BREASTFED" then
      gov.usda.wic.cvb.current.INFANT_0_5_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.current.INFANT_4_5_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.current.INFANT_4_5_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_BREASTFED" then
      gov.usda.wic.cvb.current.INFANT_6_11_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.current.INFANT_6_11_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.current.INFANT_6_11_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_AVERAGE" then
      gov.usda.wic.cvb.current.INFANT_AVERAGE.atDate d
  else if p.usda.wicFoodPackageStr == "IV-A" then gov.usda.wic.cvb.current.«IV-A».atDate d
  else if p.usda.wicFoodPackageStr == "IV-B" then gov.usda.wic.cvb.current.«IV-B».atDate d
  else if p.usda.wicFoodPackageStr == "NONE" then gov.usda.wic.cvb.current.NONE.atDate d
  else if p.usda.wicFoodPackageStr == "PARTIALLY_BREASTFEEDING" then
      gov.usda.wic.cvb.current.PARTIALLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM" then
      gov.usda.wic.cvb.current.POSTPARTUM.atDate d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM_NON_BREASTFEEDING" then
      gov.usda.wic.cvb.current.POSTPARTUM_NON_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT" then
      gov.usda.wic.cvb.current.PREGNANT.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_MULTIPLE_FETUSES" then
      gov.usda.wic.cvb.current.PREGNANT_MULTIPLE_FETUSES.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_SINGLETON" then
      gov.usda.wic.cvb.current.PREGNANT_SINGLETON.atDate d
  else if p.usda.wicFoodPackageStr == "V" then gov.usda.wic.cvb.current.V.atDate d
  else if p.usda.wicFoodPackageStr == "VI" then gov.usda.wic.cvb.current.VI.atDate d
  else gov.usda.wic.cvb.current.VII.atDate d) - (if p.usda.wicFoodPackageStr ==
      "BREASTFEEDING" then gov.usda.wic.cvb.included_in_value.BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD" then
      gov.usda.wic.cvb.included_in_value.CHILD.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_12_23_MONTHS" then
      gov.usda.wic.cvb.included_in_value.CHILD_12_23_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "CHILD_24_59_MONTHS" then
      gov.usda.wic.cvb.included_in_value.CHILD_24_59_MONTHS.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING" then
      gov.usda.wic.cvb.included_in_value.FULLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "FULLY_BREASTFEEDING_MULTIPLES" then
      gov.usda.wic.cvb.included_in_value.FULLY_BREASTFEEDING_MULTIPLES.atDate d
  else if p.usda.wicFoodPackageStr == "I-BF-A" then
      gov.usda.wic.cvb.included_in_value.«I-BF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF-B" then
      gov.usda.wic.cvb.included_in_value.«I-BF-B».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-A" then
      gov.usda.wic.cvb.included_in_value.«I-BF/FF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-B" then
      gov.usda.wic.cvb.included_in_value.«I-BF/FF-B».atDate d
  else if p.usda.wicFoodPackageStr == "I-BF/FF-C" then
      gov.usda.wic.cvb.included_in_value.«I-BF/FF-C».atDate d
  else if p.usda.wicFoodPackageStr == "I-FF-A" then
      gov.usda.wic.cvb.included_in_value.«I-FF-A».atDate d
  else if p.usda.wicFoodPackageStr == "I-FF-B" then
      gov.usda.wic.cvb.included_in_value.«I-FF-B».atDate d
  else if p.usda.wicFoodPackageStr == "II-BF" then
      gov.usda.wic.cvb.included_in_value.«II-BF».atDate d
  else if p.usda.wicFoodPackageStr == "II-BF/FF" then
      gov.usda.wic.cvb.included_in_value.«II-BF/FF».atDate d
  else if p.usda.wicFoodPackageStr == "II-FF" then
      gov.usda.wic.cvb.included_in_value.«II-FF».atDate d
  else if p.usda.wicFoodPackageStr == "INFANT" then
      gov.usda.wic.cvb.included_in_value.INFANT.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.included_in_value.INFANT_0_3_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_3_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.included_in_value.INFANT_0_3_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_0_5_FULLY_BREASTFED" then
      gov.usda.wic.cvb.included_in_value.INFANT_0_5_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.included_in_value.INFANT_4_5_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_4_5_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.included_in_value.INFANT_4_5_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_BREASTFED" then
      gov.usda.wic.cvb.included_in_value.INFANT_6_11_FULLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_FULLY_FORMULA_FED" then
      gov.usda.wic.cvb.included_in_value.INFANT_6_11_FULLY_FORMULA_FED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_6_11_PARTIALLY_BREASTFED" then
      gov.usda.wic.cvb.included_in_value.INFANT_6_11_PARTIALLY_BREASTFED.atDate d
  else if p.usda.wicFoodPackageStr == "INFANT_AVERAGE" then
      gov.usda.wic.cvb.included_in_value.INFANT_AVERAGE.atDate d
  else if p.usda.wicFoodPackageStr == "IV-A" then
      gov.usda.wic.cvb.included_in_value.«IV-A».atDate d
  else if p.usda.wicFoodPackageStr == "IV-B" then
      gov.usda.wic.cvb.included_in_value.«IV-B».atDate d
  else if p.usda.wicFoodPackageStr == "NONE" then
      gov.usda.wic.cvb.included_in_value.NONE.atDate d
  else if p.usda.wicFoodPackageStr == "PARTIALLY_BREASTFEEDING" then
      gov.usda.wic.cvb.included_in_value.PARTIALLY_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM" then
      gov.usda.wic.cvb.included_in_value.POSTPARTUM.atDate d
  else if p.usda.wicFoodPackageStr == "POSTPARTUM_NON_BREASTFEEDING" then
      gov.usda.wic.cvb.included_in_value.POSTPARTUM_NON_BREASTFEEDING.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT" then
      gov.usda.wic.cvb.included_in_value.PREGNANT.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_MULTIPLE_FETUSES" then
      gov.usda.wic.cvb.included_in_value.PREGNANT_MULTIPLE_FETUSES.atDate d
  else if p.usda.wicFoodPackageStr == "PREGNANT_SINGLETON" then
      gov.usda.wic.cvb.included_in_value.PREGNANT_SINGLETON.atDate d
  else if p.usda.wicFoodPackageStr == "V" then gov.usda.wic.cvb.included_in_value.V.atDate d
  else if p.usda.wicFoodPackageStr == "VI" then gov.usda.wic.cvb.included_in_value.VI.atDate
      d
  else gov.usda.wic.cvb.included_in_value.VII.atDate d)))))) else 0)

/-- `policyengine_us/variables/gov/usda/wic/wic.py`
    policyengine-us 1.783.0, entity person, value_type float. -/
def wic (t : TaxUnit) (p : Person) (d : Date) : Rat :=
  (if p.usda.takesUpWicIfEligible then (wicIfTakesUp t p d) else 0)

end Lawlib.USA
